### ISSUE TITLE
Apply the search term to the Show total rows count

### ISSUE THREAD

**Issue by NanorPiwik** [matomo-org/matomo#14473] opened 2019-05-23 17:27 UTC
When we enter a search term for the page url report the show total rows count apply to the full report and does not include only the search we performed.

**Comment by 9joshua** [comment] 2023-08-23 22:59
Another request for the same.

Example:
![image](https://github.com/matomo-org/matomo/assets/20234985/ae16d937-884a-461a-8b70-c85370a9f19c)

**Comment by michalkleiner** [comment] 2023-09-27 02:48
Marking this as a bug since the search-based filtering of the table isn't correctly applied to the totals row.

**Comment by sgiehl** [comment] 2023-09-28 14:08
That is more likely an issue of the order the filters are applied. The totals row is afaik calculated quite early and the search filter is applied quite lately before it's displayed. Might not be an easy one to tackle that, as applying the search eariler might make problems when e.g. the labels are manipulated in the API methods and the search should be applied afterwards.

**Comment by randy-innocraft** [comment] 2024-05-16 01:15
This is a duplicate of another issue, https://github.com/matomo-org/matomo/issues/21814 and the status will be tracked as part of that ticket. Closing this one for now.

**Closed by randy-innocraft** 2024-05-16 01:15 UTC
Labels: Bug, c: Usability

**Comment by sgiehl** [comment] 2024-05-17 07:39
@randy-innocraft When closing issues here, please ensure to close them with the correct status and/or add an according label.
