### ISSUE TITLE
Remove/anonymize personal information from URLs automatically 

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#13516] opened 2018-10-01 19:57 UTC
Interesting article see https://brianclifton.com/blog/2017/09/07/remove-pii-from-google-analytics/

Eg anonymize email addresses etc.

**Comment by mattab** [comment] 2020-01-21 05:55
Marking as duplicate of https://github.com/matomo-org/matomo/issues/15427

**Closed by mattab** 2020-01-21 05:55 UTC
Labels: c: Privacy
