### ISSUE TITLE
Page Overlay stuck on "Loading..."

### ISSUE THREAD

**Issue by Findus23** [matomo-org/matomo#14764] opened 2019-08-13 11:19 UTC
very similar to https://github.com/matomo-org/matomo/issues/11768
not like https://github.com/matomo-org/matomo/issues/12815 (no error or failed request)

Not sure since when, but the page overlay doesn't really seem to work anymore.
It only shows the loading screen but doesn't actually do anything:
![image](https://user-images.githubusercontent.com/6266037/62937372-b50cbe00-bdcc-11e9-91d7-a21c56a0ae06.png)
There are no errors in the console, no failed HTTP requests and not even any HTTP requests apart from the assets of the page (so no calls to the API)

This can also be reproduced [on demo.matomo.org](https://demo.matomo.org/index.php?module=Overlay&period=month&date=today&idSite=62#?l=https$3A$2F$2Fdivezone.net$2Fjobs$3F__enterprise_demo$3Ddemo.matomo.org$26__enterprise_demo_idsite$3D62)

and has been reported on the forum:
https://forum.matomo.org/t/page-overlay-fehler/33851

**Comment by peterbo** [comment] 2019-08-14 23:50
Same here on 3 different instances (MTM 3.11)

**Comment by tsteur** [comment] 2019-08-14 23:51
This should have been fixed in https://github.com/matomo-org/matomo/pull/14766

**Comment by peterbo** [comment] 2019-08-14 23:55
Fix works, thanks, Thomas!

**Comment by tiptronic85** [comment] 2020-01-28 15:07
I had the same issue, i upgraded to 3.13.1 version, and now i'm getting logged out.
Anyone with this problem?

**Comment by polarbirke** [comment] 2020-02-20 13:23
I'm seeing the exact same failing behaviour with 3.13.2 in latest Firefox and latest Chrome for several of our websites:

- loading spinner shown, but nothing happens
- no errors in the console
- no failed HTTP requests

I've seen this happen before (August 2019) and I know the fix worked, because the Page Overlay was working fine in November 2019. Could this be another regression?

**Comment by chrisprog20** [comment] 2020-02-25 14:39
I also want to report that in 3.13.3 the Page Overlay does not work anymore (tested in Chrome, Firefox and Edge browser).
Also: If I want to login with the App "Internet Explorer 11" of Windows 10 I fail to get logged in with my admin user. I then get the message "Error: Your session has expired due to inactivity. Please log in to continue." The login with other browsers works.

**Comment by chrisprog20** [comment] 2020-02-25 14:43
@polarbirke: Maybe you try the newest version 3.13.3. There the page overlay works - even in Firefox.
But: I cannot login with the App "Internet Explorer 11" in Windows 10 (with 3.13.3). I then get the following error message: "Error: Your session has expired due to inactivity. Please login to continue."
But if I try to login in with other browsers (I tested it with Chrome, Firefox, Edge) I can log in.

**Comment by polarbirke** [comment] 2020-02-25 14:51
Thanks @chrisprog20! Unfortunately I cannot confirm that, I still have the same endless loading spinner without errors with 3.13.3 😞

**Comment by tsteur** [comment] 2020-02-25 19:31
I'll reopen it for now @polarbirke can you confirm this used to work in an older version? Would it be possible to get access to your Matomo? If so, please comment here and send us the details to hello at matomo dot org. A user with view access be enough.

**Comment by polarbirke** [comment] 2020-02-26 11:28
Thank you @tsteur! I can confirm that it was working in November 2019 after a period where I saw the same issue occur in August 2019. I do not remember the relevant version numbers.

I have added a user called "matomo-support" with the mail address you provided and access to Matomo for our company website. I have confirmed just now that the page overlay does still not load for the homepage ('/').

**Comment by chrisprog20** [comment] 2020-02-26 12:47
@polarbirke: Oh, ok! Great that @tsteur helps you! :)

**Comment by tsteur** [comment] 2020-02-27 03:55
BTW when viewing overlay, make sure to disable any active ad blocker or similar.

Thanks for sending the login details btw. Could someone apply these 2 minor changes and see if it helps? https://github.com/matomo-org/matomo/compare/3.x-dev...issue_14764?quick_pull=1

It seems we're still sending the strict referrer policy there.

**Comment by polarbirke** [comment] 2020-02-27 15:57
> Could someone apply these 2 minor changes and see if it helps? https://github.com/matomo-org/matomo/compare/3.x-dev...issue_14764?quick_pull=1

Hej Thomas, thanks for looking into it. Was the above intended for me? 🤔

**Comment by chrisprog20** [comment] 2020-02-27 16:50
@polarbirke: Thomas did not explicitly mean you but you can give it a try by checking if his fix in https://github.com/matomo-org/matomo/compare/3.x-dev...issue_14764?quick_pull=1 solves your problem ;)

**Comment by sgiehl** [comment] 2020-03-05 10:01
@polarbirke were you able to apply the changes and check if that fixes your issue with the Overlay?

@chrisprog20  your login issue with IE 11 will be fixed with #15633

**Comment by polarbirke** [comment] 2020-03-05 11:25
Hi folks,

we applied the patch to our installation today and it did not fix the issue – HOWEVER @tsteur was on exactly the right track, only it was us, not you. 👀

Our DevOps had decided to hardwire `referrer-policy: strict-origin` in Apache for all our servers, including our Matomo instance. We've relaxed that with `setifempty` now, so Matomo's `same-origin` header is not overwritten.

Thank you all for your generous support and apologies for making our problem your problem! 🙏

/cc @chrisprog20  @sgiehl

**Comment by polarbirke** [comment] 2020-03-05 12:12
Addendum: if _we_ want to use `setifempty` it's imperative that Matomo always sets a header – currently you're setting a strict policy or none. I've proposed an update in #15673 if you want to be explicit about your headers and indulge our way of working. 🙌

**Comment by tsteur** [comment] 2020-03-15 19:43
PR was merged so marking it as closed for now. Thanks @polarbirke

**Closed by tsteur** 2020-03-15 19:43 UTC
Labels: Regression

**Comment by polarbirke** [comment] 2020-03-16 08:54
Thank you, @tsteur! 🙏
