### ISSUE TITLE
no popup graph shown after the first in page titles report

### ISSUE THREAD

**Issue by paolobenve** [matomo-org/matomo#15644] opened 2020-02-29 22:13 UTC
3.13.3

Reproduce it this way:

- go to Behaviour -> page titles
- place cursor on a line, and generate the "open row evolution" popup graph
- close it

Now you cannot generate any more popup graph.

Apparently the bug happens only in the page titles report, similar reports haven't this issue

**Comment by tsteur** [comment] 2020-02-29 23:47
Thanks for creating this issue @paolobenve . Can you reproduce this on https://demo.matomo.org/ ? With popup graph I assume you mean row evolution?

**Comment by tsteur** [comment] 2020-02-29 23:47
And was this working for you in an earlier version?

**Comment by paolobenve** [comment] 2020-03-01 06:32
> Can you reproduce this on https://demo.matomo.org/ ?

no, no on that site, which runs 3.13.2

> With popup graph I assume you mean row evolution?

yes

> And was this working for you in an earlier version?

I don't know

**Comment by tsteur** [comment] 2020-03-01 20:10
Just updated it to 3.13.3 @paolobenve . Can you check again maybe? That would be great since I'm not sure how to reproduce it. Seems to work so far.

**Comment by paolobenve** [comment] 2020-03-01 20:38
no, not reproducible... what may be the reason why on my site I have this behaviour?

**Comment by tsteur** [comment] 2020-03-01 20:40
It's honestly hard to say. Is there any chance for us to get a log in to your Matomo so we can investigate there? if so, could you create a user for us and send the details to hello at matomo.org ?

**Comment by paolobenve** [comment] 2020-03-01 20:45
not reproducible.

I can see that on the demo site, when the popup graph is closed, the hash is restored to the value before opening the popup, while on my site the hash doen't change when I close the popup.

What can I do?

**Comment by tsteur** [comment] 2020-03-01 21:00
@paolobenve which browser and which browser version are you using?

**Comment by paolobenve** [comment] 2020-03-01 21:04
Chromium 80.0.3987.87 (Build ufficiale) Built on Ubuntu , running on Ubuntu 18.04 (a 64 bit).

Same behaviour in firefox 73.0.1 (64 bit)

**Comment by tsteur** [comment] 2020-03-02 00:08
@paolobenve this should work in general. If you could create a login for us, so that we can investigate further that would be great?

**Comment by paolobenve** [comment] 2020-03-02 08:27
I created a new no-superuser user, and it doesn't has the bug

Changing its permissions to superuser, it has the bug.

The bug appears when permissions are > view

**Comment by paolobenve** [comment] 2020-03-04 12:58
@tsteur could you reproduce this bug as superuser?

**Comment by tsteur** [comment] 2020-03-04 23:57
@paolobenve I just tried and couldn't reproduce it unfortunately. If you could create a login for us, that would be great and we would try to reproduce it. 

You may even want to first create one other superuser account for yourself and see if you can reproduce it there. Chances are, it might just work. I would then maybe have an idea.

**Comment by paolobenve** [comment] 2020-03-05 08:07
https://cathopedia.org/piwik/index.php?module=CoreHome&action=index&idSite=3&period=day&date=yesterday#?idSite=3&period=year&date=2019-03-15&segment=&category=General_Actions&subcategory=Actions_SubmenuPageTitles

@tsteur where do I send you the credentials?

click on "open row evolution" -> the popup is shown and the hash changes
close the popup with the top right x:  the hash in the location bar doesn't change (bug)
click again on "open row evolution" -> the popup isn't shown

**Comment by tsteur** [comment] 2020-03-05 19:23
You can send them to hello at matomo.org @paolobenve

**Comment by paolobenve** [comment] 2020-03-05 21:18
@tsteur sent

**Comment by tsteur** [comment] 2020-03-05 21:58
@paolobenve I just tried to reproduce this with the login you sent and it works without any issues. Can you try it with that login too?

**Comment by chris246** [comment] 2020-04-04 00:05
I have a similar issues on the page *URLs* view on the Dashboard.
I can't voluntarily trigger it, but it occurs more frequently after expanding the sub rows
page 1/
| - page 1.1/
| -- page 1.1.1/

**Comment by tsteur** [comment] 2020-04-05 20:28
@chris246 same here can you reproduce this on https://demo.matomo.org ? 

Can you create a different user in your Matomo and check if it happens with that user as well?

**Comment by chris246** [comment] 2020-04-09 13:57
No, but on the demo installation I found an other issue:
I can't re-collapse *diving* any more...

On my local installation, the bug also occurs with a new user.

Furthermore, on my local installation when clicking on "Select a row to compare" ("Wählen Sie eine Zeile zum Vergleichen"), the current dialog sometimes does not close. Closing it manually and selecting an additional row works though.

**Comment by sgiehl** [comment] 2020-04-09 14:15
@chris246 does the label of the row selected for row evolution maybe contain a special char? There's a known bug, which is already fixed for Matomo 4.
To check that you could replace this line:
https://github.com/matomo-org/matomo/blob/7c52d9df25e7863bde0c92345cc270c1fc6e4f12/plugins/CoreHome/javascripts/broadcast.js#L808
with
```js
if(param != 'segment' && param != 'popover') {
```

Let me know if that fixes your issue and we will consider including the fix in the next 3.x release as well.

**Comment by chris246** [comment] 2020-04-09 14:28
The page URLs are generated by TYPO3 for this website: https://docs.typo3.org/m/typo3/reference-tca/master/en-us/ColumnsConfig/Type/Slug.html

After changing the line as suggested, I could not yet trigger the bug again.
I'll post a new reply here, if it occurs again.

Regarding the Row comparing: Shall I create a new issue for that?

**Comment by Findus23** [comment] 2020-04-20 08:48
So it seems like this has already been fixed with https://github.com/matomo-org/matomo/pull/15520/commits/10b5a85ed0ebd089a401e1a0c87f1a883516db62 and https://github.com/matomo-org/matomo/pull/15805

In case this is not fixed by changing that line (and regenerating the JS), please comment and I'll reopen the issue.

**Closed by Findus23** 2020-04-20 08:48 UTC

**Comment by chris246** [comment] 2020-05-04 20:24
Hi,
I observed the bug again twice using 3.13.5 :/
