### ISSUE TITLE
Error in Events report: Unsupported pivot: the subtable dimension for 'Events.Event Actions' does not match the requested pivotBy dimension

### ISSUE THREAD

**Issue by phoob** [matomo-org/matomo#9716] opened 2016-02-05 10:08 UTC
After upgrading to Piwik 2.16.0, I get errors when viewing the events report, specifically when I click to view the "Event Actions" sub-report. Instead of a table, the following error message is displayed:

`Unsupported pivot: the subtable dimension for 'Events.Event Actions' does not match the requested pivotBy dimension. [subtable dimension = Events.EventName, pivot by dimension = Events.EventCategory]`

And if I immediately go to the Administration page thereafter, I get this additional error message:

`ERROR: Failed to get data from API: Unsupported pivot: the subtable dimension for 'Events.Event Actions' does not match the requested pivotBy dimension. [subtable dimension = Events.EventName, pivot by dimension = Events.EventCategory] #0 /var/www/xx.xx.xx/public_html/core/DataTable/Filter/PivotByDimension.php(170): Piwik\DataTable\Filter\PivotByDimension-&gt;checkSupportedPivot() #1 [internal function]: Piwik\DataTable\Filter\PivotByDimension-&gt;__construct(Object(Piwik\DataTable), 'Events.getActio...', 'Events.EventCat...', '', 0, 0) #2 /var/www/xx.xx.xx/public_html/core/DataTable.php(493): ReflectionClass-&gt;newInstanceArgs(Array) #3 /var/www/xx.xx.xx/public_html/core/API/DataTablePostProcessor.php(160): Piwik\DataTable-&gt;filter('PivotByDimensio...', Array) #4 /var/www/xx.xx.xx/public_html/core/API/DataTablePostProcessor.php(110): Piwik\API\DataTablePostProcessor-&gt;applyPivotByFilter(Object(Piwik\DataTable)) #5 /var/www/xx.xx.xx/public_html/core/Plugin/Visualization.php(444): Piwik\API\DataTablePostProcessor-&gt;process(Object(Piwik\DataTable)) #6 /var/www/xx.xx.xx/public_html/core/Plugin/Visualization.php(185): Piwik\Plugin\Visualization-&gt;applyFilters() #7 /var/www/xx.xx.xx/public_html/core/Plugin/ViewDataTable.php(414): Piwik\Plugin\Visualization-&gt;buildView() #8 /var/www/xx.xx.xx/public_html/core/Plugin/Report.php(338): Piwik\Plugin\ViewDataTable-&gt;render() #9 /var/www/xx.xx.xx/public_html/core/Plugin/Controller.php(327): Piwik\Plugin\Report-&gt;render() #10 /var/www/xx.xx.xx/public_html/plugins/Events/Controller.php(96): Piwik\Plugin\Controller-&gt;renderReport('getAction') #11 /var/www/xx.xx.xx/public_html/plugins/Events/Controller.php(48): Piwik\Plugins\Events\Controller-&gt;indexEvent('indexAction') #12 [internal function]: Piwik\Plugins\Events\Controller-&gt;indexAction() #13 /var/www/xx.xx.xx/public_html/core/FrontController.php(495): call_user_func_array(Array, Array) #14 /var/www/xx.xx.xx/public_html/core/FrontController.php(99): Piwik\FrontController-&gt;doDispatch(NULL, NULL, NULL) #15 /var/www/xx.xx.xx/public_html/core/dispatch.php(34): Piwik\FrontController-&gt;dispatch() #16 /var/www/xx.xx.xx/public_html/index.php(27): require_once('/var/www/xx.xx...') #17 {main}`

I have Piwik running on PHP 5.5.9-1ubuntu4.14 on Ubuntu 14.04.3 LTS.

I have also posted this issue in the [Piwik forum](http://forum.piwik.org/t/error-in-events-report-after-upgrading-to-piwik-2-16-0/17918).

**Comment by phoob** [comment] 2016-02-05 10:38
Tested in latest Safari, Chrome and Firefox on Mac OS, and IE11 on Windows.

**Comment by tsteur** [comment] 2016-02-07 18:52
What are the steps to reproduce this? I couldn't reproduce it. Are you using any custom plugins? 

@mattab could you reproduce it?

**Comment by phoob** [comment] 2016-02-08 13:04
@tsteur Here are the steps to reproduce:

1. Go to Piwik dashboard
2. Open the `Actions` menu
3. Open the `Events` report
4. Click on `Event Actions` in the `Top Events` link list
5. Observe first error message (see screen shot 1)
6. Click on the cog wheel in the top right corner to go to `Administration`
7. Observe second error message (see screen shot 2)

![Screen shot 1](https://cloud.githubusercontent.com/assets/1475800/12886273/52d4861c-ce6c-11e5-8aad-687b03d7816f.png)

![Screen shot 2](https://cloud.githubusercontent.com/assets/1475800/12886282/64bdb290-ce6c-11e5-8f32-2d1001691658.png)

**Comment by tsteur** [comment] 2016-02-10 08:18
Thx. I can reproduce it with these steps: https://github.com/piwik/piwik/issues/9667 

Tried to fix it but currently couldn't find a way to do it. Need to have a more detailed look some day later

**Comment by hoang89** [comment] 2016-02-19 09:28
How can i escape this bug to view normal events, i cannot view events when this bug occur

**Comment by tsteur** [comment] 2016-02-22 08:38
If you can, try to switch to another visualization. Or create a new user and view the reports with this user.

**Comment by tsteur** [comment] 2016-03-08 01:39
@phoob @hoang89 did it work to switch to another visualization?

**Comment by phoob** [comment] 2016-03-08 11:43
Can you please describe how you mean I should do to switch to another visualization? As you can in my attached screen shot above (the first one) there is just an error message – no data table where I can choose another visualization.

**Comment by tsteur** [comment] 2016-03-08 20:04
I just realize this is not possible there as you are seeing this all the time. In my case, when I reproduced it, I was still able to change the visualization.

Can you maybe try to execute a query on the DB:
```sql
delete from piwik_option where option_name like "viewDataTableParameters_$YOUR_PIWIK_USERNAME_Events.%";
-- for example when username is "root"
delete from piwik_option where option_name like "viewDataTableParameters_root_Events.%";
```

**Comment by phoob** [comment] 2016-03-08 20:09
Awesome! Deleting the options from piwik_option solved the issue for me.

**Comment by mattab** [comment] 2016-03-10 15:52
FYI Added a FAQ to document how to reset the report settings: [ How do I reset the visualisations settings stored for a specific user, or for all users?](https://piwik.org/faq/troubleshooting/faq_21433/)

**Comment by mattab** [comment] 2016-03-30 05:30
Hopefully this issue is fixed in 2.16.1-b3 (Learn more: http://piwik.org/faq/how-to-update/faq_159/ ). I'm closing now but if you experience this issue and are already using > 2.16.1-b3 please leave a comment asking to re-open this issue.

**Comment by gregoireclemencin** [comment] 2018-02-08 10:46
Just for the sake of it, I ran into that same issue recently with Matomo 3.3.0. 
Had to issue the SQL DELETE command to overcome the issue. 

Here is one scenario where this happens (and can be reproduced): 
* I have the Event Widget on my Dashboard (it works fine) 
* I go to the Event report page, and request a pivoted View from the Category table (it does the job alright) 
* I go back to the Dahsboard --> Event Widget displays the following error message: 
> Unsupported pivot: the subtable dimension for 'Events.Noms d'évènement' does not match the requested pivotBy dimension. [subtable dimension = Events.EventAction, pivot by dimension = Events.EventCategory] 
* Same issue, if I then go back to the Event page. 

Not a big deal in my case (tiny personal web site), but there you go. 

Thanks.

**Comment by sgiehl** [comment] 2019-03-17 14:26
I found a way to reproduce:
- Go to any Events report
- switch to the alternate dimension in report footer
- switch to pivoted view of the report
- go back to the original dimension of the report

--> this will result in a similar error as above

The error is caused by this:
When switching to the pivoted view, Matomo will automatically store the viewDataTable settings for this report. This means a `pivotBy` value will be stored. When switching back to the other Dimension, that stored value is being reused, but doesn't match the subtable anymore, causing the mentioned error.

**Closed** 2019-05-20 09:30 UTC
Labels: Bug
