### ISSUE TITLE
Enhancement: Share Dashboard with other users, but not just copy but keep in Sync (optional)

### ISSUE THREAD

**Issue by peterbo** [matomo-org/matomo#16269] opened 2020-08-06 18:10 UTC
This would be very helpful for experienced users to assist less experienced users. Or for an analyst showing interesting stuff to other users. As soon as the experienced user changes stuff on the shared Dashboard, it should also change for the users the dashboard was shared with.

**Comment by tsteur** [comment] 2020-08-06 20:43
thanks @peterbo . I think this is a duplicate of https://github.com/matomo-org/matomo/issues/6964 ? Let me know if that's not the case.

**Closed by tsteur** 2020-08-06 20:43 UTC

**Comment by peterbo** [comment] 2020-08-06 23:34
Thanks @tsteur - sorry, seems like I was too sloppy searching for probable duplicates :sweat_smile:
