### ISSUE TITLE
Setting parameters rows_to_display is not allowed. Please report this bug to the Matomo team.

### ISSUE THREAD

**Issue by davidbehler** [matomo-org/matomo#16349] opened 2020-08-27 06:49 UTC
Version 3.14.0

Found this error in our logs:
Setting parameters rows_to_display is not allowed. Please report this bug to the Matomo team.

Here are the errors that occured on the same timestamp:
![grafik](https://user-images.githubusercontent.com/96450/91404462-efaf9000-e841-11ea-932c-e28c8e51b55b.png)

Is there any other info you need? I can't tell you exactly what happend before this error was logged, I just noticed it now.

**Comment by tsteur** [comment] 2020-08-27 20:08
Thanks @davidbehler . Was there maybe even more information before that? It would maybe help us identify by what this was caused.

**Comment by davidbehler** [comment] 2020-08-28 05:34
Yeah, sorry. Not sure why I left out a couple of entries :/

![grafik](https://user-images.githubusercontent.com/96450/91524996-d1f53000-e900-11ea-95fd-aecb2671e5fb.png)

**Comment by tsteur** [comment] 2020-08-30 21:07
@davidbehler thanks for this. Things are getting slightly more clear but not sure yet where this is happening.

Do you remember what you did when that happened? 

If I had to guess then a shown metric was changed in a so called "evolution graph" in either AbTesting, Cohorts, Goals, Paid Advertising, or Referrers plugin but that's more of a guess so far. 

Do you maybe know if you use any third party plugins? You can find them by going to "Matomo -> Admin -> Plugins" and click on "Third-party" in "Installed plugins"

**Comment by davidbehler** [comment] 2020-08-31 06:51
I have not installed any third party plugins.

I only noticed the error the day after it happend and I'm not the only user of this Matomo install, so sadly I can't tell you what caused it :/

**Comment by tsteur** [comment] 2020-08-31 22:01
Thanks for this @davidbehler 

I see this in our logs also happening on occasion. I think this might happen somehow related to events. eg maybe on 

```
POST /index.php?date=2020-08-28&viewDataTable=graphVerticalBar&module=Events&action=getCategory&secondaryDimension=eventAction&idSite=1&period=week&random=2875&totals=0&columns=nb_visits&filter_sort_column=nb_visits&disable_generic_filters=0
```

Might be related to the "Bar" visualisation in events. Maybe when changing a metric there.

I can actually reproduce this now exactly that way. Change visualisation eg in Events Category to "Bar" and then change the metric.

The request looks like this:

![image](https://user-images.githubusercontent.com/273120/91773036-1acb2280-ec3a-11ea-8f03-870dfa9e2f06.png)

Thanks again for your help @davidbehler

**Comment by MichaIng** [comment] 2020-10-05 20:10
Interesting, I just got this after upgrading to v4 beta2: https://forum.matomo.org/t/setting-parameters-rows-to-display-is-not-allowed/38828

In my case only happens when trying to change (back) to a non-table graph (bars or piechart) and only for the two "Times" plugin charts.

**Comment by tsteur** [comment] 2020-10-21 19:06
fixed in https://github.com/matomo-org/matomo/pull/16601

**Closed by tsteur** 2020-10-21 19:06 UTC
Labels: Bug
