### ISSUE TITLE
Unique Visitor on Rollup Reports

### ISSUE THREAD

**Issue by ibril15** [matomo-org/matomo#14971] opened 2019-10-08 18:53 UTC
Hello,

I'm seeing two places where Rollup Reports do not seem to calculate Unique Visitors.

In Visitors->Locations, the map correctly shows "1,234 Unique Visitors at the top" but each country is the same shade of blue, and hovering over each one says "0 unique visitors."

In Email Reports, the Unique Visitor count is properly displayed if the report is only for a day, but if it's for a week it's 0.

As per https://matomo.org/faq/how-to/faq_113/, I know that Unique Visitor is an expensive metric, but I don't see anything related to configurations for the above two issues.  Is it too expensive to enable those counts on large Rollup Sites?

Thanks.

-Igor

**Comment by tsteur** [comment] 2019-10-08 20:34
Hi @ibril15 for Premium Feature related questions could you get in touch with our support at shop at innocraft.com? That be great. Thanks!

**Comment by mattab** [comment] 2019-12-24 02:20
Also another maybe more pressing similar issue: **When viewing weekly reports in Roll-Ups, Unique visitors is returning 0.**

Can be reproduced at  https://demo.matomo.org/index.php?module=CoreHome&action=index&date=2019-12-13&period=week&idSite=60#?idSite=60&period=week&date=2019-12-13&segment=&category=General_Visitors&subcategory=General_Overview

**Comment by tsteur** [comment] 2019-12-24 02:24
Moving this to 4.2 as it's not so important and not a breaking change. Therefore it should not be in 4.0.

**Comment by mattab** [comment] 2020-01-13 23:36
What it looks like for weeks:
![Screenshot from 2020-01-14 12-35-34](https://user-images.githubusercontent.com/466765/72301053-760bcd00-36ca-11ea-81de-bff5489fa5aa.png)

and months:

![Screenshot from 2020-01-14 12-35-45](https://user-images.githubusercontent.com/466765/72301051-75733680-36ca-11ea-85a7-fb712816ffcf.png)
Expected instead to see the Unique Visitors metric correctly processed.

**Comment by tsteur** [comment] 2020-01-13 23:41
BTW: My understanding is that
```
enable_processing_unique_visitors_multiple_sites = 1
```

will process these metrics likely. This issue is actually more about removing the unique user column and unique visitor columns when the flag is disabled.

**Comment by tsteur** [comment] 2021-07-23 01:12
Moved this to an internal premium feature issue

**Closed by tsteur** 2021-07-23 01:12 UTC
Labels: Bug, Major
