### ISSUE TITLE
Uncaught Error: cannot call methods on liveWidget prior to initialisation; attempted to call method 'started' .

### ISSUE THREAD

**Issue by nalinvaidya** [matomo-org/matomo#14493] opened 2019-05-28 04:29 UTC
We are getting Uncaught error : cannot call methods on liveWidget prior to initialisation; attempted to call method 'started' in java script.

Steps to replicate:
1. login to demo.matomo.org
2. Go to visitor -> Real Time.
3. Click on the any action and check the console for the error.

![javascript error](https://user-images.githubusercontent.com/50700880/58450838-6dac5500-812e-11e9-931d-956e558a1987.png

**Comment by fdellwing** [comment] 2019-05-28 12:53
Can you test #14415? It might already solve the issue.

**Comment by tsteur** [comment] 2019-05-28 12:55
duplicate of https://github.com/matomo-org/matomo/issues/14374

**Closed by tsteur** 2019-05-28 12:55 UTC
