### ISSUE TITLE
Referrers: When Graph value is selected, it is redirecting to blank page.

### ISSUE THREAD

**Issue by ghost** [matomo-org/matomo#10535] opened 2016-09-21 15:20 UTC
Referrers: When Graph value is selected, it is redirecting to blank page 

Please refer: https://youtu.be/bxNofrG7vVU

**Comment by mattab** [comment] 2016-09-26 20:58
Hello, on your video I don't see a blank page. What do you mean exactly? it looks like it's working for me

**Comment by srinivasskc** [comment] 2016-09-27 07:58
Blank Page means : Blank Screen, It does not show the graph, 

Can you explain the functionality when i progress on the graph, why it displays Blank Graph Screen?

**Comment by srinivasskc** [comment] 2016-09-27 07:59
Check the video length: 0.25-0.30

**Comment by mattab** [comment] 2016-09-27 20:31
Can you reproduce this error on demo.piwik.org as well ?

**Comment by srinivasskc** [comment] 2016-10-02 10:17
Yes. I can do it on both demo.piwik.org also

**Comment by mattab** [comment] 2016-10-02 19:57
Can you reproduce with Chrome or Firefox ? somehow I cannot reproduce such issue that the page becomes white...

**Comment by sgiehl** [comment] 2023-10-09 22:31
Closing as this report is quite old, and the problem should be fixed meanwhile anyway.

**Closed by sgiehl** 2023-10-09 22:31 UTC
Labels: Waiting for user feedback
