### ISSUE TITLE
Row Evolution PopUp opens after Visitors Log Popup Closed

### ISSUE THREAD

**Issue by chandrakant-hake** [matomo-org/matomo#15875] opened 2020-04-28 03:58 UTC
I am facing the issue that when we open Row Evolution popup and close it and then Open Visitors Log for the same Record and Closes it then Row Evolution Popup Opens Directly Without any click. and after that, if we refresh the page then also Row Evolution Popup comes in. 

- It is not removing Popup from ParamStack also and from URL as well.
- It Pushes Row Evolution Popup in Stack Multiple Times.

**Comment by sgiehl** [comment] 2020-04-29 13:45
Hi @chandrakant-hake. Thanks for creating the issue. Are you already using the latest version of Matomo? I'm not able to reproduce that at the moment. There was an issue for rows that contained special chars, might that be the case for you, or is that happening for every row?

**Comment by chandrakant-hake** [comment] 2020-04-29 13:52
Yes, I am Using Latest Version. Does '/'(slash),'-'(dash) and '.'(Dot) will be Treated as Special Character.

**Comment by chandrakant-hake** [comment] 2020-04-29 13:56
Also, My Pages Has Subpages Please check that Case too.
Means:: 
Customer is page Having Sub Pages : 
Account and /index
account has Subpage like Create and /index

**Comment by sgiehl** [comment] 2020-04-29 15:50
The issue with special chars matches your error report. But it should have been fixed with #15809 in the latest 3.13.5, which was released yesterday.

**Comment by sgiehl** [comment] 2020-04-30 08:10
@chandrakant-hake would you mind checking again if you are already on 3.13.5? I'm not able to reproduce that locally or on our demo. If you are still having this issue with 3.13.5 could you maybe give us access to your Matomo instance so we can have a look and check if we can fix that? If so you can send the credentials to stefan{at}matomo.org

**Comment by chandrakant-hake** [comment] 2020-04-30 08:13
I will check and let you know

**Comment by chandrakant-hake** [comment] 2020-04-30 12:45
I have updated my code base, but that doesn't work for me with the issue.
**I am mentioning Steps to Reproduce error**

- Select Any website on your machine Which has Some data **(Not Single Page Website)**.
- Click on Behaviour > Pages
- You will see Selected Website Pages on Right Side
- Click on **Open Row Evolution** which is in front of one of the Page
- Row Evolution Popup will be open for that Page
- Click on the close button of Popup **(X)**
- Then click on **Open Segment Visit Log** of that Same Page
- Click on the close button of Popup **(X)**
_**After this Row Evolution Popup gets open**_ 

**ScreenShots**
_Step 1:_
![1](https://user-images.githubusercontent.com/64453914/80709752-78742480-8b0b-11ea-9cfe-9ffad407964e.png)
_Step2:_
![2](https://user-images.githubusercontent.com/64453914/80709812-95105c80-8b0b-11ea-83f6-8e86cfb553df.png)
_Step3:_
![3](https://user-images.githubusercontent.com/64453914/80709824-9b063d80-8b0b-11ea-8477-1c2feb1964e9.png)
_Step4:_
![4](https://user-images.githubusercontent.com/64453914/80709890-bf621a00-8b0b-11ea-8ab4-e207c6768d6f.png)
_Step5: Where Error Comes In -->_
![5](https://user-images.githubusercontent.com/64453914/80709955-d3a61700-8b0b-11ea-8d0d-1cdb240597bc.png)

**Comment by chandrakant-hake** [comment] 2020-05-05 04:22
@sgiehl Any Updates to my Query??

**Comment by sgiehl** [comment] 2020-05-05 06:49
Hi @chandrakant-hake. Thanks again for the details. I was able to reproduce that now. Seems that only happen when clicking the `X`. If you click outside the popover it will be closed as well, but won't reopen after another one...

**Closed** 2020-05-06 07:24 UTC
Labels: Bug, c: Usability
