### ISSUE TITLE
Emailed report ignoring Report Period

### ISSUE THREAD

**Issue by CoreyBurger** [matomo-org/matomo#16644] opened 2020-11-01 20:43 UTC
Matamo 3.14.1

Steps to repoduce:
1. Create a report
2. Choose Report Period of "year", "week" or "month"
3. Send test email

Expected result:
Email sends report with correct period

Actual result:
Report only shows period of "day", not "year", "week" or "month"

I've check the backend SQL databse - it is storing the period correctly in the DB

**Comment by tsteur** [comment] 2020-11-01 22:39
@CoreyBurger what version of Matomo are you using? Is this when you manually trigger the report to be sent or automated?

**Comment by CoreyBurger** [comment] 2020-11-01 23:14
Matomo 3.14.1. It happens when I download or email it. 
![MatomoError1](https://user-images.githubusercontent.com/30996781/97818052-fd73fe00-1c54-11eb-9c8b-8b1d96640020.png)

**Comment by CoreyBurger** [comment] 2020-11-01 23:15
Configuration of the report
![MatomoError2](https://user-images.githubusercontent.com/30996781/97818070-19779f80-1c55-11eb-8e15-e780bd591b9b.png)

**Comment by tsteur** [comment] 2020-11-01 23:40
Thanks @CoreyBurger this is a duplicate of https://github.com/matomo-org/matomo/issues/11367 and will close it therefore. @CoreyBurger be good to watch the other issue. In this case it uses the selected date in the shown date selector above the list of reports.

**Closed by tsteur** 2020-11-01 23:40 UTC

**Comment by CoreyBurger** [comment] 2020-11-01 23:59
Thanks @tsteur for the quick triage
