### ISSUE TITLE
Upgrade 3.9.1 to 3.10.0 leads to date errors when viewing website details

### ISSUE THREAD

**Issue by roock** [matomo-org/matomo#14644] opened 2019-07-09 18:44 UTC
After upgrading from 3.9.1 to 3.10.0 I am receiving an error when I try to view the details of a website. The "All Websites" page works fine, but when I try to open a website i get the error that the time range is invalid.
![matomo-error](https://user-images.githubusercontent.com/533172/60914442-d6d4cb80-a289-11e9-9bb6-9b636b1cf1d7.png)

PHP Error Log:
```
2019/07/09 18:34:11 [error] 32#32: *72 FastCGI sent in stderr: "PHP message: Error in Matomo: The date &#039;-0001-11-30&#039; is a date before first website was online. Try date that&#039;s after Aug 6, 1991 (timestamp 681436800).: -62169984000" while reading response header from upstream, client: x.x.x.x, server: , request: "GET /index.php?module=CoreHome&action=index&date=today&period=day&idSite=5 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm7.sock:", host: "xxxxxxx", referrer: "https://xxxxxxx/index.php?module=MultiSites&action=index&idSite=1&period=day&date=today"
```

Firefox 67, PHP 7.2.19 using Docker Image from https://github.com/crazy-max/docker-matomo

output from database migration:
```

    *** Update ***

    Database Upgrade Required

    Your Matomo database is out-of-date, and must be upgraded before you can continue.

    Matomo database will be upgraded from version 3.9.1 to the new version 3.10.0.

    *** Note: this is a Dry Run ***

    ALTER TABLE `piwik_report` ADD COLUMN `period_param` VARCHAR(10) NULL;
    ./console plugin:activate "Tour"

    *** End of Dry Run ***


Starting the database upgrade process now. This may take a while, so please be patient.

    *** Update ***

    Database Upgrade Required

    Your Matomo database is out-of-date, and must be upgraded before you can continue.

    Matomo database will be upgraded from version 3.9.1 to the new version 3.10.0.

    The database upgrade process may take a while, so please be patient.

  Executing ALTER TABLE `piwik_report` ADD COLUMN `period_param` VARCHAR(10) NULL;... Done. [1 / 2]
  Executing ./console plugin:activate "Tour"... Done. [2 / 2]

Matomo has been successfully updated!

```

**Comment by tsteur** [comment] 2019-07-14 20:20
@roock what is the URL when you open the dashboard? Feel free to hide the domain. We may need access to the instance if that's possible to quickly have a look as we can't reproduce this

**Comment by roock** [comment] 2019-07-19 15:00
@tsteur Thank you for your feedback. The URL is: https://matomo.example.unknown/index.php?module=CoreHome&action=index&date=today&period=day&idSite=1
Access to instance should be possible. Let me know about the details!

**Comment by tsteur** [comment] 2019-07-21 20:41
Can you email the details to hello at matomo.org? Cheers

**Comment by SivaranjaniMurugeshan** [comment] 2019-11-27 06:55
I have installed the new matomo instance. I got an below same error while creation version on tag manager. 
**Start date: The date '-0001-11-30' is a date before first website was online. Try date that's after Aug 6, 1991 (timestamp 681436800).: -62169984000**

**Comment by tsteur** [comment] 2019-11-27 21:48
This should be fixed in a recent 3.13.0 release

**Comment by tsteur** [comment] 2019-11-27 21:49
I will close this issue as I think we made a few fixes in various places. Let me know if someone is still experiencing this issue.

**Closed by tsteur** 2019-11-27 21:49 UTC

**Comment by roock** [comment] 2020-07-08 18:48
For future reference: the issue was that my superuser created during installation had set  the `date_registered` in `piwik_user` to 0. Changing it to a valid date solved the issue.
