### ISSUE TITLE
Opening a visitor profile in a new window sometimes shows a different visitor's profile

### ISSUE THREAD

**Issue by KaanErturk** [matomo-org/matomo#11078] opened 2016-12-25 21:15 UTC
This happens when you click on a specific visit on the right side of the visitor profile popup. The URL for opening a visitor profile in a new window changes; `visitorId` gets removed and instead `visitId` is added. But that new parameter has no affect and the new page shows the very last visitor's profile.

Steps to reproduce:

1. Go to Visitor Log
2. View a visitor's profile (other than the very last visitor)
3. Click on a specific visit on the right side (even though there is only one)
4. Click on the user ID to open the visitor profile in a new window
5. You will now see the very last visitor's profile (see the URL for parameters mentioned above)

This happens for the `Export this dataset in other formats` link (next to the user ID) as well.

**Comment by mattab** [comment] 2018-09-25 00:55
Hi @KaanErturk Can you still reproduce this issue with Matomo 3.6.0?

**Comment by sgiehl** [comment] 2019-03-17 11:44
This should have been fixed with one of the refactorings of the visitor profiles. I'm not able to reproduce that behavior anymore, nor do I see any way how that could happen with the current code.

**Closed by sgiehl** 2019-03-17 11:44 UTC
Labels: Bug, Waiting for user feedback / Cannot reproduce yet
