### ISSUE TITLE
Chrome and OptOut not working 

### ISSUE THREAD

**Issue by ehwg** [matomo-org/matomo#12225] opened 2017-10-25 07:55 UTC
Hi,
I have a  piwik.domain.eu  piwik installation. My active Site is   www.site.de.
I included the optOut code:

`<iframe frameborder="no" width="100%" height="300px" src="https://piwik.domain.eu /index.php?module=CoreAdminHome&action=optOut&language=de"></iframe>
`

on my site www.site.de/test.html
It is fine in IE, Firefox and even Edge, where the do not track option is recognized.
But unfortunately this seems not to work in Chrome browser. I get the OptOut text and the option to check but this seems not to be recognized. After clicking same text is shown again, saying still opted in.

Calling `https://piwik.domain.eu /index.php?module=CoreAdminHome&action=optOut&language=de ` directly does work in Chrome. 
I found issue  [https://github.com/piwik/piwik/issues/9290] which is a kind different
and neverthelesse added this to the ini file:

`assume_secure_protocol = 1
proxy_client_headers[] = HTTP_X_FORWARDED_FOR
proxy_host_headers[] = HTTP_X_FORWARDED_HOST
`

But it did not have any effect. I have piwik 3.2 installed.

Any ideas or help  would be welcome.  
Kind regards
Eckard.

**Comment by ehwg** [comment] 2017-10-25 09:01
Hi, 
after some more research I found the reason: Chrome browser has a setting for cookies:
chrome://settings/content/cookies
to block third-party cookies.  I guess with this settings then there is no chance to swith off the tracking in chrome other then calling the optOut directly withut a frame in a new window, right?
This means for data protection reasons this has to be added then, or?
Best regards
Eckard.

**Comment by fdellwing** [comment] 2017-10-25 12:02
I tried this with Chrome 59 and Chrome 62 under Linux and it works fine with default browser settings.

So I'm pretty sure that you disabled 3rd-party-cookies by yourself.

**Comment by sgiehl** [comment] 2018-08-18 21:10
Closing as not reproducible and no feedback since months. @ehwg  if you still have that issue with latest version, please create a new issue.

**Closed by sgiehl** 2018-08-18 21:10 UTC
Labels: Waiting for user feedback / Cannot reproduce yet
