### ISSUE TITLE
Reports without data when increasing the data range

### ISSUE THREAD

**Issue by monti-cistella** [matomo-org/matomo#13548] opened 2018-10-05 16:20 UTC
Hi all,

Something strange happens when I query page URL metrics from Behaviour->Pages. When I want to see the page visits of a specific page added to the website a few minutes ago, I wait until the reports archiving is executed (I process reports archiving every hour) and then I query the page URL in Behavior->Pages. If I query the page URL with the calendar filter showing only the today metrics, it works! Then, I increase the data range in the calendar filter. If I filter from yesterday to today, it also works. If I filter from 6 days ago until today, it works too. But when I filter from 14 days ago until today or I apply the year filter, the result is “There is no data for this report.”. It has no sense to me. It doesn’t matter how much time ago you put in the calendar data range, all the visits are from today, so the result should be the same.
You can see this behaviour in this video: 
[https://www.useloom.com/share/c4a979ed31094dd4b387924b68e5a522](https://www.useloom.com/share/c4a979ed31094dd4b387924b68e5a522)

This happens to me in many URLs, but not all of them. Some ones are working well but I cannot appreciate any difference/pattern among them. 

Note: I process reports archiving every hour from cron using the --force-periods=all parameter to force the archiving of day, week, month and year in each execution.

Thanks in advance,
Miquel.

**Comment by mattab** [comment] 2020-01-08 21:22
@monti-cistella the video you posted is not available anymore, but maybe the issue happens when you select a date range overlapping 2 months? This is covered in https://github.com/matomo-org/matomo/issues/15363

Closing this one as likely duplicate, or it may be a duplicate of: https://github.com/matomo-org/matomo/issues/14123

**Closed by mattab** 2020-01-08 21:22 UTC
