### ISSUE TITLE
Users are converting but not retaining pre-conversion history in visitor log

### ISSUE THREAD

**Issue by beatelite** [matomo-org/matomo#11112] opened 2016-12-29 18:14 UTC
Summary: when a visitor triggers a signup goal, we register them and associate their userid to piwik for tracking. 

However, all pre-goal-conversion visit history for that user is orphaned as an anonymous visitor, in that, it's not showing under the userid for that visitor when viewing the log or custom dimension reports. Piwik seems to attribute all pre-conversion history (including the conversion itself) to an anonymous visitor with the same IP and shows post-conversion history to the userId profile.

I swear piwik used to combine pre and post conversion history under one userID once the anonymous user signed in or registered. Is this a bug or as designed? What am I missing?

I am using 2.16.1

**Comment by mattab** [comment] 2017-01-02 00:35
Currently this is how User ID works (by design). However, as explained in https://github.com/piwik/piwik/issues/7691#issuecomment-93869541 amongst other, we may change the way User ID works in the future. Can't say yet as we are under discussion to maybe make several changes. We'll announce it in the issue tracker

**Comment by peachp** [comment] 2019-07-29 15:28
Would be great. It totally makes sense to me show visitor's pre-conversion / pre-login activity from all previous visits. And when they login from another device, the activity from this device should be also shown all under same User ID.

This feature is actually the most crucial for us to use Matomo.
I am considering to hack something together with Custom dimension and my own Cookies / JS / SQL views.

**Comment by tsteur** [comment] 2019-07-29 20:09
I think this should be fixed with https://github.com/matomo-org/matomo/pull/14360

**Comment by mattab** [comment] 2019-11-02 19:40
Could you apply the change in #14360 and confirm whether this fixes the issue for you @beatelite @peachp ?

**Comment by mattab** [comment] 2020-01-23 01:13
Marking as fixed as this should be fixed now, please open a new issue if it's not fixed

**Closed by mattab** 2020-01-23 01:13 UTC
Labels: Enhancement
