### ISSUE TITLE
Download/Outlinks not shown correctly when link contains &

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#15924] opened 2020-05-07 21:46 UTC
Reported in https://wordpress.org/support/topic/some-minor-ui-tips/#post-12794720

You can reproduce it eg using this HTML

```html
<a target="_blank"  href="https://foo.bar/wp-content/plugins/test.php?api_user_id=123455&dlkey=49849494&content_type=application/pdf">PDF</a>
or 
<a target="_blank"  href="https://foo.bar/wp-content/plugins/test.php?api_user_id=123455&amp;dlkey=49849494&amp;content_type=application/pdf">PDF</a>
```

resulting in a false link in visitor log (reports itself seem to be fine)
```
https://foo.bar/wp-content/plugins/test.php?api_user_id=123455&amp;dlkey=49849494&amp;content_type=application/pdf
```

instead of 
```
https://foo.bar/wp-content/plugins/test.php?api_user_id=123455&dlkey=49849494&content_type=application/pdf
```

Quick test shows the tracker might send the correct value, but might be some escaping issue.

**Comment by mattab** [comment] 2020-05-07 23:03
Maybe duplicate of  https://github.com/matomo-org/matomo/issues/11806 ?

**Comment by tsteur** [comment] 2020-05-07 23:39
It's not related to any segmenting or so.

**Comment by tsteur** [comment] 2021-04-05 23:42
there's more insights here https://wordpress.org/support/topic/some-user-facing-logs-have-a-url-encoding-issue-for-ampersands-in-links/ 

Basically, it seems to work in Downloads  reports but not in Visits log and real time widget meaning it is likely indeed an escaping issue.

**Comment by tsteur** [comment] 2021-07-22 22:58
This might be fixed meanwhile. Need to first reproduce it before looking into it.

**Comment by sgiehl** [comment] 2022-06-24 13:02
I'm actually not able to reproduce the tracking issue. If I have a page with the links mentioned in the issue description, both are tracked with the same url. Maybe the browser already removes the encoded ampersands. 
Nevertheless: If I manually trigger tracking a download with an encoded url like:
```
_paq.push(['trackLink', 'https://foo.bar/wp-content/plugins/test.php?api_user_id=132&amp;dlkey=132&amp;content_type=application/pdf', 'download']);
```
That url is displayed encoded in the visitor log, while it works when it's tracked as outlink. Will check why that is the case...

**Closed** 2022-06-28 05:39 UTC
Labels: Bug, Regression
