### ISSUE TITLE
UI_CONTROL_MULTI_SELECT behaves weird (remove UI control?)

### ISSUE THREAD

**Issue by Findus23** [matomo-org/matomo#12832] opened 2018-05-06 10:30 UTC
I just wrote [a plugin](https://plugins.matomo.org/LanguageToogle) which allows switching between languages quickly. For this I created a `UI_CONTROL_MULTI_SELECT` with all languages (the same can be reproduced with https://plugins.matomo.org/RestrictLanguageSelection as I am using the same selector)

I can't really describe it (it feels a bit like `Lights Out`), so here is a video of a try to add French to German:
[high quality](https://giant.gfycat.com/MildGrimAppaloosa.webm)

![gif](https://thumbs.gfycat.com/MildGrimAppaloosa-size_restricted.gif)

**Comment by tsteur** [comment] 2018-05-06 19:43
I'm not 100% sure I get what you mean but yes it is not ideal and it is kind of by design like this. This is simple the multi select we get from materializecss. In the coming up 1.0.0 they improved it a little bit see second example here: https://materializecss.com/select.html but still not ideal. There is not too much we can do I guess unless we embedded another UI library just for this. 
I think you may rather want to use the new multi tuple feature see https://github.com/matomo-org/matomo/blob/3.x-dev/plugins/Morpheus/templates/demo.twig#L362 .

You can use it like this:

```php
            $this->makeSetting('fooBar', array(), FieldConfig::TYPE_ARRAY, function (FieldConfig $field) {
                $field->title = 'Foo Bar';
                $field->description = 'Optionally set one or multiple custom dimensions in scope visit.';
                $field->uiControl = FieldConfig::UI_CONTROL_MULTI_PAIR;
                $field1 = new FieldConfig\MultiPair('Language', 'languageCode', FieldConfig::UI_CONTROL_SELECT);
                $field->uiControlAttributes['field1'] = $field1->toArray();
            }),
```

**Comment by Findus23** [comment] 2018-05-06 19:53
I’m not entirely sure if it is by design that it is impossible to select an entry as always others get selected and removed kind of randomly (Gallicanian and Greek in the above video) and even others get highlighted in the drop down. 

But the new multi tuple feature seem even more user friendly than an correctly working multiselect.

**Comment by tsteur** [comment] 2018-05-07 04:28
Lets remove this UI control in Matomo 4

**Comment by liquidlx** [comment] 2019-09-23 20:37
Hello, I had the same problem and I've found a solution for this one. 

But first, I would like to say that this problem is probably caused by the old version of the materialize.

**How to fix**
We need to add the class 'browser-default' from the materialize to use the browser multi select, using the $uiControlAttributes like that:
`
$field->uiControlAttributes = array('class' => 'browser-default');
`

![Captura de Tela 2019-09-23 às 16 11 23](https://user-images.githubusercontent.com/37184280/65455094-e392a580-de1c-11e9-9a89-f247b5a80ec7.png)

But when we add the class, the label stay behind the selector like that:

![Captura de Tela 2019-09-23 às 12 43 33](https://user-images.githubusercontent.com/37184280/65455338-63207480-de1d-11e9-83f5-e9d474d36a8d.png)

We can fix this making a custom css. See [https://developer.matomo.org/guides/working-with-piwiks-ui](url).

Here's my custom css for that: 

![Captura de Tela 2019-09-23 às 16 18 27](https://user-images.githubusercontent.com/37184280/65455544-d2966400-de1d-11e9-9dd2-84ebb9d4e5cf.png)

The 'for' attribute in the label is the value of the $name variable.

Final result:

![Captura de Tela 2019-09-23 às 16 20 22](https://user-images.githubusercontent.com/37184280/65455667-14bfa580-de1e-11e9-98c6-17cca4956d20.png)

We can add any style for the select (and javascript).

**Comment by tsteur** [comment] 2019-09-23 20:58
cheers @liquidlx feel free to issue a PR for that. Otherwise in Matomo 4 we're planning to upgrade to latest version of materializecss which maybe fixes the issue as well but we're not sure.

**Comment by sgiehl** [comment] 2020-04-14 09:15
guess that one needs to wait until #14082 is done. Or shall we update materializecss upfront?

**Comment by tsteur** [comment] 2020-04-14 22:01
I think maybe @diosmosis already started some work on this?

**Comment by diosmosis** [comment] 2020-04-14 23:51
@tsteur I guess materializecss could be updated/patched on 3.13.5 if it's a small enough change? Otherwise it's a lot of work. I haven't continued on #14082 since it's not as high a priority as other issues, but I can get back to it if needed.

**Comment by tsteur** [comment] 2020-04-15 00:14
We wouldn't want this in 3.X @diosmosis 
We'll get back to it as part of https://github.com/matomo-org/matomo/pull/14082 when there's time.

We can then see if the issue will be fixed automatically maybe.

**Comment by sgiehl** [comment] 2020-06-09 13:13
Now as #14082 has been merged I've just checked it with my plugin and it seems to work as expected now. @Findus23 could you maybe have a quick look, if the multi select works for you as well. Guess we can close this issue then...

**Comment by Findus23** [comment] 2020-06-09 13:54
@sgiehl I rewrote the plugin to a multi-tuple so I have to trust you. Maybe @liquidlx can check. 
But if it still happens, we can simply reopen it.

**Comment by tsteur** [comment] 2020-06-09 19:56
👍 closing it for now

**Closed by tsteur** 2020-06-09 19:56 UTC
Labels: c: Platform
