### ISSUE TITLE
Error: wrong date format when switching from "all websites" to "dashboard"

### ISSUE THREAD

**Issue by DorianVasco** [matomo-org/matomo#15514] opened 2020-02-04 16:08 UTC
I recently found some errors on my matomo installation:
![2020-01-30 11_43_51-Window](https://user-images.githubusercontent.com/6312198/73762124-0db38700-4770-11ea-8553-0f7f339903d7.png)
That occurs when sometimes when I select a custom date on the "all websites" tab and then switching to the dashboard of a single site.
I've found that the url changes after selecting the same date range again:
```
after switching from 'all websites':
https://matomo.dododata.de/index.php?module=CoreHome&action=index&date=2020-01-29%2C2020-02-04&period=range&idSite=13#?idSite=13&period=range&date=2020-01-29%252C2020-02-04&segment=&category=Dashboard_Dashboard&subcategory=1

after selecting the date range again:
https://matomo.dododata.de/index.php?module=CoreHome&action=index&date=2020-01-29%2C2020-02-04&period=range&idSite=13#?idSite=13&period=range&date=2020-01-29,2020-02-04&segment=&category=Dashboard_Dashboard&subcategory=1
```

I use PHP 7.3.14 and Apache 2.4

**Comment by tsteur** [comment] 2020-02-04 19:53
Cheers @DorianVasco This should be a duplicate of https://github.com/matomo-org/matomo/issues/15238

**Closed by tsteur** 2020-02-04 19:53 UTC
