### ISSUE TITLE
Undefined index: nb_pages_per_search

### ISSUE THREAD

**Issue by Findus23** [matomo-org/matomo#15454] opened 2020-01-24 10:16 UTC
This seems like a bug

https://forum.matomo.org/t/problems-with-getsitesearchkeywords-after-update-to-3-13-1/35774

> WARNING: /www/htdocs/<my domain>/plugins/CoreVisualizations/Visualizations/HtmlTable.php(228): Notice - Undefined index: nb_pages_per_search
> WARNING: /www/htdocs/<my domain>/core/DataTable/Row.php(188): Warning - Illegal offset type

> I did a little trial and error. When I disable the “Site Search Keywords” widget on the dashboard, the error message does not appear. When I turn it on again, the message appears again.

**Comment by sgiehl** [comment] 2020-01-24 13:31
Might be a duplicate of #15441

**Closed** 2020-01-27 12:34 UTC
Labels: Bug, duplicate
