### ISSUE TITLE
Visitor graphs not working anymore

### ISSUE THREAD

**Issue by timscha** [matomo-org/matomo#16703] opened 2020-11-11 12:01 UTC
Hello!
I'm unsure if this is a bug or a wrong server configuration, but with Matomo 3 everything worked.

Currently I am using Matomo 4 RC2 with PHP 7.4 and nginx 1.19.4 which is working mostly fine.
But, the graphs stopped working. I still see visitors logged, but the graphs indicated that there are no visitors. Also the statistics are empty.

If you need more information I would really like to help making Matomo even better! :)

Thanks
Tim
![Bildschirmfoto 2020-11-11 um 07 41 29](https://user-images.githubusercontent.com/4650393/98809480-e6d06280-241d-11eb-9ec7-e3812ac99b9c.png)

**Comment by tsteur** [comment] 2020-11-11 19:26
Hi @timscha thanks for taking the time to report this. Very appreciated. I'll close this as a duplicate of https://github.com/matomo-org/matomo/issues/16689 . We're working on a fix for this.

**Closed by tsteur** 2020-11-11 19:26 UTC
