### ISSUE TITLE
Can not read the filename in the downloads view

### ISSUE THREAD

**Issue by tfrdidi** [matomo-org/matomo#11178] opened 2017-01-11 08:26 UTC
I use Piwik 3.0.0, and had some of the previous versions, too. I use it without JS tracking, just by importing server logs. 
Now I need information about **which file is downloaded the most**. The problem with the downloads overview is, that "hierarcical" view only groups the url of the site, not the path of the file (like in the page view).
As we have very long URLs for the downloads, you need a very big monitor to actually see the filename as it is the last part of the URL. In my opinion this contradicts the responsive paradigm of Piwik 3.0.0. On mobile devices there is no chance for me to see which file is downloaded, just the very first part of the download url.

Btw: I already opend a ticket with a solution ([https://github.com/piwik/piwik/issues/11069](https://github.com/piwik/piwik/issues/11069)) which was not accepted. Now I only want to mention my problem and let you find a solution ;-)

**Comment by gaumondp** [comment] 2017-01-11 14:19
Maybe a solution would be to have a parameter where we can specify if we just want filenames and not full path?

Or crop path but from right (then filename is always visible but start of the full URL could be cropped).

**Comment by tfrdidi** [comment] 2017-01-11 19:52
The latter sounds better to me. Not always the filename is sufficient to identify which one was it. Think about several readmes in different folders

**Comment by mattab** [comment] 2017-02-20 17:05
Hi @tfrdidi 
Thanks for the suggestion. Would you mind posting a screenshot showing the problem? 

When you hover on the filename, is there a tooltip showing the full filename maybe?

**Comment by ChrisR1993** [comment] 2017-02-21 00:37
@mattab 
Hi Mattab,

I had the same issue.
For example, page below is normal page which can show the clean "hierarcical" view
+directoryA
   -directotyB
      page.html
so the whole link should be **directoryA/directoryB/page.html**, right? and it can show the "hierarcical".
but when I go to the download page. it cannot show by "hierarcical" and just grouping and showing the 
whole link like below.

**directoryA/directoryB/download.pdf**

And I want the download page show the link by "hierarcical" like
+directoryA 
  -directoryB
      download.pdf

because some link just so long that I cannot read the whole link when it grouped them together.
I hope you can understand my discription and will appreciate your great advise.

Regards,

**Comment by mattab** [comment] 2017-02-21 05:23
@ChrisR1993  Would you mind posting a screenshot showing the problem?

When you hover on the filename, is there a tooltip showing the full filename maybe?

**Comment by ChrisR1993** [comment] 2017-02-21 05:55
@mattab 
thanks for your reply.

This is the page which can show "hierarcical" view .
![page11](https://cloud.githubusercontent.com/assets/25838575/23152333/bdf02aac-f844-11e6-9abd-871ae3afc74d.PNG)

This is the download page just grouping all directory together.
![download page](https://cloud.githubusercontent.com/assets/25838575/23152344/c9cfab68-f844-11e6-98a0-43e415388c77.PNG)

is that can be the "hierarcical" view like the picture 1?
+jp 
  +diet
    +publication
this download page uploaded is all right but some time the link is so long that I cannot read it.
and I know what you mean that hover on the filename, but we are talking the link not the filename.

thanks and regards,

**Comment by mattab** [comment] 2017-02-21 06:37
It is by design that the full path is displayed in downloads. We wanted to keep things simpler for downloads and outlinks and only group by domains. In your screenshots, all the filenames are visible. therefore it's not an issue

**Comment by ChrisR1993** [comment] 2017-02-21 06:50
@mattab 
thank you mattab, so it cannot be changed?

**Comment by mattab** [comment] 2017-02-21 07:12
Not at this time see https://github.com/piwik/piwik/issues/11069

**Comment by ChrisR1993** [comment] 2017-02-21 07:17
@mattab 
Thank you mattab, appreciate your time.

**Comment by ChrisR1993** [comment] 2017-02-21 08:12
@mattab 
mattab, sorry to bother you again.
I just only want to let the download page displayed by  "hierarcical". If the Action-Pages which show the condition of the HTML can display data by  "hierarcical" view, so can I change the PHP code to let the PDF and JPG links into the "Action-Pages" page when the system divide the data? could this behavior solve the problom?

**Comment by tfrdidi** [comment] 2017-02-21 14:35
Hi, 
i use a 24'' monitor with full width. Despite that not all download paths are displayed completely (no i have not influence on the paths). For most of them hovering shows the full name in the tooltip wich is not the best solution, but at least it works. But for some of them the tooltip does not contain the full name, too:

![piwik download long filename](https://cloud.githubusercontent.com/assets/8374395/23169192/1c6da4dc-f84b-11e6-89f2-377f0e1a837b.png)

**Comment by ChrisR1993** [comment] 2017-02-23 05:07
@tfrdidi 
Hi tfrdidi,
I changed the Download data imported to "Action-Pages" page instead of download page, and I worked.
the data is displayed by "hierarcical".

**Comment by tfrdidi** [comment] 2017-03-06 09:22
@ChrisR1993 Thanks for your time! Is this now part of the 3.0.2-Release? Would you mind updating the status of the ticket?

**Comment by mattab** [comment] 2017-10-06 08:40
This was also be improved in the latest beta released today! it would be great if you could test again and let us know if it's improved?

**Comment by MatomoForumNotifications** [comment] 2023-03-24 16:20
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/export-of-download-information/5672/6

**Comment by mattab** [comment] 2023-12-10 11:56
Thanks for contributing to this issue. As it has been a few months since the last activity and we believe this is likely not an issue anymore, we will now close this. If that's not the case, please do feel free to either reopen this issue or [open a new one](https://developer.matomo.org/guides/core-team-workflow#submitting-a-bug-report). We will gladly take a look again!

**Closed by mattab** 2023-12-10 11:56 UTC
Labels: Enhancement, c: Usability
