### ISSUE TITLE
Visits Over Time report requires Annotations plugin to be enabled

### ISSUE THREAD

**Issue by vincent3569** [matomo-org/matomo#11993] opened 2017-08-31 13:14 UTC
Hello to the community

I noticed that the widgetized reports - Visits Over Time - doesn't work.
All the provided links (in embed iframe, in direct link) doesn't work and I have a blank page.

the provided link is as following:
https://piwik.domain_name.fr/index.php?module=Widgetize&action=iframe&forceView=1&viewDataTable=graphEvolution&widget=1&moduleToWidgetize=VisitsSummary&actionToWidgetize=getEvolutionGraph&idSite=2&period=range&date=last30&disableLink=1&widget=1

**Comment by sgiehl** [comment] 2017-08-31 13:20
Not able to reproduce that on our demo: https://demo.piwik.org/index.php?module=Widgetize&action=iframe&forceView=1&viewDataTable=graphEvolution&widget=1&moduleToWidgetize=VisitsSummary&actionToWidgetize=getEvolutionGraph&idSite=7&period=range&date=last30&disableLink=1&widget=1

Do you see any error in browser console or server error log?

**Comment by vincent3569** [comment] 2017-08-31 13:27
I have an error that I can see in Firebug:
![screenshot017](https://user-images.githubusercontent.com/1224809/29925537-e04d7962-8e60-11e7-9d48-0b970ce0fd3b.png)

**Comment by mattab** [comment] 2017-09-18 03:39
@vincent3569 is the plugin `Annotations` enabled in your Piwik? This may be the issue, as it seems Piwik won't work well if that plugin is disabled (as it is referenced from `plugins/CoreHome/javascripts/dataTable.js`)

**Comment by vincent3569** [comment] 2017-09-18 06:58
Hi @mattab 

in fact, Annotations plugin wasn't enabled.
I anable it, but nothing happen and the widgetized reports - Visits Over Time - still doesn't work.
and to be more complete, these reports are not working:
-visitors in real time
-visitor profile
-visitor log

in error_log, for most of not working reports, I can see this error:

[18-Sep-2017 06:53:56 UTC] Error in Piwik: SQLSTATE[42S22]: Column not found: 1054 Unknown column &#039;log_action_event_category.type&#039; in &#039;field list&#039;

**Comment by sgiehl** [comment] 2017-09-18 09:57
This will be fixed with 3.1.1. In the meantime try activating the Events plugin.

**Comment by vincent3569** [comment] 2017-09-25 08:34
I don't know what is fixed in 3.1.1 but the report "Visits Over Time" still need the plugin Annotations to be activated to work.

**Comment by sgiehl** [comment] 2018-03-11 18:15
Just tried to reproduce, but Visits Over Time works with disabled Annotations plugin. If anyone is having issues with disabled Annotations plugin please open a new issue.

**Closed by sgiehl** 2018-03-11 18:15 UTC
Labels: Bug
