### ISSUE TITLE
Matomo 3.13.3 Not Remembering Login [bug]

### ISSUE THREAD

**Issue by ButisitArt** [matomo-org/matomo#15658] opened 2020-03-04 13:11 UTC
My Matomo 3.13.3 (hosted server) install is not remembering my login on either Mac Safari, or Chrome even though cookies are allowed. I have to log in every time I close or quit either browser.

I also have AdGuard turned off for my stats site, as well as all ad blockers turned off in Safari prefs for the site.

This was never a problem before.

**Comment by sgiehl** [comment] 2020-03-04 14:08
this is duplicate of #15625 and will be fixed with next release

**Closed by sgiehl** 2020-03-04 14:08 UTC
