### ISSUE TITLE
Misleading colors for bounce rate and generation time

### ISSUE THREAD

**Issue by jackyhallyday** [matomo-org/matomo#16643] opened 2020-11-01 12:03 UTC
When comparing two periods, the differences are shown in percentage (Visits Overview, for instance).

The problem is: it's ALWAYS green if the value has increased over the previous period, and red otherwise, regardless of if it's a good thing or not.
So:
Bounce rate is decreasing? Red, because it's less.
Generation time is 3s instead of 0.1s? Green, because it's more. 

These colors are not helping.

**Comment by tsteur** [comment] 2020-11-01 19:49
Thanks for creating this issue @jackyhallyday I'm closing this as a duplicate of https://github.com/matomo-org/matomo/issues/15820

**Closed by tsteur** 2020-11-01 19:49 UTC
