### ISSUE TITLE
Bug: Dashboard repeat/duplicate widgets

### ISSUE THREAD

**Issue by Laul0** [matomo-org/matomo#14647] opened 2019-07-10 15:39 UTC
# Summary

Sometimes (twice today), when I'm going to my Dashboard site, all of widgets are duplicated in the dashboard like illustrated in this picture:

<img width="1659" alt="Screen Shot 2019-07-10 at 11 38 23" src="https://user-images.githubusercontent.com/15279205/60983090-5a80cd80-a307-11e9-84c3-c226b13f114a.png">

## Current behavior

* Today, at the **first connection** I met this bug
* More generaly, I'm meting this bug when I'm browser through several page of Matomo and I come back to the dashboard site
* I have to remove manually the duplicate widgets

This behavior occur randomly.

**Comment by tsteur** [comment] 2019-07-14 20:18
@Laul0 are you using the latest Matomo version? Any third party plugins? 

We might need access to this instance to quickly check if that's possible? We can't reproduce this issue here and have never seen it.

**Comment by Laul0** [comment] 2019-07-14 23:18
Hi @tsteur 

Here, all informations about my installation:

## Matomo

Version: **3.10.0**

(I already met this behaviour with the previous version of Matomo.

## Installed and active Plugins

* Actions (core)
* Annotations (core)
* Bandwidth (v3.1.1)
* BotTracker (v1.03)
* BulkTracking (Core)
* Contents (Core)
* CustomDimensions (v3.1.8)
* CustomPiwikJs (Core)
* CustomVariables (Core)
* Dashboard (Core)
* DeviceNetworkInformation (v3.0.3)
* DevicePlugins (Core)
* DevicesDetection (Core)
* Diagnostics (Core)
* Ecommerce (Core)
* Events (Core)
* ExampleAPI (Core)
* ExamplePlugin (Core)
* Feedback (Core)
* GeoIp2 (Core) 
* Goals (Core)
* Heartbeat (Core)
* IceCastStatistics (v1.0.11) 
* ImageGraph (Core)
* Insights (Core)
* IntranetMeasurable (Core)
* Live (Core)
* Login (Core) 
* Marketplace (Core)
* MobileMessaging (Core)
* Monolog (Core)
* MultiSites (Core)
* Overlay (Core)
* PrivacyManager (Core) 
* ProfessionalServices (Core)
* ProtectTrackID (v1.0.0) 
* Referrers (Core)
* Resolution (Core)
* RssWidget (Core)
* SEO (Core)
* ScheduledReports (Core)
* SegmentEditor (Core)
* TagManager (Core)
* Tour (Core)
* Transitions (Core)
* TwoFactorAuth (Core) 
* UserCountry (Core)
* UserCountryMap (Core)
* UserId (Core)
* UserLanguage (Core)
* VisitFrequency (Core)
* VisitTime (Core)
* VisitorInterest (Core)
* VisitsSummary (Core)
* Widgetize (Core)

## Steps to reproduces

I reproduce this behavior by:

* switch from Tag Manager to Dashboard and refresh Dashboard
* switch from Real-Time Log to Dashboard

I didn't reproduce it today...

**Comment by mattab** [comment] 2020-01-21 05:16
Thank you for the report :+1:  To likely fix the issue, could you upgrade to the latest Matomo version?
see https://matomo.org/docs/update/ 

if you still experience this issue afterwards, please re-open this and post a comment. Thanks!

**Comment by CassenH** [comment] 2021-01-13 11:00
I'm experiencing the exact same issue using Matomo Analytics Cloud.

**Comment by tsteur** [comment] 2021-01-13 19:12
I'm pretty sure I have been able to reproduce this as well at some stage or experienced it. Will reopen this issue.

**Comment by matomoto** [comment] 2021-07-01 08:14
Hi, i have the same problem since any of the latest updates. Yet Matomo 4.3.1. I have no idea how it comes. I do not make experience. I have never changed anything on the dashboard. I have all default. No additionally Plugins. Pure Matomo, respectively a former Piwik installation.

I haven't had time to take care of it yet. I just wanted to delete the duplicates already. But now I have decided to look for a solution.

**Comment by mattab** [comment] 2023-12-11 05:19
Thanks for contributing to this issue. As it has been a few months since the last activity and we believe this is likely not an issue anymore, we will now close this. If that's not the case, please do feel free to either reopen this issue or [open a new one](https://developer.matomo.org/guides/core-team-workflow#submitting-a-bug-report). We will gladly take a look again!

**Closed by mattab** 2023-12-11 05:19 UTC
Labels: Bug
