### ISSUE TITLE
Error 'Entry "Piwik\Auth" cannot be resolved' while executing core:archive

### ISSUE THREAD

**Issue by Programie** [matomo-org/matomo#14743] opened 2019-08-08 05:51 UTC
I've configured a cronjob to execute core:archive every hour. In some executions the job fails with an error "There was an error while regenerating container releases: Entry "Piwik\Auth" cannot be resolved: the class is not instantiable".

I've already asked for help in the [Matomo forums](https://forum.matomo.org/t/error-entry-piwik-auth-cannot-be-resolved-the-class-is-not-instantiable-on-execution-of-core-archive-and-core-update/33627) but got referred here to open an issue.

The following exception is thrown:

```
ERROR [2019-08-08 05:01:37] 17942  There was an error while regenerating container releases: Entry "Piwik\Auth" cannot be resolved: the class is not instantiable
Full definition:
Object (
   class = #NOT INSTANTIABLE# Piwik\Auth
   scope = singleton
   lazy = false
)#0 /var/www/b/piwik/vendor/php-di/php-di/src/DI/Definition/Resolver/ObjectCreator.php(243): DI\Definition\Exception\DefinitionException::create(Object(DI\Definition\ObjectDefinition), 'Entry "Piwik\\Au...')
#1 /var/www/b/piwik/vendor/php-di/php-di/src/DI/Definition/Resolver/ObjectCreator.php(126): DI\Definition\Resolver\ObjectCreator->assertClassIsInstantiable(Object(DI\Definition\ObjectDefinition))
#2 /var/www/b/piwik/vendor/php-di/php-di/src/DI/Definition/Resolver/ObjectCreator.php(70): DI\Definition\Resolver\ObjectCreator->createInstance(Object(DI\Definition\ObjectDefinition), Array)
#3 /var/www/b/piwik/vendor/php-di/php-di/src/DI/Definition/Resolver/ResolverDispatcher.php(58): DI\Definition\Resolver\ObjectCreator->resolve(Object(DI\Definition\ObjectDefinition), Array)
#4 /var/www/b/piwik/vendor/php-di/php-di/src/DI/Container.php(303): DI\Definition\Resolver\ResolverDispatcher->resolve(Object(DI\Definition\ObjectDefinition), Array)
#5 /var/www/b/piwik/vendor/php-di/php-di/src/DI/Container.php(131): DI\Container->resolveDefinition(Object(DI\Definition\ObjectDefinition))
#6 /var/www/b/piwik/core/Container/StaticContainer.php(80): DI\Container->get('Piwik\\Auth')
#7 /var/www/b/piwik/core/Piwik.php(567): Piwik\Container\StaticContainer::get('Piwik\\Auth')
#8 /var/www/b/piwik/plugins/CoreHome/Menu.php(32): Piwik\Piwik::getLoginPluginName()
#9 /var/www/b/piwik/plugins/CoreHome/Menu.php(20): Piwik\Plugins\CoreHome\Menu->getLoginModule()
#10 /var/www/b/piwik/core/Menu/MenuTop.php(57): Piwik\Plugins\CoreHome\Menu->configureTopMenu(Object(Piwik\Menu\MenuTop))
#11 /var/www/b/piwik/plugins/TagManager/Controller.php(207): Piwik\Menu\MenuTop->getMenu()
#12 /var/www/b/piwik/plugins/TagManager/Controller.php(53): Piwik\Plugins\TagManager\Controller->renderTemplate('@TagManager/deb...')
#13 [internal function]: Piwik\Plugins\TagManager\Controller->debug()
#14 /var/www/b/piwik/core/FrontController.php(589): call_user_func_array(Array, Array)
#15 /var/www/b/piwik/core/FrontController.php(165): Piwik\FrontController->doDispatch('TagManager', 'debug', Array)
#16 /var/www/b/piwik/plugins/TagManager/Context/WebContext/JavaScriptTagManagerLoader.php(72): Piwik\FrontController->dispatch('TagManager', 'debug')
#17 /var/www/b/piwik/plugins/TagManager/Context/WebContext.php(166): Piwik\Plugins\TagManager\Context\WebContext\JavaScriptTagManagerLoader->getPreviewJsContent()
#18 /var/www/b/piwik/plugins/TagManager/Context/WebContext.php(152): Piwik\Plugins\TagManager\Context\WebContext->addPreviewCode('/*!!\n * Matomo ...', true, true, Array)
#19 /var/www/b/piwik/plugins/TagManager/Model/Container.php(123): Piwik\Plugins\TagManager\Context\WebContext->generate(Array)
#20 /var/www/b/piwik/plugins/TagManager/TagManager.php(253): Piwik\Plugins\TagManager\Model\Container->generateContainer(97, 'DDLlW4wP')
#21 /var/www/b/piwik/core/Access.php(628): Piwik\Plugins\TagManager\TagManager->Piwik\Plugins\TagManager\{closure}()
#22 /var/www/b/piwik/core/Piwik.php(838): Piwik\Access::doAsSuperUser(Object(Closure))
#23 /var/www/b/piwik/plugins/TagManager/TagManager.php(261): Piwik\Piwik::doAsSuperUser(Object(Closure))
#24 /var/www/b/piwik/plugins/TagManager/Tasks.php(34): Piwik\Plugins\TagManager\TagManager->regenerateReleasedContainers()
#25 [internal function]: Piwik\Plugins\TagManager\Tasks->regenerateReleasedContainers(NULL)
#26 /var/www/b/piwik/core/Scheduler/Scheduler.php(264): call_user_func(Array, NULL)
#27 /var/www/b/piwik/core/Scheduler/Scheduler.php(136): Piwik\Scheduler\Scheduler->executeTask(Object(Piwik\Scheduler\Task))
#28 /var/www/b/piwik/plugins/CoreAdminHome/API.php(65): Piwik\Scheduler\Scheduler->run()
#29 /var/www/b/piwik/core/CronArchive.php(617): Piwik\Plugins\CoreAdminHome\API->runScheduledTasks()
#30 /var/www/b/piwik/core/CronArchive.php(317): Piwik\CronArchive->runScheduledTasks()
#31 /var/www/b/piwik/core/Access.php(628): Piwik\CronArchive->Piwik\{closure}()
#32 /var/www/b/piwik/core/CronArchive.php(319): Piwik\Access::doAsSuperUser(Object(Closure))
#33 /var/www/b/piwik/plugins/CoreConsole/Commands/CoreArchiver.php(27): Piwik\CronArchive->main()
#34 /var/www/b/piwik/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): Piwik\Plugins\CoreConsole\Commands\CoreArchiver->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 /var/www/b/piwik/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#36 /var/www/b/piwik/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Piwik\Plugins\CoreConsole\Commands\CoreArchiver), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#37 [internal function]: Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#38 /var/www/b/piwik/core/Console.php(98): call_user_func(Array, Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#39 /var/www/b/piwik/core/Access.php(628): Piwik\Console->Piwik\{closure}()
#40 /var/www/b/piwik/core/Console.php(99): Piwik\Access::doAsSuperUser(Object(Closure))
#41 /var/www/b/piwik/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Piwik\Console->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#42 /var/www/b/piwik/console(27): Symfony\Component\Console\Application->run()
#43 {main}
ERROR [2019-08-08 05:01:38] 17942  There was an error while regenerating container releases: Entry "Piwik\Auth" cannot be resolved: the class is not instantiable
Full definition:
Object (
   class = #NOT INSTANTIABLE# Piwik\Auth
   scope = singleton
   lazy = false
)#0 /var/www/b/piwik/vendor/php-di/php-di/src/DI/Definition/Resolver/ObjectCreator.php(243): DI\Definition\Exception\DefinitionException::create(Object(DI\Definition\ObjectDefinition), 'Entry "Piwik\\Au...')
#1 /var/www/b/piwik/vendor/php-di/php-di/src/DI/Definition/Resolver/ObjectCreator.php(126): DI\Definition\Resolver\ObjectCreator->assertClassIsInstantiable(Object(DI\Definition\ObjectDefinition))
#2 /var/www/b/piwik/vendor/php-di/php-di/src/DI/Definition/Resolver/ObjectCreator.php(70): DI\Definition\Resolver\ObjectCreator->createInstance(Object(DI\Definition\ObjectDefinition), Array)
#3 /var/www/b/piwik/vendor/php-di/php-di/src/DI/Definition/Resolver/ResolverDispatcher.php(58): DI\Definition\Resolver\ObjectCreator->resolve(Object(DI\Definition\ObjectDefinition), Array)
#4 /var/www/b/piwik/vendor/php-di/php-di/src/DI/Container.php(303): DI\Definition\Resolver\ResolverDispatcher->resolve(Object(DI\Definition\ObjectDefinition), Array)
#5 /var/www/b/piwik/vendor/php-di/php-di/src/DI/Container.php(131): DI\Container->resolveDefinition(Object(DI\Definition\ObjectDefinition))
#6 /var/www/b/piwik/core/Container/StaticContainer.php(80): DI\Container->get('Piwik\\Auth')
#7 /var/www/b/piwik/core/Piwik.php(567): Piwik\Container\StaticContainer::get('Piwik\\Auth')
#8 /var/www/b/piwik/plugins/CoreHome/Menu.php(32): Piwik\Piwik::getLoginPluginName()
#9 /var/www/b/piwik/plugins/CoreHome/Menu.php(20): Piwik\Plugins\CoreHome\Menu->getLoginModule()
#10 /var/www/b/piwik/core/Menu/MenuTop.php(57): Piwik\Plugins\CoreHome\Menu->configureTopMenu(Object(Piwik\Menu\MenuTop))
#11 /var/www/b/piwik/plugins/TagManager/Controller.php(207): Piwik\Menu\MenuTop->getMenu()
#12 /var/www/b/piwik/plugins/TagManager/Controller.php(53): Piwik\Plugins\TagManager\Controller->renderTemplate('@TagManager/deb...')
#13 [internal function]: Piwik\Plugins\TagManager\Controller->debug()
#14 /var/www/b/piwik/core/FrontController.php(589): call_user_func_array(Array, Array)
#15 /var/www/b/piwik/core/FrontController.php(165): Piwik\FrontController->doDispatch('TagManager', 'debug', Array)
#16 /var/www/b/piwik/plugins/TagManager/Context/WebContext/JavaScriptTagManagerLoader.php(72): Piwik\FrontController->dispatch('TagManager', 'debug')
#17 /var/www/b/piwik/plugins/TagManager/Context/WebContext.php(166): Piwik\Plugins\TagManager\Context\WebContext\JavaScriptTagManagerLoader->getPreviewJsContent()
#18 /var/www/b/piwik/plugins/TagManager/Context/WebContext.php(152): Piwik\Plugins\TagManager\Context\WebContext->addPreviewCode('/*!!\n * Matomo ...', true, true, Array)
#19 /var/www/b/piwik/plugins/TagManager/Model/Container.php(123): Piwik\Plugins\TagManager\Context\WebContext->generate(Array)
#20 /var/www/b/piwik/plugins/TagManager/TagManager.php(253): Piwik\Plugins\TagManager\Model\Container->generateContainer(97, 'DDLlW4wP')
#21 /var/www/b/piwik/core/Access.php(628): Piwik\Plugins\TagManager\TagManager->Piwik\Plugins\TagManager\{closure}()
#22 /var/www/b/piwik/core/Piwik.php(838): Piwik\Access::doAsSuperUser(Object(Closure))
#23 /var/www/b/piwik/plugins/TagManager/TagManager.php(261): Piwik\Piwik::doAsSuperUser(Object(Closure))
#24 [internal function]: Piwik\Plugins\TagManager\TagManager->regenerateReleasedContainers(Object(Piwik\CronArchive))
#25 /var/www/b/piwik/core/EventDispatcher.php(141): call_user_func_array(Array, Array)
#26 /var/www/b/piwik/core/Piwik.php(778): Piwik\EventDispatcher->postEvent('CronArchive.end', Array, false, Array)
#27 /var/www/b/piwik/core/CronArchive.php(555): Piwik\Piwik::postEvent('CronArchive.end', Array)
#28 /var/www/b/piwik/core/CronArchive.php(318): Piwik\CronArchive->end()
#29 /var/www/b/piwik/core/Access.php(628): Piwik\CronArchive->Piwik\{closure}()
#30 /var/www/b/piwik/core/CronArchive.php(319): Piwik\Access::doAsSuperUser(Object(Closure))
#31 /var/www/b/piwik/plugins/CoreConsole/Commands/CoreArchiver.php(27): Piwik\CronArchive->main()
#32 /var/www/b/piwik/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): Piwik\Plugins\CoreConsole\Commands\CoreArchiver->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 /var/www/b/piwik/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 /var/www/b/piwik/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Piwik\Plugins\CoreConsole\Commands\CoreArchiver), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 [internal function]: Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#36 /var/www/b/piwik/core/Console.php(98): call_user_func(Array, Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#37 /var/www/b/piwik/core/Access.php(628): Piwik\Console->Piwik\{closure}()
#38 /var/www/b/piwik/core/Console.php(99): Piwik\Access::doAsSuperUser(Object(Closure))
#39 /var/www/b/piwik/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Piwik\Console->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#40 /var/www/b/piwik/console(27): Symfony\Component\Console\Application->run()
#41 {main}
```

* Matomo version: 3.11.0
* OS: Debian Jessie 8.11
* PHP version: 7.2.20 (Debian packages provided by sury.org)
* MySQL version: MariaDB 10.3.8
* Additionally enabled plugins: LoginLdap (v4.0.7), MarketingCampaignsReporting (v3.1.1)

**Comment by tsteur** [comment] 2019-08-08 20:19
Hi there, this is a duplicate of https://github.com/matomo-org/plugin-LoginLdap/issues/190

**Closed by tsteur** 2019-08-08 20:19 UTC
