### ISSUE TITLE
comparison with previous year shows date in 2018, 2 years ago

### ISSUE THREAD

**Issue by ovidiucp** [matomo-org/matomo#15549] opened 2020-02-10 19:25 UTC
I’m trying to compare All Visits with the same day a year ago. I click the date at the top of the main page, choose “day” as Period, click to select the “Compare” option, and choose “Previous year”. When I click Apply, the dates being shown are the day I chose, but the same day 2 years earlier.

This is clearly a bug.

When I choose a custom period and enter the day a year earlier, I get the expected result.

**Comment by tsteur** [comment] 2020-02-10 20:04
Thanks for creating the issue and letting us know 👍

**Comment by sgiehl** [comment] 2020-02-17 13:04
actually a duplicate of #15193

**Closed by sgiehl** 2020-02-17 13:04 UTC
Labels: Bug, duplicate
