### ISSUE TITLE
today button in calendar user interface

### ISSUE THREAD

**Issue by tassoman** [matomo-org/matomo#15680] opened 2020-03-06 10:10 UTC
Today I'm so lazy I would like to suggest a "today" button to reset the calendar... 🤷‍♂️
We can file it as a _feature request_ with _low priority_ 😅

![Screenshot_2020-03-06 - 2020-03-06 - Web Analytics Reports - Matomo](https://user-images.githubusercontent.com/92727/76074047-fcda7900-5f9a-11ea-852a-2f5032561d7b.png)

**Comment by tassoman** [comment] 2020-03-06 10:15
Or maybe like this.. 

![Screenshot_2020-03-06 - 2020-03-06 - Web Analytics Reports - Matomo](https://user-images.githubusercontent.com/92727/76074553-d1a45980-5f9b-11ea-93d3-3ed9254d93d0.png)

**Comment by pebosi** [comment] 2020-03-06 13:00
Could easily be done, as UI Datepicker supports this with an option. Decision from core team :)

![datepicker-today](https://user-images.githubusercontent.com/445179/76085714-804f9680-5faa-11ea-80a4-1186c80d859e.png)

**Comment by tassoman** [comment] 2020-03-06 13:21
Today, this sounds lazier 🛋 🤣

**Comment by tsteur** [comment] 2020-03-07 02:46
Thanks for the suggestion. Very appreciated 👍   Be indeed useful to have. Marking it for now as a duplicate of https://github.com/matomo-org/matomo/issues/9094

**Closed by tsteur** 2020-03-07 02:46 UTC
