### ISSUE TITLE
segment filter: no results for "browser": IE AND "Browser version": 11

### ISSUE THREAD

**Issue by hpvd** [matomo-org/matomo#10067] opened 2016-04-18 13:57 UTC
There are no  results found/shown with segmentation:
 "browser": IE
AND
 "Browser version": 11

Even if there are hundrets visits visible without v11 filter...
same problem with other browser version numbers..

piwik 2.16.1

**Comment by tsteur** [comment] 2016-04-18 23:54
I can reproduce this on our second demo. @sgiehl do you maybe have an idea?

**Comment by hpvd** [comment] 2016-04-19 05:33
good to here.
As already mentioned here https://github.com/piwik/piwik/issues/5372#issuecomment-209902471
filtering by browser version is really important...

**Comment by hpvd** [comment] 2016-04-19 15:27
same in 2.16.2B1

**Comment by sgiehl** [comment] 2016-04-19 18:08
Filtering by browser + version does work. The problem is choosing an `equals` comparison does not work as expected at that point. The browser version is stored like `11.0`, `32.345.545.444` or similar. Which means an `11` won't match with `11.0`.  So you would need to compare with the exact version, or try something like `starts with` `11.` or `lower than` `12` and `at least` `11`.

**Comment by hpvd** [comment] 2016-04-19 18:52
Thanks for your details on this!
Well that's not easy no know...
1) When setting the mouse to the version number field there is a list of proposals with numbers without digits so one could easily choose a number it doesn't work with (please see attachment)
2) there is no format advice shown
3) uuuh how to select "lower than" and "at least"??? Would like that very much but thought it's not solved yet and part of https://github.com/piwik/piwik/issues/5372

![2016-04-19_20h40_34](https://cloud.githubusercontent.com/assets/5681880/14651529/760e6332-0670-11e6-8c87-2af610c4960d.png)

![2016-04-19_20h49_33](https://cloud.githubusercontent.com/assets/5681880/14651538/7dc17326-0670-11e6-9b2f-b85e89992003.png)

![2016-04-19_20h47_54](https://cloud.githubusercontent.com/assets/5681880/14651546/868672b8-0670-11e6-9222-0f101f625e59.png)

**Comment by hpvd** [comment] 2016-04-19 18:59
just imho:
"11" should filter all 11.xx versions and "11.1" should filter all 11.1x
if it's working in another way, there is a hint needed how it's working
and of course list of proposed values should only contain possible values / or should simply not be shown

**Comment by tsteur** [comment] 2016-04-19 20:28
That's definitely not intuitive. I did not know it either. Maybe it would be good to have a combo like "IE 11" similar to the report and then it gets split into 2 segments? It's likely not trivial to implement though. I wonder if we could show the segment `$acceptValues` help text at least as a title when hovering segment name, segment comparison and segment value. Any other ideas?

**Comment by sgiehl** [comment] 2016-04-25 21:49
We should definitely find a smarter solution for that. But imho, that is more a usability improvement as a "bug", as Piwik strictly applies the segment as defined.

We could indeed allow some kind of combined segment. But that wouldn't solve the comparison problem. Theoretically the browser version could contain anything. For most cases that will be a version number but it might be a text in some cases. aswell.
As long as Piwik will keep tracking minor versions (e.g. X.Y) only and no patch versions (e.g. X.Y.Z) the comparison might be easy to solve, as we can compare the versions as numbers.

But I'm still unsure how we should compare the versions. Should a `11`really match a `11.133`, aswell? That would make it impossible to match exactly `11` and no others.

Btw. the list of possible versions shown is correct, but it shows all tracked versions tracked for any browser. So the `11` might match for another browser than `IE`. Switching to a combined segment would maybe allow to show only available browser/version combinations.

**Comment by tsteur** [comment] 2016-04-25 22:05
I guess we likely need two segments like "Browser exact version" and "Browser major version". Maybe we could on top offer at some point a segment like "IE 11.*".

Otherwise in the autocomplete we could maybe show "11", "11.133" but also "11.*" and when ".*" is selected we convert it to basically "11.% or 11" and match all versions. However, I reckon ".*" might be only understood by more technical people. I presume having two different segments could be useful.

**Comment by hpvd** [comment] 2016-04-26 05:04
Maybe one can also think of a solution where there is only an additional check mark:
"not exact" / "globalize" or similar, which allows to find all subversions:
- "11" => 11.x.x.x.x
- "11.1" => 11.1.x.x.x
- ...
if check mark is not set it works like it's actually working
11 => 11.0.0.0.

![2016-04-26_07h01_28](https://cloud.githubusercontent.com/assets/5681880/14807458/16f0345e-0b7d-11e6-8fc8-6101e9f93293.png)


regarding suggestions, this could be helpful also in general (not only for browsers)
one could think of always applying the combined conditions setup before the the suggest appears:
Suggest for browser AND Browser Version => suggest for browser version shows only the ones fitting to selected browser before
only check:
the other way around:
AND Browser Version AND Suggest for browser :
Suggestion for browser version should show all versions ever tracked
Suggestion for browser should only show the browsers having the browser version selected before...

**Comment by hpvd** [comment] 2016-04-26 05:53
the "not exact" would also make sense for other segment filters like e.g.
- operating system version
- latitude
- longitude
- ...

**Comment by hpvd** [comment] 2016-04-26 05:58
just another aproach:
couldn't we simply adopt the existing "starts with" condition also for numbers?

**Comment by hpvd** [comment] 2016-04-26 06:01
when choosing this way, one could also find combined data like browser versions like:
"43.4 beta"
when filtering "browser version" "starting with" "43"

**Comment by hpvd** [comment] 2016-04-26 06:59
hmmm...adopting "starting with" does not work perfect, because than one can't choose "greater than", "less than" anymore (see https://github.com/piwik/piwik/issues/5372)

the solution with a checkmark for "not exact" should work any way....

**Comment by mattab** [comment] 2023-12-12 04:53
Thanks for contributing to this issue. As it has been a few months since the last activity and we believe this is likely not an issue anymore, we will now close this. If that's not the case, please do feel free to either reopen this issue or [open a new one](https://developer.matomo.org/guides/core-team-workflow#submitting-a-bug-report). We will gladly take a look again!

**Closed by mattab** 2023-12-12 04:53 UTC
Labels: c: Usability
