### ISSUE TITLE
the page view time is not correct for some case and not coming for few cases

### ISSUE THREAD

**Issue by psudeep** [matomo-org/matomo#16575] opened 2020-10-14 19:20 UTC
I have implemented a self hosted matomo and try to track time spent on an article but sometimes the time is not correct and a few no time is being tracked.

How do I fix this?
Is there any solutions. on Google analytics I am able to do it.

**Comment by tsteur** [comment] 2020-10-14 19:59
Hi @psudeep Are you maybe referring to the last page view within a visit? In this case this issue would be a duplicate of https://github.com/matomo-org/matomo/issues/9748

**Closed** 2023-12-10 13:43 UTC
