### ISSUE TITLE
Cannot remove GoogleAnalyticImporter plugin download error notification

### ISSUE THREAD

**Issue by chibiapp** [matomo-org/matomo#15498] opened 2020-02-01 10:57 UTC
On dashboard there is following notification message:

Failed to download plugin from https://plugins.matomo.org/api/2.0/plugins/GoogleAnalyticsImporter/download/1.2.2?coreVersion=3.13.0: curl_exec: Operation timed out after 60000 milliseconds with 3128825 bytes received. Hostname requested was: plugins.matomo.org

Already dismissed the message, but when I refresh the page, it re-appear

Tried to totally remove/uninstall the plugin (GoogleAnalyticsImporter), but the error notification is still persisted

**Comment by bazzadp** [comment] 2020-09-02 19:43
As noted in #15575 clearing cookies to end the session removes the error message finally!

**Comment by tsteur** [comment] 2020-09-02 19:52
Thanks @bazzadp closing this as a duplicate of https://github.com/matomo-org/matomo/issues/15575

**Closed by tsteur** 2020-09-02 19:52 UTC
Labels: Bug
