### ISSUE TITLE
After logout also user can access site using authentication token

### ISSUE THREAD

**Issue by mahesh978** [matomo-org/matomo#12604] opened 2018-03-07 13:03 UTC
we configured piwik on wamp server. but we are facing issue regarding the token. we are using burp tool for testing purpose when user logout from piwik. if he again visit the same page he can access all the details.
can we have solution to hide or remove auth_token from piwik.

**Comment by tsteur** [comment] 2018-03-07 18:14
I am not quite sure what you mean. Do you log in the user? The regular way? The token_auth is like a combination of username and password and using this it is possible to access data. Every user has a token_auth which is currently expected. Did you mean you want to hide or remove the token_auth from the Piwik UI in the personal settings? This is currently not really possible yet as the token would be possibly still visible in the source of the website (eg right click View Page Source). We will eventually remove it from the source of the site to improve security even further, then it would make sense to also add a feature to not show the token to the user in the UI 👍 
There are some other work arounds though maybe. For example every time the user logs out, you could create a new token_auth. In case the user is not logged in, you could even do this for example one hour after the last action or something. 

Apart from this I'm not quite sure why the user is not supposed to be able to access data with the token when the user can also just log in anyway?

**Comment by mahesh978** [comment] 2018-03-08 05:43
thanks @tsteur for your reply.
my question is simple when we Login to piwik. one piwik_auth cookie is getting generated which is same for a user. with the cookie after logout also user can visit the same page without using Login credentials and he can do all operations.
we tested with burp tool i attached image of the tool after logout.
![Burp tool Image](https://user-images.githubusercontent.com/32063001/37134938-d3973240-22c0-11e8-8d8e-53ec2ddbd71a.PNG)
left hand side we can see all the cookies and right hand side the html for the page so directly we can browse the page. as security is main concern for us.
is there any way to hide Authentication token as i'm new to piwik so i don't know complete features.

**Comment by fdellwing** [comment] 2018-03-08 09:11
As @tsteur mentioned, this is working as intended. The token_auth is an alternative way to login into Matomo and should be threated with the same care as the password.

**Comment by mahesh978** [comment] 2018-03-08 10:32
yes but i don't think it is the proper way for some secured sites as anyone having access to the browser can get Auth_token without sharing. and with a get request we will directly get an Auth_token.

**Comment by tsteur** [comment] 2018-03-08 18:15
Now I know what you mean @mahesh978 . Check out https://github.com/matomo-org/matomo/pull/12208 👍 I'll close this now as answered but feel free to reopen or comment on that issue.

**Closed by tsteur** 2018-03-08 18:15 UTC
