### ISSUE TITLE
3.8.1 to 3.9 upgrade error when upgrading from UI

### ISSUE THREAD

**Issue by jordo1138** [matomo-org/matomo#14242] opened 2019-03-20 00:20 UTC
Error after upgrading via browser
<img width="1330" alt="Screen Shot 2019-03-19 at 5 16 38 PM" src="https://user-images.githubusercontent.com/8525512/54650309-238e5f80-4a6b-11e9-87c0-7ef38284b1a3.png">

Manually refresh the same url, and get to 
<img width="1022" alt="Screen Shot 2019-03-19 at 5 15 40 PM" src="https://user-images.githubusercontent.com/8525512/54650339-3dc83d80-4a6b-11e9-852e-833186b3b06a.png">

Seems normal now, but just a note on the weird upgrade screen errors. Not sure if anything else has an issue now or not yet.

**Comment by AramVK** [comment] 2019-03-20 00:42
Had the same thing going on.

**Comment by peterkraume** [comment] 2019-03-20 05:30
Same problem here. I'll post the error message again for search engines to better find it:
`Matomo encountered an error: Call to undefined method Piwik\Plugin\Manager::getPluginDirectory() (which lead to: Circular dependency detected while trying to resolve entry 'Piwik\Twig')`

**Comment by JepKoha** [comment] 2019-03-20 05:35
I Had also the same issue as updating from browser on 2 Matomo instances

https://MY-MATOMO-URL/index.php?module=CoreUpdater&action=oneClickUpdate
Matomo encountered an error: Call to undefined method Piwik\Plugin\Manager::getPluginDirectory() (which lead to: Circular dependency detected while trying to resolve entry 'Piwik\Twig')

Matomo: 3.9.0
MySQL: 5.1.73
PHP: 7.0.31

However everything seem ok after refreshing index page...

**Comment by fdellwing** [comment] 2019-03-20 07:53
Duplicate of #14227

**Closed** 2019-03-20 08:37 UTC
Labels: duplicate
