### ISSUE TITLE
Login problems with IE11 (Matomo

### ISSUE THREAD

**Issue by mockey** [matomo-org/matomo#15661] opened 2020-03-04 13:41 UTC
Matomo version: 3.13.3 
After the login from IE11 the page shows the top menu and the sidebar but instead of a report there is an error message saying that the session has expired.
Could this be because of the use of `SameSite: Lax` for the cookie?

**Comment by sgiehl** [comment] 2020-03-04 14:04
might be possible. IE 11 only has partial support in later releases 🤔

**Comment by mockey** [comment] 2020-03-04 14:32
Whatever that means exactly. Unfortunately we have customers still using it...
The problem seems to the ajax call(s) that get the reports.

**Comment by sgiehl** [comment] 2020-03-04 15:48
Nevermind. Are you using Windows 10 with latest IE 11 or an older Windows?

**Comment by sgiehl** [comment] 2020-03-04 17:15
I'm able to reproduce that locally. It's definitely caused by the samesite. If I remove setting samesite from the cookie the login works again...

**Comment by sgiehl** [comment] 2020-03-04 18:05
Did some more testing on that. Seems not to be caused by the samesite option. Seems to be caused by the invalid session expire as well. And should already be fixed with #15633

**Closed by sgiehl** 2020-03-04 18:05 UTC
Labels: Regression

**Comment by mockey** [comment] 2020-03-17 19:17
Thanks. I'll test this with 3.x-dev branch tomorrow.
