### ISSUE TITLE
MATOMO_SESSID expires directive with wrong format

### ISSUE THREAD

**Issue by matzesa** [matomo-org/matomo#15625] opened 2020-02-26 09:55 UTC
After logging in the MATOMO_SESSID Cookie is changed via the http header set-cookie and an expires directive is added. But the format of the value is unixtime instead of date (https://tools.ietf.org/html/rfc6265#section-4.1)

Example (Version 3.13.3):
```
Set-Cookie: MATOMO_SESSID=380lf4cjmaenc605u73dgklnq9; expires=1583920346; path=/; secure; httponly; SameSite=Lax
```

Found the following code line, perhaps it helps, but did not inspect deeper:
https://github.com/matomo-org/matomo/blob/35467f54cd3e1dae889d88ae4f80d4626f9127ed/core/Session.php#L210

Here it seems to be converted:
https://github.com/matomo-org/matomo/blob/35467f54cd3e1dae889d88ae4f80d4626f9127ed/core/Cookie.php#L155

**Comment by tsteur** [comment] 2020-02-26 20:02
Thanks @matzesa very appreciated.

**Comment by dev-101** [comment] 2020-02-26 20:08
Is this the cause of Matomo session lasting for few hours only? Ever since upgrading to the latest version 3.13.3 on one site, I always get login screen, even with remember me option checked. What have you done wrong this time? :)

**Comment by Findus23** [comment] 2020-02-27 13:19
Same is reported in https://forum.matomo.org/t/remember-me-not-working-since-update/36233

**Comment by adegans** [comment] 2020-02-27 17:37
For me to 'remember me' doesn't work either.
But, it's not so much the checkbox as the session that's broken I think.

I tried logging out and then back in to sort of set a new login hash/id/thing - In case an old session or whatever was lingering around.
But as soon as I close the tab and load Matomo again I have to log in again.
So probably a session/cookie issue.
Worked fine in 3.13.2 (or whatever the version before was)

**Comment by benkuper** [comment] 2020-02-27 20:16
Same here, is there a workaround that we can do in the meantime ?

**Comment by Findus23** [comment] 2020-02-28 16:07
@benkuper 
You can in the meantime try to apply this change from #15633 and report back if it works for you:

```diff
diff --git a/core/Session.php b/core/Session.php
index f2f984d357e..dd5b1229d70 100644
--- a/core/Session.php
+++ b/core/Session.php
@@ -222,7 +222,7 @@ public static function writeCookie($name, $value, $expires = 0, $path = '/', $do
     {
         $headerStr = 'Set-Cookie: ' . rawurlencode($name) . '=' . rawurlencode($value);
         if ($expires) {
-            $headerStr .= '; expires=' . $expires;
+            $headerStr .= '; expires=' . gmdate('D, d-M-Y H:i:s', $expires) . ' GMT';
         }
         if ($path) {
             $headerStr .= '; path=' . $path;

**Comment by benkuper** [comment] 2020-02-28 23:23
Thanks @Findus23 , it seems to do the job !
I have just tested by closing the browser and going back, but at least this works. This should definitely be integrated in next version :)

**Closed** 2020-03-02 20:24 UTC
Labels: Bug, Regression

**Comment by cbeams** [comment] 2021-02-01 12:34
I am running Matomo v4.1.1 and still seeing the old, erroneous epoch time expiration values in the cookie. If I understand this issue and the linked PR correctly, this problem got fixed and integrated back in the 3.x line. How could it be that I'm still seeing this behavior? Anyone else still having the problem?

**Comment by dev-101** [comment] 2021-02-01 12:44
Have you tried to sign-out and sign-in? This step was required to complete the fix iirc. But, I guess you already tried that. So far, no issues here since the original fix.

**Comment by cbeams** [comment] 2021-02-01 12:53
Sorry, I just realized that I am in fact seeing the proper date string, not the old unix time string, and I even see that the date is updated on every refresh within the same session. Currently the expiry time reads "2021-07-31T10:10:33.600Z", but regardless, I still get logged out. Not sure what the problem could be. I've tried logging out, etc. It's as if the cookie just isn't being read / respected.

**Comment by dev-101** [comment] 2021-02-01 13:12
Maybe session file on your server gets removed for some reason. Don't know what could be the problem.

**Comment by cbeams** [comment] 2021-02-01 13:12
False alarm. I've played with this further, and now everything is working as expected. I don't know exactly what made the difference, but perhaps I hadn't fully / properly tested by logging out, quitting the browser and restarting before. All good now.

**Comment by nebulade** [comment] 2021-02-03 13:26
To get some better picture, I am facing the same issue and upon some investigation, I've seen that it our instance never stores session files on the disk, but rather appears to have a `session` table in the database.  What is the connection between that table and the login session or are these some other kind of sessions?

**Comment by sgiehl** [comment] 2021-02-03 13:32
@nebulade Matomo switched to using database sessions instead of files a while ago. So the table should hold all login sessions.

**Comment by nebulade** [comment] 2021-02-03 13:56
Thanks for the clarification @sgiehl !
