### ISSUE TITLE
Segment "Country starts with United" doesn't match visits from "united states" 

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#16307] opened 2020-08-17 10:42 UTC
Bug: creating a new segment "Country starts with United", doesn't match "United states". 

Expected instead it would match visits from the US.

**Comment by sgiehl** [comment] 2020-08-17 12:28
I guess that might be a more generic problem for segments using `setSqlFilterValue` to transform the values.
If a value is provided that isn't included in the list it won't include anything useful I guess.
Might be better to disable any compare that does not match an exact value for those segments maybe.

Otherwise we might need to handle such stuff in a complete other way. E.g. we would need to go through the list of possible values and match them against the segment. The matching ones then would need to be transferred to their SQL value and combined into the sql query according the match type.

**Comment by tsteur** [comment] 2020-08-17 19:55
We'll eventually  add a possibility to only show certain segment comparisons for certain types of dimensions. Eg for boolean dimensions only equals and not equals may be offered etc. So depending what comparisons a segment supports different comparisons will be shown.

**Comment by KarthikRaja1388** [comment] 2020-08-19 23:06
United States is not available in the suggestion at all, even though visitors are tracked from United states.

**Comment by tsteur** [comment] 2020-08-19 23:33
@KarthikRaja1388 what you describe is a duplicate of https://github.com/matomo-org/matomo/issues/15620

**Closed** 2020-11-23 03:13 UTC
Labels: Bug
