### ISSUE TITLE
When event (name, action or category) segment is applied, there is no data in some actions report, Inform users why 

### ISSUE THREAD

**Issue by adaqus** [matomo-org/matomo#9796] opened 2016-02-17 13:50 UTC
Let's create segment based on event name:

`eventName==some name`

When browsing 'Actions' reports for this segment, only reports in Actions / Events show some data. Others actions reports show message 'There is no data for this report.' and users think this is an error.

Users should be informed somehow that this is not error and it is logical consequence of using segment based on events.

This is also the case for any segment based on actions or events.

**Comment by tsteur** [comment] 2016-02-18 07:07
Good point :+1: Won't be easy though as depending on segment some reports may still show some data while others not.

**Comment by Aeyoun** [comment] 2016-09-01 00:27
As a new user, I’m really curios about the explanation for this. This limitation makes no sense to me; ff course I’d like to see which URLs are popular among users who triggered the `leftComment` event. Not being able to do this should be considered a bug (possibly a larger architectural problem) and not just a user error.

**Comment by mattab** [comment] 2016-09-27 03:59
> Not being able to do this should be considered a bug (possibly a larger architectural problem) and not just a user error.

Fair enough, marking as `Bug` and moving up the priority list. Although it does not mean we will investigate soon soon as there are so many other issues to deal with. Help is very welcome (but this issue will be quite complex so may not be the best place to help!)

**Comment by mattab** [comment] 2016-09-27 04:00
@Aeyoun maybe you could link to the few forum posts where this was discussed? this could help increase "perceived priority" on our end

**Comment by Aeyoun** [comment] 2016-09-28 00:46
Here is a rough unfiltered list. The first 20 results were all this very issue (didn’t bother clicking through the 100 remaining threads), but your personal Google rankings may yield different results.
https://www.google.com/search?q=site%3Aforum.piwik.org%20event%20action

**Comment by hpvd** [comment] 2017-09-15 06:07
I think this is related to
show instant feedback on period & segment selector usage (result counting) #9109

in the case of no data one simply see something like this:

"**0 different visits counted within selected period and segment.
These are 0% of all visits on entire website within this period**"

**Comment by mattab** [comment] 2019-08-12 01:48
Duplicate of #11900 which we're planning to implement in Matomo 4 if all goes as planned.

**Closed by mattab** 2019-08-12 01:48 UTC
Labels: Bug, Major, c: Usability

**Comment by mattab** [comment] 2019-10-27 20:32
This should be fixed in Matomo 3.12.0 which will be released tomorrow - if you still experience this issue then, let us know.
