### ISSUE TITLE
Segments to exclude a URL are still shown in the visits log.

### ISSUE THREAD

**Issue by jmumby** [matomo-org/matomo#15708] opened 2020-03-18 23:46 UTC
When creating a segment to exclude a particular string. Results are still shown in the visits log. 

![image](https://user-images.githubusercontent.com/4339071/77017490-851b3e00-69df-11ea-8d41-b105a519c93e.png)

**Comment by tsteur** [comment] 2020-03-19 02:39
I suppose technically the user visited a page that did not include that string, and therefore this result be actually expected from what is currently implemented.

**Comment by mattab** [comment] 2020-03-19 04:54
@tsteur a few people have reported this and finding it not clear/not what they expect.

 If we wanted to change the implementation of "Does not contain" for actions, would that be possible and how much effort would it be?

**Comment by tsteur** [comment] 2020-03-19 05:26
@mattab I don't know if it's possible. Would estimate a few days since it requires rewriting a lot of deep core logic in join tables generator, segment query generator, etc and ensuring nothing breaks etc. Also if it works, it would potentially mean performance implications to already slow action queries (especially when it comes to contains). Is this a duplicate of https://github.com/matomo-org/matomo/issues/13785 ?

**Comment by mattab** [comment] 2020-03-19 21:13
Marking as duplicate of https://github.com/matomo-org/matomo/issues/13785

**Closed by mattab** 2020-03-19 21:13 UTC
Labels: Enhancement
