### ISSUE TITLE
Issues displaying actions under a visit in segmented Visitor profile

### ISSUE THREAD

**Issue by KarthikRaja1388** [matomo-org/matomo#15099] opened 2019-11-04 03:59 UTC
Issue: Actions under a visit in segmented visitor log is not getting displayed, even though the number of actions can be seen

Steps to reproduce:

1. Click on "Visitors > Visits Log"
2. Click on "View Visitor Profile"
3. Scroll down and click on "Load more Visits"
4. Click on the number of actions on the right

Please find the screenshot attached:
![image](https://user-images.githubusercontent.com/26726594/68098921-60d52e00-ff24-11e9-926b-a596f0eb7a6a.png)

**Comment by sgiehl** [comment] 2019-11-04 09:54
@KarthikRaja1388 I guess you are using a segment that is based on a action (like action url, title, ...)?

**Comment by KarthikRaja1388** [comment] 2019-11-04 21:38
@sgiehl May be the title was misleading, I have just updated it. I haven't applied any segment manually, this actually happens when clicking 
![image](https://user-images.githubusercontent.com/26726594/68160183-143b3280-ffb8-11e9-9bdb-6f1b1d42db80.png) in each visit to view the visits for a particular visitor profile.

**Comment by tsteur** [comment] 2019-11-04 21:59
@KarthikRaja1388 I can't reproduce it. Be good to let us know step by step how to reproduce this

**Comment by KarthikRaja1388** [comment] 2019-11-04 23:14
@tsteur steps are mentioned above. Pasting again:

Steps to reproduce:
  1.  Click on "Visitors > Visits Log"
  2.  Click on "View Visitor Profile"
  3.  Scroll down and click on "Load more Visits"
  4.  Click on the number of actions on the right

No actions will be found under the log (pageview, reload etc.)

**Comment by mattab** [comment] 2020-01-21 04:47
Can you reproduce this on the demo @KarthikRaja1388 and share the URL?

**Comment by KarthikRaja1388** [comment] 2020-01-21 21:54
@mattab https://demo.matomo.org/index.php?module=CoreHome&action=index&idSite=62&period=day&date=yesterday#?idSite=62&period=day&date=yesterday&segment=&category=General_Visitors&subcategory=Live_VisitorLog&popover=visitorProfile$3A364a349ac52e0807

Click on Load more after loading this page

**Comment by mattab** [comment] 2020-08-20 01:27
@KarthikRaja1388 can you still reproduce it? it looks like it's been fixed in the meantime

**Comment by tsteur** [comment] 2021-07-22 23:17
Looks like it works for me. If someone is still experiencing this issue please let us know. Ideally with steps to reproduce or a link to our demo where this happens (https://demo.matomo.cloud)

**Closed by tsteur** 2021-07-22 23:17 UTC
Labels: Bug
