### ISSUE TITLE
Real-Time Map | Overlay close doesn't close properly

### ISSUE THREAD

**Issue by CookieMonsterNL** [matomo-org/matomo#15411] opened 2020-01-17 14:33 UTC
**Background**
When visiting Visitors > Real-Time Map and clicking on one of the locations, a pop-up opens (see screenshot attached).

**Challenge**
You can close the overlay by clicking on the map, or clicking on the 'X' (top-right) ro close. The 'X' button doesn't work (no response at all).

*Setup*
- Using the latest Matomo for WP
- On my Chrome Browser (Version 79.0.3945.130 - 64-bit)
- Windows 10 laptop

![1-Real-Time Map pop-up](https://user-images.githubusercontent.com/60006242/72619896-90e67780-393e-11ea-8d22-e109679394b3.PNG)

**Comment by Findus23** [comment] 2020-01-17 15:18
I can reproduce this on demo.matomo.org in Firefox (no error in the console).

**Comment by Findus23** [comment] 2020-01-17 15:27
I didn't see that this is a duplicate of #15404

**Closed by Findus23** 2020-01-17 15:27 UTC
Labels: Regression
