### ISSUE TITLE
open_basedir restriction AND Support multiple plugin paths

### ISSUE THREAD

**Issue by prolibre** [matomo-org/matomo#14226] opened 2019-03-19 08:34 UTC
I have an error since the last update (3.9.0)

> WARNING: /**INSTALL_DIR**/core/Plugin/Manager.php(451): Warning - is_dir(): open_basedir restriction in effect. File(/**INSTALL_DIR**plugins/Annotations) is not within the allowed path(s): (/**INSTALL_DIR**/) - Matomo 3.9.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already)

Because there's a mistake in the path : **/INSTALL_DIRplugins/Annotations** (it's missing one /)

_$corePluginsDir = PIWIK_INCLUDE_PATH . 'plugins/' . $pluginName;_
should perhaps be replaced by:
_$corePluginsDir = PIWIK_INCLUDE_PATH . '/plugins/' . $pluginName;_

Thank you for your work / Merci beaucoup

Anthony

**Comment by conrad784** [comment] 2019-03-19 08:39
I can confirm this bug, this is an issue with my installation too.

**Comment by mattab** [comment] 2019-03-19 09:03
Thanks for the report @prolibre 
@conrad784 just to confirm, do you mean that the patch here solves the bug for you?

**Comment by prolibre** [comment] 2019-03-19 09:08
Hello @mattab 
```
- $corePluginsDir = PIWIK_INCLUDE_PATH . 'plugins/' . $pluginName;
+ $corePluginsDir = PIWIK_INCLUDE_PATH . '/plugins/' . $pluginName;
```
works for me yes

**Comment by Findus23** [comment] 2019-03-19 09:10
Comparing it with other places in https://github.com/matomo-org/matomo/search?q=PIWIK_INCLUDE_PATH&unscoped_q=PIWIK_INCLUDE_PATH it makes sense as they also have a leading `/`

**Comment by conrad784** [comment] 2019-03-19 09:12
@mattab changing
```
- $corePluginsDir = PIWIK_INCLUDE_PATH . 'plugins/' . $pluginName;
+ $corePluginsDir = PIWIK_INCLUDE_PATH . '/plugins/' . $pluginName;
```
 in 'core/Plugin/Manager.php' works for me

the update gave me the same error message as reported in #14227

**Comment by sgiehl** [comment] 2019-03-19 09:13
the `/` is missing indeed. Otherwise the `if` always returns false (if open_basedir is not a problem). I'll create a PR for it

**Comment by RedJohn14** [comment] 2019-03-20 07:43
I have the same problem here.

`- $corePluginsDir = PIWIK_INCLUDE_PATH . 'plugins/' . $pluginName;
+ $corePluginsDir = PIWIK_INCLUDE_PATH . '/plugins/' . $pluginName;`

will it fixed in next version?

**Comment by sgiehl** [comment] 2019-03-20 09:38
@RedJohn14 yes. it will be fixed

**Closed** 2019-03-20 09:39 UTC
Labels: Bug
