### ISSUE TITLE
Propose including unlink into upgrade process

### ISSUE THREAD

**Issue by fdellwing** [matomo-org/matomo#14249] opened 2019-03-20 19:53 UTC
Currently files that are no longer needed after an update will be shown in integrety report to be deleted by the user. This does confuse some people and I do understand that feeling. I also think after an update there should be no unwated files in my install folder that I did not put there myself.

I propose that with the following version the update process unlinks all files that are deleted from one to another version. With 3.8.1 -> 3.9.0 this would have been:
```
plugins/Referrers/Widgets/GetKeywordsForPage.php
vendor/JShrink/
```
Probably this would also need a new helper function as PHP is not able to delete folders with content, so we have to unlink everything recursivly and finally call rmdir on the folder.

**Comment by Findus23** [comment] 2019-03-20 20:00
Duplicate of #11132 :slightly_smiling_face: 

Doing this automatically sounds like something where a lot of things can go dangerously wrong.

So at most I'd go with a button that deletes all files listed above.

**Closed by Findus23** 2019-03-20 20:00 UTC

**Comment by fdellwing** [comment] 2019-03-20 20:06
I don't see a big risk for much going wrong as I would not integrate this into the integrety report but write it by hand in the `core/Updates/xxx.php`. Will continue in orginal issue.
