### ISSUE TITLE
Not able to access site with cors-proxy-ite

### ISSUE THREAD

**Issue by JeffS25** [matomo-org/matomo#13234] opened 2018-07-31 15:03 UTC
Hi,

I'm not able to access site with cors, it's giving me internal server error. Please find attached screenshot.
Could you please help me with issue?

http://cors-proxy-ite.abc.com/?feed=http://piwik-test.abc.com/piwik/index.php?module=API&method=Actions.getPageUrl&pageUrl=/sites/TestCreate9th.aspx&idSite=3&period=day&date=today&format=json 

Thanks

![image](https://user-images.githubusercontent.com/40857207/43468084-be26dd0e-9500-11e8-9720-b25e041e0cbf.png)

**Comment by mattab** [comment] 2019-06-18 22:54
Thanks for the report. It sounds like there is an error on the Matomo server and that the PHP process is failing with an error. Could you check your Web server error.log for the actual error message(s) logged by the server? Once we see the error messages we will likely be able to understand where the problem is from. Looking forward to investigating further.

**Comment by sgiehl** [comment] 2023-10-09 22:57
Closing as there hadn't been any further feedback.

**Closed by sgiehl** 2023-10-09 22:57 UTC
Labels: Bug, Waiting for user feedback
