### ISSUE TITLE
Make sure users with an older PHP can't upgrade to Matomo 4

### ISSUE THREAD

**Issue by nmstoker** [matomo-org/matomo#11068] opened 2016-12-22 12:23 UTC
I logged in to the Piwik interface and saw the small message flagged up in the top right saying I should upgrade my 2.17 installation to 2.17.1.  (I'm on PHP 5.4 so cannot go to 3.0.0 until the point at which we're able to move the installation to PHP 5.5+)

I clicked on teh message and then the automatic upgrade button (which has worked perfectly in the past) and then almost immediately got a message about an error due to the PHP version (see screenshot)
![image](https://cloud.githubusercontent.com/assets/3694484/21425446/0ca6e480-c841-11e6-8dba-3d20b954aa59.png)

After digging into the files on the server, I discovered that the update has taken me to 3.0.0.  Somehow it has been able to proceed with this bypassing the checks that it did previously and now leaving an unworkable system (until we can upgrade PHP).

I doubt many people will end up in this scenario, but it would be good to check that the version checking process works for any future cases where a higher specific version of PHP (or something else) is required and not necessarily available.

**Comment by tsteur** [comment] 2016-12-22 18:08
That's no good, sorry for that. Can you check what it says in "config/config.ini.php" for "release_channel = ..."? You may be able to downgrade manually see https://piwik.org/docs/update/#the-manual-three-step-update  You can download 2.17.1 here http://builds.piwik.org/piwik-2.17.1.zip

**Comment by nmstoker** [comment] 2016-12-23 12:20
Hi Thomas,

Thanks for getting back to me.  The config/config.ini.php file doesn't have any mention of "release_channel" at all, but seeing that the values there were able to override those in global.ini.php I checked in there and found it says this:

release_channel = "latest_stable"

![image](https://cloud.githubusercontent.com/assets/3694484/21453649/222dd7e6-c909-11e6-81e1-a6ead23c32d8.png)

I'm not going to have much of a chance to check details after today for about a week, so I'll need to leave it for now, but I'll gladly check anything useful later on.  Given the somewhat restricted nature of my access on the installation, I think my best option is likely to be to prioritise the PHP upgrade if possible and push on rather than try rolling back.

**Comment by mattab** [comment] 2016-12-26 04:47
to keep the code easier to understand, maybe we should remove the release_channel from the config file @tsteur ? maybe some code path is triggered using the config value instead of the recorded UI setting..

**Comment by tsteur** [comment] 2016-12-27 01:16
I think it is only in the config but I haven't looked at the code.

**Comment by tsteur** [comment] 2016-12-27 01:17
Just because it is a UI setting doesn't mean it is stored in the DB just FYI

**Comment by lhilarides** [comment] 2017-01-30 22:15
Just FYI: I ran into the exact same issue last week. Piwik asking me to upgrade to 2.17.1 and ending up with an unusable 3.0 install because it's still running on Ubuntu 12.04 and PHP 5.4. Our stats are not exactly mission critical, so for us the upgrade path (planned move to Debian 8) will be the solution

**Comment by mattab** [comment] 2017-02-18 12:08
We will need to solve this problem so it does not occur again in our next major release. Assigning to Piwik 4

**Comment by tsteur** [comment] 2020-04-15 02:57
BTW I cannot reproduce this issue no matter the release channel. @mattab quite certain this issue can be closed. Eg used hard coded values to see what version it suggests

![image](https://user-images.githubusercontent.com/273120/79294047-53878b00-7f29-11ea-852d-0e9964d99425.png)

**Comment by tsteur** [comment] 2020-04-15 03:03
Created the referenced PR though for the API...

**Closed** 2020-06-19 19:52 UTC
Labels: Bug
