### ISSUE TITLE
don't show error if loading a page has been aborted

### ISSUE THREAD

**Issue by Findus23** [matomo-org/matomo#14341] opened 2019-04-11 19:11 UTC
When opening a page in Matomo that loads widgets and navigating to the next page before the widgets have finished loading, the widget aborts loading and instead shows the error message until the next page has loaded.

With the error messages beeing brighter since the last redesign this is more annoying than before. 

![grafik](https://user-images.githubusercontent.com/6266037/55984398-a5099400-5c9d-11e9-9782-b0214212c6d5.png)

**Comment by tsteur** [comment] 2019-04-11 20:12
Feel free to reopen but I think this is a duplicate of https://github.com/matomo-org/matomo/issues/10578

**Closed by tsteur** 2019-04-11 20:12 UTC
Labels: c: Design / UI
