### ISSUE TITLE
Missing option to disable fingerprinting

### ISSUE THREAD

**Issue by Peython** [matomo-org/matomo#15156] opened 2019-11-13 17:23 UTC
Hi there Matomo team.

Here in Germany, there are privacy concerns even if anonymization of IP addresses are activated, because of fingerprinting users. Many lawyers give advise to not include Matomo on the web pages, at least not before user consent with an opt-in. Regardless, how the fingerprints are generated or salted or any of that.

That's not ideal for many and our cases. We'd like to be both absolutely sure, that our tracking tools are GDPR compliant, but we also like to track all visitors before consent via opt-out. As long as there is any kind of law-grey-area, we can't really use Matomo before consent, but then we'll lose a lot of basic traffic data, which our clients are kinda mad about.

Is there a chance to get something like that as an option in a future release?

Thanks. :-)

**Comment by mattab** [comment] 2020-01-20 22:33
Hello. thanks for the suggestion, marking as duplicate of https://github.com/matomo-org/matomo/issues/13655

**Closed by mattab** 2020-01-20 22:33 UTC
