### ISSUE TITLE
For mobile app measurables, rename "Page Titles" => "Screens" and hide page reports

### ISSUE THREAD

**Issue by diosmosis** [matomo-org/matomo#15375] opened 2020-01-10 08:33 UTC
Mobile apps don't generally have URLs so we can only really report by page title. When a mobile app measurable is being viewed, we should change the view to make more sense to the user.

If page reports do for some reason have data, we can show them, maybe as "Screen URL".

**Comment by tsteur** [comment] 2020-01-11 02:47
@diosmosis can maybe close this as duplicate of https://github.com/matomo-org/matomo/issues/7823 ?

refs https://github.com/matomo-org/matomo/issues/7826

**Closed** 2020-01-11 02:49 UTC
Labels: duplicate
