### ISSUE TITLE
Update davaxi/sparkline composer dependency

### ISSUE THREAD

**Issue by creativecoder** [matomo-org/matomo#15458] opened 2020-01-26 18:09 UTC
Currently `davaxi/sparkline` is set to the version `dev-multiple-series` in `composer.json`

https://github.com/matomo-org/matomo/blob/5322d058d5afcd2c40e76a13762038e05f0795f3/composer.json#L51)

This results in the following error when running `composer require piwik/piwik`

```
Problem 1
    - piwik/piwik 3.13.1 requires davaxi/sparkline dev-multiple-series -> no matching package found.
```

I believe `davaxi/sparkline` should instead be set to `~1.2`, to install the [latest release](https://github.com/davaxi/Sparkline/releases/tag/1.2.0) that includes the changes merged to support [displaying multiple series](https://github.com/davaxi/Sparkline/pull/11).

**Comment by tsteur** [comment] 2020-01-27 00:32
@Findus23 @sgiehl do you maybe know more?

**Comment by Findus23** [comment] 2020-01-27 11:20
@diosmosis should know best about it but I have no idea why this fails. While we should now be using the latest upstream (#15465), the branch still exists and should therefore work in composer (https://github.com/matomo-org/Sparkline/tree/multiple-series)

**Comment by diosmosis** [comment] 2020-01-27 13:26
Maybe caused by a composer setting? I'm not sure why this would fail.

**Comment by tsteur** [comment] 2020-01-27 20:32
I can reproduce the issue. Not sure why it doesn't work though or how it needs to be configured etc. It looks like we used to use 1.1 so we could change it to 1.2 or so?

**Comment by sgiehl** [comment] 2020-01-27 20:39
I've created PRs to update that, but actually the latest release has
another bug, that produces warnings on PHP 5 and an error on PHP 7. Created
a PR to fix it in the lib. Hope it gets merged soon and a new version is
released, so we can update it...

>

**Comment by limitstudios** [comment] 2020-01-30 17:05
@sgiehl looks like a new release maybe coming next week https://github.com/davaxi/Sparkline/pull/15#issuecomment-580148795

**Closed** 2020-02-06 09:13 UTC
Labels: Bug
