### ISSUE TITLE
Brief flashing of Opps... there was a problem

### ISSUE THREAD

**Issue by cpoetter** [matomo-org/matomo#14345] opened 2019-04-12 12:15 UTC
Hi,

I am very new to Matomo. I installed it just yesterday with the help of the official docker image, the MySQL docker image and the Redis docker image. Additionally I am using a Nginx load balancer in front of it for SSL termination. I also setup the archiving cron job for every hour.

So far everything works great. But I am seeing with every dashboard load a very brief ( < 0.1 seconds ) flash of this:

```
Oops... there was a problem during the request. Maybe the server had a temporary issue, or maybe you requested a report with too much data. Please try again. If this error occurs repeatedly please contact your Matomo administrator.
```

I am very certain that my 1 user per day test page does not trigger the `maybe you requested a report with too much data` part of the error 🤣

I installed the **LogViewer** plugin, but I have a feeling that it does not work with the installation inside a docker image (all logs are piped out to stdout stderr?), because I always see the following error, even with log level `DEBUG` in the **Log Viewer**:

```
Specified path to log file does not exist: /var/www/html/tmp/logs/matomo.log
```

In the log files of the docker container I can see a lot of *GET* and *POST* request in *stdout*, but nothing that looks like an error or anything in *stderr*.

Thank you very much for your help!

**Comment by Findus23** [comment] 2019-04-12 12:17
Hi,
Can you check the browsers developer tools for errors in the console or failed requests in the network tab?

**Comment by cpoetter** [comment] 2019-04-12 12:23
Hi @Findus23,

thank you very much for your help! I see only this warning:

```
possible region mismatch! – "BY" – 1 in index.php:6452:44098
```

(And a 404 error for /bundle.min.js.map.)

Thanks again for your help!

**Comment by mattab** [comment] 2020-01-21 05:38
@cpoetter Thanks for the report, marking as duplicate of: https://github.com/matomo-org/matomo/issues/15287

if you know the steps to reproduce please add a comment the issue, it will be very helpful :+1:

**Closed by mattab** 2020-01-21 05:38 UTC
