### ISSUE TITLE
Old name "piwik" is not completely changed to "matomo"

### ISSUE THREAD

**Issue by vekunz** [matomo-org/matomo#12484] opened 2018-01-19 08:33 UTC
Hi, i just changed the subdomain of my personal Matomo to the new name. But because I forgot to add the new subdomain to the trusted domains list, I got a warning message. And in this warning message you forgot to change "piwik" to "matomo" in some cases.
I added a (german) screenshot of the warning (by the way there are some missing translations, and the button at the bottom is "missing").

<img width="1440" alt="bildschirmfoto 2018-01-19 um 09 01 55" src="https://user-images.githubusercontent.com/5724298/35141578-a3bb706c-fcfb-11e7-90d1-bc7141c6a582.png">

**Comment by Findus23** [comment] 2018-01-19 08:40
Hi,

The change is only missing in the German translation:
https://github.com/matomo-org/matomo/blob/463f6bb4da35635df2741f30d4400cf0b67129be/plugins/CoreHome/lang/de.json#L29

The English source file has been replaced:
https://github.com/matomo-org/matomo/blob/463f6bb4da35635df2741f30d4400cf0b67129be/plugins/CoreHome/lang/en.json#L33

If you want to help translating join Matomo on Transifex:
https://www.transifex.com/matomo/matomo

There you can find all Translations including "Piwik" (for the CoreHome plugin):
https://www.transifex.com/matomo/matomo/translate/#de/matomo-plugin-corehome/44536445?qt=Piwik

**Comment by vekunz** [comment] 2018-01-19 08:51
Ok, but the third "piwik" (in the path) is in an englisch string.

**Comment by Findus23** [comment] 2018-01-19 11:25
This seems to be caused by this line:
https://github.com/matomo-org/matomo/blob/463f6bb4da35635df2741f30d4400cf0b67129be/core/Plugin/Controller.php#L800-L803

**Comment by matomoto** [comment] 2018-01-20 15:50
Matomo 3.3.0
```
piwik/xxx-piwik.txt
piwik/tmp/cache/tracker/piwikcache_ReportFactoryMap_2-8ead3d86ffa59e619836946cb55bea78-en.php
piwik/tmp/cache/tracker/piwikcache_marketplace.api.2.0.plugins.checkUpdates.281823630ca0623a029202254aa2953e.php
piwik/tmp/cache/tracker/piwikcache_marketplace.api.2.0.plugins.bda6c92c88de2431ef1fc1f97f83f9af.php
piwik/tmp/cache/tracker/piwikcache_allSiteUrlsPerSite.php
piwik/tmp/cache/tracker/piwikcache_2.php
piwik/tmp/cache/tracker/piwikcache_Translations-en-171a3f59fbe7aa1718656cf11a34397500040668.php
piwik/tmp/cache/tracker/piwikcache_Translations-en-2febaebb86f3321e46993b609a6ec65bea917ff1.php
piwik/tmp/cache/tracker/piwikcache_Translations-de-2febaebb86f3321e46993b609a6ec65bea917ff1.php
piwik/tmp/cache/tracker/piwikcache_marketplace.api.2.0.plugins.a15caad8bbd2bdbf27d8836a65ea16e9.php
piwik/tmp/cache/tracker/piwikcache_general.php
piwik/vendor/piwik
piwik/vendor/piwik/piwik-php-tracker
piwik/misc/others/uninstall-delete-piwik-directory.php
piwik/misc/proxy-hide-piwik-url
piwik/piwik.php
piwik/js/piwik.min.js
piwik/js/piwik.js
piwik/piwik.js
piwik/plugins/Zeitgeist/templates/_piwikTag.twig
piwik/plugins/Zeitgeist/javascripts/piwikHelper.js
piwik/plugins/CoreHome/angularjs/piwikApp.config.js
piwik/plugins/CoreHome/angularjs/piwikApp.js
piwik/plugins/CoreHome/angularjs/common/services/piwik-api.spec.js
piwik/plugins/CoreHome/angularjs/common/services/piwik-api.js
piwik/plugins/CoreHome/angularjs/common/services/piwik-url.js
piwik/plugins/CoreHome/angularjs/common/services/piwik.js
piwik/plugins/CoreHome/angularjs/common/services/piwik.spec.js
piwik/plugins/Morpheus/javascripts/piwikHelper.js
piwik/plugins/Morpheus/fonts/piwik.ttf
piwik/plugins/Morpheus/fonts/piwik.svg
piwik/plugins/Morpheus/fonts/piwik.woff
```
;)

**Comment by sgiehl** [comment] 2018-01-20 15:55
@matomoto We are not able to fully rename all files within the next releases, as that would break compatibility with older versions. We will likely rename the last files and classes with release of version 4.0.

**Comment by sgiehl** [comment] 2018-02-02 17:31
Closing in favor of #12420

**Closed by sgiehl** 2018-02-02 17:31 UTC
