### ISSUE TITLE
Error message after update to 3.9.0

### ISSUE THREAD

**Issue by hkbln** [matomo-org/matomo#14232] opened 2019-03-19 12:45 UTC
Matomo encountered an error: Call to undefined method Piwik\Plugin\Manager::getPluginDirectory() (which lead to: Circular dependency detected while trying to resolve entry 'Piwik\Twig')
what to do?

**Comment by fdellwing** [comment] 2019-03-19 13:22
Duplicate of #14227

**Comment by Findus23** [comment] 2019-03-19 13:38
Duplicate of #14227

**Closed by Findus23** 2019-03-19 13:38 UTC
