### ISSUE TITLE
Error: Variable "siteName" does not exist.

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#12690] opened 2018-03-31 09:54 UTC
Certainly an edge case, but this fatal error happened twice and should be prevented:
```
Error: {"message":"Variable \"siteName\" does not exist.","file":"\/plugins\/Morpheus\/templates\/dashboard.twig","line":11}

URL: index.php?module=Cloud&action=help&idSite=1&period=day&date=yesterday&showaddsite=false

Referrer: index.php?module=CoreAdminHome&action=generalSettings&idSite=1&period=day&date=yesterday&showaddsite=false
```

**Comment by sgiehl** [comment] 2018-03-31 14:49
This might more be a problem of Cloud.

**Comment by tsteur** [comment] 2018-03-31 20:22
Likely a duplicate of https://github.com/matomo-org/matomo/issues/12617 and possibly a core issue.

**Comment by mattab** [comment] 2018-05-21 06:15
Haven't seen this error since April 16th so should be fixed :+1:

**Comment by mattab** [comment] 2018-09-18 22:11
Actually just today got the error again:

```
 Error: {"message":"Variable \"siteName\" does not exist.","file":"\/plugins\/Morpheus\/templates\/dashboard.twig","line":11}
```

**Comment by diosmosis** [comment] 2018-09-18 22:26
No stack trace?

**Comment by tsteur** [comment] 2018-09-18 22:29
This particular problem can be likely fixed in a plugin of ours...

**Closed by tsteur** 2018-09-18 22:29 UTC
Labels: Bug
