### ISSUE TITLE
Unable to Install a plugin from market place when LoginLdap is active and Login is inactive

### ISSUE THREAD

**Issue by r621549** [matomo-org/matomo#14770] opened 2019-08-14 22:41 UTC
Unable to Install a plugin from marketplace after install ldap plugin

**Comment by r621549** [comment] 2019-08-14 22:48
when clicking on install button , it is throwing this error 

An error occurred
The plugin Login is not enabled. You can activate the plugin on Settings > Plugins page in Matomo.

**Comment by tsteur** [comment] 2019-08-14 23:51
Could you enable the plugin?

**Comment by gramakri** [comment] 2020-01-30 22:10
@mattab @tsteur  I hit this issue today. Here's more information:

1. Login as super user
2. Enable matomo LDAP plugin - https://plugins.matomo.org/LoginLdap
2.5. Clear the session objects on server and relogin as super user.
3. Go to marketplace and try to install a plugin . It fails with `The plugin Login is not enabled. You can activate the plugin on Settings > Plugins page in Matomo.`

From what I can make out:
1. When LDAP plugin is enabled, the Login plugin is disabled. The super user is still logged in using the "Login" module (?)
2. When you install a plugin now from the marketplace, the installer redirects to a page where it asks for the password for confirmation. This is handled by the Login module which is now disabled and thus the error message.

To hit the problem, it is important that you had not entered the password previously! I guess this is because it's remembered in the session somewhere. This is why step 2.5 above is important.

Workaround: If using the LDAP module, the super user has to disable it first and then install modules and then re-activate the LDAP module.

Can this bug be re-opened? Maybe a doc fix or a code fix.

**Comment by cronventis** [comment] 2020-04-20 06:01
I dont think to disable and enable LDAP every time you want to install something is a viable solution...

**Comment by cronventis** [comment] 2021-07-27 10:14
@mattab : This issue is still open, is there any intention to fix this?

**Comment by tsteur** [comment] 2021-07-27 20:48
@cronventis are you using the latest version of Matomo and also the latest version of the other plugins?

**Comment by cronventis** [comment] 2021-07-28 06:29
Yes, and yes.

Matomo 4.3.1
Ldap: 4.3.0

**Comment by tsteur** [comment] 2021-07-29 02:13
AFAIK this should have been fixed by https://github.com/matomo-org/matomo/pull/15945 and I just tried to reproduce this but couldn't. Is this still the same error that is happening? What's the URL when this error happens?

**Comment by cronventis** [comment] 2021-07-29 06:14
Hmmmm... Just now I tried it again to get the url and error message....... But its working now? wt*?

**Comment by sgiehl** [comment] 2021-07-29 11:15
@cronventis Thanks for the confirmation that it's working now. I'm closing this one then. If you experience this or another issue again, feel free to create a new issue here.

**Closed by sgiehl** 2021-07-29 11:15 UTC
Labels: Bug
