### ISSUE TITLE
Official PHP Reporting Client, or at least link those that already exist

### ISSUE THREAD

**Issue by guix77** [matomo-org/matomo#16291] opened 2020-08-13 10:20 UTC
Hi, would it be possible to provide an official PHP Reporting Client for the Reporting API or at least evaluate & eventually link in the doc those that already exist?

- doc: https://developer.matomo.org/guides/reporting-api-clients
- https://github.com/pfrenssen/matomo-reporting-api
- https://github.com/VisualAppeal/Matomo-PHP-API

**Comment by Findus23** [comment] 2020-08-13 10:49
Hi,

I don't think an official client is the highest priority because in most languages you can simply make the API request in a few lines of custom code that doesn't introduce a dependency and fits to the existing code style.

That said, I think it should be fine to e.g. create a new subpage at https://developer.matomo.org/api-reference/reporting-api which links to those existing clients.

**Comment by guix77** [comment] 2020-08-13 11:07
Hey,

I find it rather strange to not link the existing API clients, but link the one for Laravel and for other languages.

That said, I agree with you. I'm planning to finally directly call the API through Guzzle, because I don't want to depend on a library that might be lagging behind Matomo API.

However, if Matomo was written in such a way that it would use its own API client as a composer package, then every one could use it as well in any PHP project. But we're talking about a major rewrite here, so... :)

**Comment by tsteur** [comment] 2020-08-13 22:02
Hi there. Can we close this one as a duplicate of https://github.com/matomo-org/matomo/issues/7268 @guix77 @Findus23 ? i suppose this one here is more like just documenting the existing libraries and not really a duplicate?

**Comment by guix77** [comment] 2020-08-13 23:07
Hi, perfect on my side, thanks and sorry, I didn't see #7268

**Comment by Findus23** [comment] 2020-08-14 08:47
It turns out that this page already exists at https://docs.matomo/guides/reporting-api-clients and I updated it in https://github.com/matomo-org/developer-documentation/pull/369 to mention the unofficial clients.

**Closed** 2020-08-14 20:09 UTC
Labels: c: Documentation
