### ISSUE TITLE
Some issues with Site Search Keywords in 2.16.2

### ISSUE THREAD

**Issue by dstarmanhr** [matomo-org/matomo#10486] opened 2016-09-12 06:08 UTC
Hi,

We are having some issues with tracking Site search keywords after upgrading to 2.16.2 version:

This is before the upgrade:

[￼https://cdn-standard.discourse.org/uploads/piwik/original/2X/1/1878a4cbb2c8e3f95fb8f68d599c7a51316059da.png](https://cdn-standard.discourse.org/uploads/piwik/original/2X/1/1878a4cbb2c8e3f95fb8f68d599c7a51316059da.png)

And this is after:

https://cdn-standard.discourse.org/uploads/piwik/original/2X/7/75990f2f14bf054b7144aea4afa10cc5a643897a.png

in next post as i can only post one image.

It looks like it might be inserting data into the wrong table? Or reading from wrong table?

Thnx for loking into it.

**Comment by mattab** [comment] 2016-09-27 02:32
Hello @dstarmanhr 

So far I cannot reproduce this issue. Looks like it's working on the demo: http://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=7&period=month&date=2016-09-20#?module=Actions&action=indexSiteSearch&idSite=7&period=month&date=2016-07-20

or can you reproduce this issue on the demo?

Or maybe you changed something on your website around the time of the migration? when did the data start changing if you look day-by-day... does it change on the day of the Piwik upgrade?

**Comment by mattab** [comment] 2016-09-28 21:21
Which PHP version are you using?

**Comment by dstarmanhr** [comment] 2016-09-30 13:42
hi, its nginx+php-fpm, php version:

php -v
PHP 5.6.23 (cli) (built: Jun 24 2016 09:53:22)

**Comment by dstarmanhr** [comment] 2016-09-30 13:43
I can't reproduce it in the demo but the data changed exactly on the day of the upgrade.

**Comment by sgiehl** [comment] 2020-07-23 09:49
We've change the implementation of site search keywords with Matomo 4 a bit. As this issue is already quite old, I'll close it. Feel free to create a new one, if something like this happens again with a new version of Matomo

**Closed by sgiehl** 2020-07-23 09:49 UTC
Labels: Waiting for user feedback
