### ISSUE TITLE
visit action url is garbled

### ISSUE THREAD

**Issue by yhlin00001** [matomo-org/matomo#13424] opened 2018-09-13 08:59 UTC
Wimdows 2016 IIS + PHP 7.1.10
If the page url is chinese, it will display garbled in visit record page and export to json/xml (but data is correct in db).

Hiw can I solve it ?

**Comment by yhlin00001** [comment] 2018-09-13 14:42
in download
![image](https://user-images.githubusercontent.com/1841976/45495560-0ddf6b00-b7a6-11e8-9b10-55f4633b5fd0.png)

in visit record
![image](https://user-images.githubusercontent.com/1841976/45495636-36676500-b7a6-11e8-8288-64c6066ec2b0.png)

**Comment by tsteur** [comment] 2018-09-13 21:19
Can you maybe paste the path part of the URL in here? This will make it easier to reproduce so we can copy/paste. Cheers

**Comment by yhlin00001** [comment] 2018-09-13 21:27
http://web.my-mall.biz/文件庫/個人金融部/個人金融部對外/政策性貸款/DocLib/▲青創相關文件-106年11月.zip

**Comment by yhlin00001** [comment] 2018-09-13 21:32
And piwik can not export to json format data if piwik had this kind of visit record .
We tested in matomo 3.2.0 & 3.5.1.

**Comment by yhlin00001** [comment] 2018-09-15 12:09
I think, I have solved this issue. But please help me to check if it will have any site-effect. Thanks

in PageUrl.php, I change as the follow:

    public static function reconstructNormalizedUrl($url, $prefixId)
    {
        $map = array_flip(self::$urlPrefixMap);

        if ($prefixId !== null && isset($map[$prefixId])) {
            $fullUrl = $map[$prefixId] . $url;
        } else {
            $fullUrl = $url;
        }

        // Clean up host & hash tags, for URLs
		// YH
			$fullUrl = urlencode($fullUrl);
        $parsedUrl = @parse_url($fullUrl);
		// YH
			$parsedUrl[path] = urldecode($parsedUrl[path]);
			$parsedUrl[query] = urldecode($parsedUrl[query]);
		echo '--parseUrl_1===';
		print_r($parsedUrl);
        $parsedUrl = PageUrl::cleanupHostAndHashTag($parsedUrl);
		echo '--parseUrl_2===';
		print_r($parsedUrl);
        $url       = UrlHelper::getParseUrlReverse($parsedUrl);

        if (!empty($url)) {
			echo '--url='.$url.'<br/>';
            return $url;
        }

		echo '--fullUrl='.$fullUrl.'<br/>';
        return $fullUrl;
    }

**Comment by yhlin00001** [comment] 2018-09-15 12:10
Sorry, this is correct code:

    public static function reconstructNormalizedUrl($url, $prefixId)
    {
        $map = array_flip(self::$urlPrefixMap);

        if ($prefixId !== null && isset($map[$prefixId])) {
            $fullUrl = $map[$prefixId] . $url;
        } else {
            $fullUrl = $url;
        }

        // Clean up host & hash tags, for URLs
		// YH
			$fullUrl = urlencode($fullUrl);
        $parsedUrl = @parse_url($fullUrl);
		// YH
			$parsedUrl[path] = urldecode($parsedUrl[path]);
			$parsedUrl[query] = urldecode($parsedUrl[query]);
        $parsedUrl = PageUrl::cleanupHostAndHashTag($parsedUrl);
        $url       = UrlHelper::getParseUrlReverse($parsedUrl);

        if (!empty($url)) {
            return $url;
        }

        return $fullUrl;
    }

**Comment by fdellwing** [comment] 2018-09-15 18:09
Best would be you create a PR its easier to read and test.

**Comment by yhlin00001** [comment] 2018-09-21 02:30
finally, we replace parse_url with the following method:
public static function mb_parse_url($url)
    {
        $enc_url = preg_replace_callback(
            '%[^:/@?&=#]+%usD',
            function ($matches)
            {
                return urlencode($matches[0]);
            },
            $url
        );
        
        $parts = parse_url($enc_url);
        
        if($parts === false)
        {
            throw new \InvalidArgumentException('Malformed URL: ' . $url);
        }
        
        foreach($parts as $name => $value)
        {
            $parts[$name] = urldecode($value);
        }
        
        return $parts;
    }

**Comment by mattab** [comment] 2019-03-19 09:37
Got another report from a customer:

This is the parse_url function that raises concerns about some configurations https://bugs.php.net/bug.php?id=52923

By replacing this function with this one http://php.net/manual/en/function.parse-url.php#114817
 replacing parse_url with Common :: mb_parse_url here https://github.com/matomo-org/matomo/blob/af3a79c055bfe2c5778b5827ba3d165674315f4b/core/Tracker/PageUrl.php#L43

it may solve the problem?

I think it would take a larger fix such as for strtolower (https://github.com/matomo-org/matomo/issues/10083) since this is not the only place where matomo uses parse_url.

**Comment by mattab** [comment] 2019-03-19 09:41
FYI In customer's case (in previous comment) the issue was fixed (or rather: worked around) by configuring PHP to use `LC_CTYPE` of `fr_FR.UTF-8` instead of the previous value (where error was triggered) of  `fr_FR`.

**Comment by guytarr** [comment] 2019-03-20 15:05
I add in Core/Common.php http://php.net/manual/en/function.parse-url.php#114817 with support of optionnal arg "component" (see below) and replace everywhere parse_url by Common::mb_parse_url .
Be Careful to add
```
use Piwik\Common;
```
in files when it is not present
```
    /**
     * parse_url() UTF-8 aware.
     * See https://bugs.php.net/bug.php?id=52923
     * See https://secure.php.net/manual/en/function.parse-url.php#114817
     *
     * @param url $string
     * @param int $component
     * @return string
     */
    public static function mb_parse_url($url, $component = -1)
	{
		$enc_url = preg_replace_callback(
			'%[^:/@?&=#]+%usD',
			function ($matches)
			{
				return urlencode($matches[0]);
			},
			$url
		);
		
		$parts = parse_url($enc_url, $component);
		
		if($parts === false)
		{
			throw new \InvalidArgumentException('Malformed URL: ' . $url);
		}
		
		if($component != -1) 
		{
			return urldecode($parts);
		}
		
		foreach($parts as $name => $value)
		{
			$parts[$name] = urldecode($value);
		}
		
		return $parts;
	}
```

**Comment by sgiehl** [comment] 2019-03-23 10:35
@guytarr would you mind creating a PR with your changes?

**Comment by s1awa** [comment] 2019-08-20 07:40
Not only the URL but also the page title can not display all UFT-8 characters in matomo.

If page title is
`📧 Contact`
it will show up as
`� Contact`

**Comment by sgiehl** [comment] 2019-08-20 07:58
@s1awa that's on purpose as the database tables are not yet utf8mb4. Not supported characters are currently converted to �. This will be changed in Matomo 4. See https://github.com/matomo-org/matomo/issues/9785

**Comment by slawa-dev** [comment] 2020-11-26 04:02
I updated to version 4 and converted the database tables to utf8mb4. Now everything shows up as expected!

**Comment by mattab** [comment] 2023-12-10 11:32
Thanks for contributing to this issue. As it has been a few months since the last activity and we believe this is likely not an issue anymore, we will now close this. If that's not the case, please do feel free to either reopen this issue or [open a new one](https://developer.matomo.org/guides/core-team-workflow#submitting-a-bug-report). We will gladly take a look again!

**Closed by mattab** 2023-12-10 11:32 UTC
Labels: Bug
