### ISSUE TITLE
3.9.1 - Email report conains IP address instead of hostname

### ISSUE THREAD

**Issue by GavL89** [matomo-org/matomo#14413] opened 2019-05-05 23:46 UTC
Relatively fresh deployment of Matomo 3.9.1 - the email reports contain the IP address of the server instead of the hostname:
Please find below your day report for site 
Site - Daily Digest 
Date range: Tuesday, April 30, 2019 
Sent from http://192.168.4.251/. 

We have multiple servers running behind a load balancer in AWS and have set things such as trusted hostnames in the config.ini.php file.  We've followed the steps in this guide to implement load balancing: https://matomo.org/faq/new-to-piwik/faq_134/

I've also tried updating the piwikUrl row in the database however it just gets updated by itself to the IP address of one of the servers.

Happy to provide other information, just let me know.

**Comment by tsteur** [comment] 2019-05-06 00:31
@GavL89 I'll mark it as a duplicate of https://github.com/matomo-org/matomo/issues/11029

We also had other similar issues like https://github.com/matomo-org/matomo/issues/13176 and https://github.com/matomo-org/matomo/pull/13122 and I reckon we thought it was changed. 

Is any of the trusted hostnames an IP? I'll create a comment in https://github.com/matomo-org/matomo/issues/11029

**Closed by tsteur** 2019-05-06 00:31 UTC

**Comment by GavL89** [comment] 2019-05-06 00:34
Thanks @tsteur - I've put a comment onto the other thread with some more information.
