### ISSUE TITLE
GDPR Improvements - integrate quick access in Visitor profile

### ISSUE THREAD

**Issue by dev-101** [matomo-org/matomo#14109] opened 2019-02-17 14:14 UTC
I suggest we integrate GDPR toolbox directly in Visitor profile page for quicker operation:

![piwik-matomo-gdpr-improvements](https://user-images.githubusercontent.com/5383059/52913742-5fde6c80-32c1-11e9-879d-70a5a3b95e59.png)

~~User~~ **Visitor ID** is now a link, it makes it a bit harder to copy (Chrome browser offers only "copy link address" for example) - make this easier, so we can directly copy ID into clipboard.

Additionally, add quick-access GDPR options to EXPORT (not shown in mock-up) and DELETE this visitor from the analytics directly from the profile page.

Thanks

**Comment by tsteur** [comment] 2019-02-17 19:12
Hi there, this is a duplicate of https://github.com/matomo-org/matomo/issues/3385#issuecomment-383769596 where we will integrate those features.

**Closed by tsteur** 2019-02-17 19:12 UTC
