### ISSUE TITLE
#13113 not fixxed - segmented visitors empty if url contains whitespaces

### ISSUE THREAD

**Issue by fdellwing** [matomo-org/matomo#13460] opened 2018-09-20 10:15 UTC
@sgiehl I just took a look at this with your fix applied and it is not fixxed for me.

![matomo2](https://user-images.githubusercontent.com/22813377/45811965-cccbe700-bcce-11e8-8127-ef57efda6208.png)

**Comment by fdellwing** [comment] 2018-09-20 10:17
This PR should have fixxed it:  #13198

**Comment by eetasse** [comment] 2018-09-20 12:03
I confirmed #13113 not fixed in 3.6.0. 

URL Sent to Matomo : https://........./display/~EtasseE/Backup+plan+October+2017
In the Matomo UI (Behaviour|Page screens) we have: https://........./display/~EtasseE/Backup plan October 2017

The + (PLUS) chars have been replaced with whitepaces. As a consequence the "Open Segmented Visitor Log" does not show any data. As soon there is one whitepace in the "page URL" on this screen it does not work.

**Comment by diosmosis** [comment] 2018-09-23 23:37
Don't have a fix yet, but found the cause of the error. Actions are stored urlencoded in the log_action table, but the value in the segment when opening the segmented visitor log/transitions modal/etc. is not. This results in Matomo looking for an idaction where the name is, eg, `example.org/with+plus-sign/` instead of `exampleo.org/with%2Bplus-sign/`. Somewhere the value is either getting urldecoded or needs to be urlencoded.

**Closed** 2019-10-02 20:33 UTC
Labels: Bug
