### ISSUE TITLE
Content impressions generate "0 Action" in visitor log

### ISSUE THREAD

**Issue by hmage** [matomo-org/matomo#6415] opened 2014-10-10 19:14 UTC
After adding the content impression, my visitor log got spammed with "0 Action" entries.

![image](https://cloud.githubusercontent.com/assets/739119/4597720/061fd874-50b1-11e4-9354-26d31c11a1d5.png)

I don't think this is intended, so I'm opening an issue.

Images with links are marked something like this:

``` html
<a target="_blank" href="images/image-104.jpg" data-track-content 
   data-content-name="Image #104">
<img src="images/image-104-thumb.jpg" alt="Image #104" data-content-piece/>
</a>
```

**Comment by mattab** [comment] 2015-04-07 07:26
@tsteur what do you think is the status & next step of this Bug?

**Comment by tsteur** [comment] 2015-04-07 20:58
From my point of view it can be closed. You wanted to leave it open so users can find it

**Comment by mattab** [comment] 2015-11-25 00:34
The bug is still actually live, leaving opened

**Comment by jcm77** [comment] 2015-11-26 08:23
Hi, 

after implementing content tracking I started to get visits with 0 Actions and my Bounce Rate is being seriously affected. I´m using the 2.15.0 Version and the issue is still there. 
I will see if this http://plugins.piwik.org/QueuedTracking works. 

Thanks,

JCM77

**Comment by jcm77** [comment] 2015-12-02 16:24
Hi Matt, 

we installed the plug-in and unfortunately we still have the problem. We keep looking for ways to solve the issue, one of them could be to disable the content tracking and see if the problem persists. 

I will let you know if we can solve it 

Regards

Javier

**Comment by hpvd** [comment] 2016-07-15 13:52
hmm is there any news/solution on this?
would be awesome to share it here.

**Comment by tsteur** [comment] 2016-07-17 20:30
The only known workaround is to use the QueuedTracking plugin see https://github.com/piwik/piwik/issues/6415#issuecomment-159448227

**Comment by huang0808** [comment] 2018-07-26 08:12
@tsteur  I meet this issue, when I update to 3.4.0. show many 0 action. and In my develop server, it is not many request, but it still show 0 action. Have you help me see the issue?

thanks,

Sophie Wang

**Comment by tsteur** [comment] 2018-07-26 18:44
See one comment above. Give the plugin [Queued Tracking](https://plugins.matomo.org/QueuedTracking) a try. It is now easy to set it up and likely fixes all the issues.

**Comment by tsteur** [comment] 2019-08-17 18:56
I haven't over all the comments but wouldn't a similar solution that we do to avoid duplicate actions do?
* Like we insert the visit
* then we select like all visits that were created in the last 1 min matching the config_id or the visitor_id (depending on the config settings, config_id match has index and is fast anyway)
* we only keep the visit with the lowest id or so.

Haven't thought much about it though but something like this could work here too? But of course it be another select for new visits. @mattab

**Comment by mattab** [comment] 2019-10-21 09:02
> Haven't thought much about it though but something like this could work here too? But of course it be another select for new visits. @mattab

This might work :+1:

**Comment by mattab** [comment] 2023-12-11 05:34
## FYI: The solution: Give the plugin [Queued Tracking](https://plugins.matomo.org/QueuedTracking) a try. This should fix this issue. 

As it has been a few months since the last activity and we believe this is likely not an issue anymore, we will now close this. If that's not the case, please do feel free to either reopen this issue or [open a new one](https://developer.matomo.org/guides/core-team-workflow#submitting-a-bug-report). We will gladly take a look again!

**Closed by mattab** 2023-12-11 05:34 UTC
Labels: Bug, Major
