### ISSUE TITLE
Feature: preview mode based on cookies

### ISSUE THREAD

**Issue by Laul0** [matomo-org/matomo#15941] opened 2020-05-12 03:00 UTC
# Summary

An over approach to display the debug console in preview mode based on Google Tag Manager experience

## Current behavior

After enable the preview mode, you have to go the the target site and add arguments to the URL:

* either ?mtmPreviewMode=[Tag Manager container ID]
* or &mtmPreviewMode=[Tag Manager container ID]

## Expected behavior

Once preview mode enable, go the the target site with the same browser and the debug console appears alone.
To hide the console, disable the preview mode.

The preview mode manage a cookie into the browser to determine if the debug console have to be displayed or not in addition to the Matomo Tag Manager configuration.

### Pros

* Not need to add argument to the URL
* Don't lost the argument when click on link (page navigation)
* Based on cookies for the same browser (security - avoid that someone who know how to enable debug mode try to enable it)

### Cons

* Can't share the preview mode with other people
* Have to use the same browser to display the debug console

That's it 🙂

Don't hesitate if you need some additional information.

**Comment by tsteur** [comment] 2020-05-14 21:23
Cheers @Laul0 closing this as a duplicate of https://github.com/matomo-org/tag-manager/issues/217 As mentioned there we are setting a cookie already, but this only works when both Matomo and the site itself runs on the same domain so far.

**Closed by tsteur** 2020-05-14 21:23 UTC
