### ISSUE TITLE
"MySQL has gone away" more common with PHP 7.2+

### ISSUE THREAD

**Issue by millnut** [matomo-org/matomo#15451] opened 2020-01-24 08:17 UTC
Hi,

I've setup quite a few matomo instances at our hosting company and have noticed that as soon as we upgrade a customers PHP to 7.2 or above, the matomo instance starts showing lots of "MySQL has gone away" errors and performance goes down.

As soon as we downgrade back to 7.1 these errors go away and the system functions and performs fine. With PHP 7.1 being end of life, it would probably be a good idea looking to support the newer versions and ensuring performance is on par or better, and that errors like the above don't appear.

I'm a PHP developer myself so happy to work with you guys and provide a test environment to help debug and fix.

**Comment by tsteur** [comment] 2020-01-26 20:08
@limitstudios It be great if you look into this and find something. Have you tested if there is again a difference for PHP 7.3? Are you maybe planning to give it a try?

Maybe PHP 7.2 regressed performance in some particular features. It's possible these performance issues only apply when using specific features/configurations. Some issues might only happen on a specific load etc. While we do support newer PHP versions, it's impossible for us to do advanced performance/load tests for different PHP versions unfortunately.

**Comment by limitstudios** [comment] 2020-01-27 09:05
Hi @tsteur I would imagine there is, from my testing on a live environment it seems to affect 7.2 and 7.3.

I've almost got my profiling working and I'm able to reproduce the performance difference locally so will let you know what I find.

**Comment by Findus23** [comment] 2020-04-20 08:16
There is a suspiciously large amount of people reporting something similar to this:
After updating from PHP<7.2 to any version >=7.2, they get a lot of `MySQL has gone away` errors to the point where Matomo is unusable.
My initial guess was that someone had a custom fix in the old PHP config and didn't apply it to their new PHP config after updating, but there are too many reports for this to accidentally happen.

Another common thing I see, is that this happens more often on shared hosters, so we can't get more information about the MySQL setup. 

Some examples:
- https://forum.matomo.org/t/php-version-change-causes-server-gone-away-error/36978
- https://forum.matomo.org/t/problems-with-php-7-2/36803/5
- https://forum.matomo.org/t/mysqli-prepare-error-mysql-server-has-gone-away-on-cpanel/35990 (maybe)
- https://forum.matomo.org/t/probleme-php-7-2-18/34177
- https://forum.matomo.org/t/matomo-on-hostinger-shared-hosting/33546 (maybe)
- https://forum.matomo.org/t/matomo-on-hostinger-shared-hosting/33546 (multiple people)

If someone has a clue on how to reproduce this or what could be causing this change, please comment.

**Comment by limitstudios** [comment] 2020-04-20 09:50
I can provide a shared hosting environment where this is reproducible if it helps?

**Comment by Findus23** [comment] 2020-04-20 09:55
@limitstudios Is your shared hoster by chance in Germany? Maybe it is even the same shared hoster for everyone reporting the issue?

**Comment by limitstudios** [comment] 2020-04-20 10:02
Nope UK based it could be they all have the same CPanel setup and setting the website version from <7.2 to >=7.2 makes something trigger unexpectedly

**Comment by Findus23** [comment] 2020-04-24 12:57
This might be a hint in the right direction:
https://forum.matomo.org/t/php-version-change-causes-server-gone-away-error/36978/2?u=lukas

**Comment by tsteur** [comment] 2020-04-26 02:14
Interesting. If this indeed improves it, might be worth switching to nd_mysqli or nd_pdo_mysql fyi @mattab

**Comment by limitstudios** [comment] 2020-04-26 09:24
This does seem somewhat connected, the options in that forum thread didn't fix it for me; however these steps did

- PHP Extensions
    - mysqli
    - mysqlnd
    - pdo_mysql

Now when I was getting a lot of the "MySQL has gone away errors" my adapter in config.ini.php was "MYSQLI" when I removed this line, which I think defaults to "PDO_MYSQL" the errors went away under 7.2 and 7.3 (currently on 7.3.17)

And I can access the system config status page and the widgets on the dashboard without any "MySQL has gone away" errors, I'll continue to monitor the beginning of this week when the data collection starts to ramp up again.

**Comment by louiswolf** [comment] 2020-05-08 09:30
For me the nd_mysqli solution seems to work for PHP 7.4.5 

> 
> 
> This might be a hint in the right direction:
> https://forum.matomo.org/t/php-version-change-causes-server-gone-away-error/36978/2?u=lukas

I've been fooling around with PHP and PHP-CLI versions to solve an old archiving issue (https://forum.matomo.org/t/mysql-server-has-gone-away/31760/8) that had slipped my mind, but returned after upgrading PHP on several domains.

The issue seems to appear exclusively when there are archiving tasks, breaking both core:archive (mysql server has gone away) and the web interface (all websites). 

I also noticed 2 ways in which the archive task (triggered by cron) fails: 
- sometimes it will just hang consuming a bit of memory, which after a few crons will consume a lot of memory. 
- In other cases the cronjob just finishes with errors. 

The above seems dependent on which combination of PHP versions I set. I'm using cpanel, where I can set PHP for both domains and CLI. However, I always get one or more `Error: Got invalid response from API request:` caused by a `Mysqli prepare error: MySQL server has goneaway`.

Not sure of the above is helpful, but let me know if I can provide you with more information.

**Comment by Findus23** [comment] 2020-05-09 14:46
One more user reported back that switching from MySQLi to PDO fixed the issue:
https://forum.matomo.org/t/problems-with-php-7-2/36803/15?u=lukas

**Comment by limitstudios** [comment] 2020-05-09 20:23
@Findus23 I wonder if PDO has some sort of connection cleanup/closing where as the MySQLi method doesn't do this in some cases?

**Comment by ThibaultVlacich** [comment] 2020-08-07 19:21
I have this issue, and I can't even install Matomo. I get the error "Error while trying to connect to the database server: SQLSTATE[HY000] [2006] MySQL server has gone away." during the step 3 "Database Setup" of the install.

Following [this article](https://fr.matomo.org/faq/troubleshooting/faq_183/) changed nothing.

**Comment by mattab** [comment] 2020-08-08 08:10
@ThibaultVlacich which php version do you use, can you try to upgrade to PHP 7.4 latest, this might help?

**Comment by ThibaultVlacich** [comment] 2020-08-08 08:12
@mattab I am using the [official Docker image](https://github.com/matomo-org/docker), so the version included with it (meaning php 7.4).

**Comment by tsteur** [comment] 2020-08-09 07:00
It might help to use eg php nd_mysqli or nd_pdo_mysql  https://github.com/matomo-org/matomo/issues/15451#issuecomment-625729287 . Any chance to try that in the one without SSD?

**Comment by dejwsz** [comment] 2020-10-28 08:42
In my case, this error disappeared after I changed the adapter from MYSQLI to PDO\MYSQL. I am using Matomo 3.14.1 with PHP 7.4.11 and MySQL 8.0.20-11.3. I tried any other things like this: https://matomo.org/faq/troubleshooting/faq_183/ and nothing helped. I had this error very often during cron archive. Right after I changed the type of the adapter the error isn't there anymore.

**Comment by rosa2** [comment] 2022-02-09 14:21
Hello and a pleasure to be able to give a little in this great community

I was having this problem also.
I followed this guide (one of the first when you search for Debian 10 and Matomo)
https://help.clouding.io/hc/en-us/articles/360015906879-How-to-Install-Matomo-Web-Analytics-on-Debian-10
There the user is created in mysql

`CREATE USER 'username'@'localhost' IDENTIFIED BY 'password';`

Then when going to create the database tables, automatically i will get the ip 127.0.0.1 and the error :scream_cat: 
Changing the ip by localhost was the solution :)
mysql  Ver 15.1 Distrib 10.3.31-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
I hope it helps someone.

Thanks for this great FLOSS software!

**Comment by michalkleiner** [comment] 2024-05-22 02:14
Hi, since Matomo doesn’t support PHP version below 7.2, we believe this was likely a server configuration issue as we would hear from more users otherwise.

We have also already implemented improvements around possible connection loss issues, and we have a related ticket for improving the connection resilience (#21807), so we will close this issue now. 

If you still experience the issue feel free to open a new bug report. Thank you for your understanding.

**Closed by michalkleiner** 2024-05-22 02:14 UTC
Labels: c: Performance, Can't reproduce (yet)
