### ISSUE TITLE
automatic update to 3.7 does not work for me

### ISSUE THREAD

**Issue by bavramor** [matomo-org/matomo#13749] opened 2018-11-22 14:49 UTC
The automatic update from 3.6.1 to 3.7 does not work. 
If I press automatic update then the next thing he says is that the update was successful and I should update the database. I did this via console with the following command:  
php /srv/www/piwik/console core:update

Then he says that the update was successful.

However, when I open Matomo's backend, everything is empty. The created pages can't be found anymore. The backend is in principle completely empty.

What am I doing wrong?

Greetings Bavra

![2018-11-22 15_21_11-window](https://user-images.githubusercontent.com/1936649/48909678-30f55d80-ee6e-11e8-98d1-6eafad49b504.png)

**Comment by Findus23** [comment] 2018-11-22 16:11
Hi,

Can you check your PHP error_log and the JavaScript console of your browser when you are seeing the empty page?

**Comment by bavramor** [comment] 2018-11-23 10:15
Thank you very much for your feedback. I'll make a copy and check it out. But I need a moment. I'll get back to you.

**Comment by bavramor** [comment] 2018-11-23 13:08
I have some new information about my problem. The apache error.log shows me the following error:

[Thu Nov 22 14:37:18.597288 2018] [core:alert] [pid 18600] [client 213.61.111.222:10587] /srv/www/piwik/libs/.htaccess: AddHandler not allowed here, referer: https://piwik. adexxxx.de/index.php?module=MultiSites&action=index&idSite=1&period=range&date=previous7

So, now I have commented out the AddHandler section of /libs/.htaccess and it seems it solves the problem. But why is there a problem? On my test environment the page and the update runs normally with the Addhandler part. Both sides are on the same server and have the same apache modules.

Greetings Bavra

Translated with www.DeepL.com/Translator

**Comment by tsteur** [comment] 2018-11-24 21:37
Which apache version are you using?

**Comment by bavramor** [comment] 2018-11-29 11:50
Is this enough information for you?

Server version: Apache/2.4.10 (Debian)
Server built:   Mar 31 2018 09:39:03

Greetings

**Comment by tsteur** [comment] 2018-11-29 19:30
Sorry I can't really help you there. Maybe someone else with apache knowledge knows more what is wrong with out htacess. I suppose this here seems to cause the problem: https://github.com/matomo-org/matomo/commit/e3139a3557ef685725516e693325ecebe7f1c247

Any chance you installed Matomo many years ago?

**Comment by axilleas** [comment] 2018-12-01 18:14
Duplicate of https://github.com/matomo-org/matomo/issues/13738?

**Comment by tsteur** [comment] 2018-12-01 19:05
@mattab also see duplicate #13738 ... is this maybe not needed anymore ?  was added in https://github.com/matomo-org/matomo/issues/5266

**Comment by mattab** [comment] 2019-03-20 01:41
Closing this issue. Please re-open if you still experience this issue in Matomo 3.9.0 and we will assist :+1:

**Closed by mattab** 2019-03-20 01:41 UTC
Labels: Bug
