### ISSUE TITLE
New users always see report from yesterday

### ISSUE THREAD

**Issue by Findus23** [matomo-org/matomo#13881] opened 2018-12-19 11:00 UTC
I think this is also one of these minor UX issues in Matomo that are obvious to everyone using it, but may leave a bad first impression to new users (and there are lots of people reporting this).

When you have finished setting up your first Matomo instance and have added the tracking code to the website, you finally see the first visitors come in the live-widget.
But all reports around seem to still show no data. Even an hour later all reports are still empty, until you notice that the date selector is set to "yesterday".

While it makes sense to set the date selector to yesterday, it may be useful to make an exception to the first day of new Matomo users to not make them think Matomo is broken.

**Comment by GreenReaper** [comment] 2018-12-19 11:49
I think they don't want you to see a partial day. Certain reports might also not be compiled yet?

Ideally 'the last 24 hours' might make more sense, but the whole UI is set up as days as the unit.

**Comment by tsteur** [comment] 2018-12-19 18:52
duplicate of https://github.com/matomo-org/matomo/issues/13754 and I think there is also an older issue about this somewhere.

**Closed by tsteur** 2018-12-19 18:52 UTC
Labels: c: Usability
