### ISSUE TITLE
Visitor maps not showing regions correctly in most countries

### ISSUE THREAD

**Issue by CGsama** [matomo-org/matomo#13347] opened 2018-08-25 17:50 UTC
I use the city db for geoip(php), all fine when using wordwide view. However, it couldn't show on reguion and city map. But correct at realtime map.
![5 ac r9qwjo91 un 6d 2o](https://user-images.githubusercontent.com/15722562/44621079-caac6f00-a86d-11e8-81c2-c1fd181cc5c1.png)
![s37 x s73o3r0 yh5x0xamp](https://user-images.githubusercontent.com/15722562/44621074-bd8f8000-a86d-11e8-8587-c95ca449af36.png)
![o6a xx h 0_snnmz k4](https://user-images.githubusercontent.com/15722562/44621075-bf594380-a86d-11e8-9309-5186b1d1fc5e.png)

**Comment by CGsama** [comment] 2018-08-25 18:40
I'm using the GeoIP2(php). Thanks for clarifying that. And for my IP which in Canada, I can see the region map shows correct.

**Comment by parruc** [comment] 2018-09-04 09:32
Same problem here: for Italy with GeoIP2 (php) I can see the cities correctly but all regions are marked as unknown.

**Comment by sgiehl** [comment] 2018-09-06 16:52
For GeoIP2 it will still show regions correctly if the FIPS and ISO code for a region is the same. That applies for US, CA and some smaller countries. We are working on updated maps to fully support the ISO codes GeoIP2 is using...

**Comment by mattab** [comment] 2019-03-19 09:19
Since the upgrade to Geoip2, most of countries regions are not displayed correctly in the Maps. 
Maybe we should consider disabling the feature of Region mapping on our maps, since it doesn't work mostly -> Moving into the milestone so we can take a decision.

 Because It feels bad to have a non working feature it may be easiest to disable region mapping completely

or should we "partially disable region mapping" if it still work for some countries? @sgiehl

**Comment by thinkof4** [comment] 2019-08-09 20:06
Will this bug ever be fixed, I mean this is an one year old issue...

**Comment by dfabreguette-ap** [comment] 2019-10-17 07:41
Same bug here ! Any workaround ?
![Capture d’écran 2019-10-17 à 09 39 43](https://user-images.githubusercontent.com/7055931/66988158-57456c80-f0c2-11e9-8c5c-1e010b30e981.png)

**Comment by mirkomaty** [comment] 2019-11-13 10:36
@sgiehl, @mattab 
What exactly is the problem with fixing this bug? These are the data we get from the maxdb:

{
	"city": {
...
		}
	},
	"continent": {
...	},
	"country": {
		"geoname_id": 2921044,
		"is_in_european_union": true,
		"iso_code": "DE",
		"names": {
			"de": "Deutschland",
			"en": "Germany",
			"es": "Alemania",
			"fr": "Allemagne",
			"ja": "????????",
			"pt-BR": "Alemanha",
			"ru": "????????",
			"zh-CN": "??"
		}
	},
	"location": {
...	},
	"postal": {
...	},
	"registered_country": {
...	},
	"subdivisions": [{
			"geoname_id": 2951839,
			"iso_code": "BY",
			"names": {
				"de": "Bayern",
				"en": "Bavaria",
				"es": "Baviera",
				"fr": "Bavière",
				"ja": "??????",
				"pt-BR": "Baviera",
				"ru": "???????",
				"zh-CN": "????"
			}
		}
	]
}

As we can see, in subdivisions.iso_code an iso_code is provided. If your maps are based on FIPS codes, all you have to do is to provide a translation based on a file, which can be filled by the community. We are interested in the regions for Germany. The FIPS codes for Germany are 

GM01_414_414_state_land___Baden-Wurttemberg__
GM02_414_414_state_land___Bayern__Bavaria
GM03_414_414_state_land___Bremen__
GM04_414_414_state_land___Hamburg__
GM05_414_414_state_land___Hessen__
GM06_414_414_state_land___Niedersachsen__
GM07_414_414_state_land___Nordrhein-Westfalen__
GM08_414_414_state_land___Rheinland-Pfalz__
GM09_414_414_state_land___Saarland__
GM10_414_414_state_land___Schleswig-Holstein__
GM11_414_414_state_land___Brandenburg__
GM12_414_414_state_land___Mecklenburg-Vorpommern__
GM13_414_414_state_land___Sachsen__
GM14_414_414_state_land___Sachsen-Anhalt__
GM15_414_414_state_land___Thuringen__
GM16_414_414_state_land___Berlin__

All we need is a file with entries like

GM02 BY

or 

GM02_414_414_state_land___Bayern__Bavaria

whatever format your map expects. The task for a workaround is to provide an iso code and get a FIPS code.

If you gave me a hint, where I can find the map code I could try to provide that workaround.

That's what we can do now in V3 and an iso based solution can be done without haste for V4.

**Comment by sgiehl** [comment] 2019-11-13 10:43
The problem is, that there is no exact mapping from ISO to FIPS code. 
You can find a mapping from FIPS to ISO here: https://github.com/matomo-org/matomo/blob/3.x-dev/plugins/GeoIp2/data/regionMapping.php

But it's not possible to invert the mapping for most of the countries. But it should be possible for Germany

**Comment by sgiehl** [comment] 2019-12-09 12:45
Most regions should be shown correctly again with next release.
Closing this one in favor of #11929, as new maps should fix that finally

**Closed by sgiehl** 2019-12-09 12:45 UTC
Labels: Bug, Major
