### ISSUE TITLE
Cyrillic url are handled incorrectly

### ISSUE THREAD

**Issue by nagulka** [matomo-org/matomo#15829] opened 2020-04-19 13:47 UTC
Hi,
Cyrillic url are handled incorrectly. You can see the log. You can see that in the log snippet
![matomo-error](https://user-images.githubusercontent.com/37404910/79689408-f48d8300-8254-11ea-97a0-7360774d136d.PNG)

**Comment by sgiehl** [comment] 2020-04-19 19:35
@nagulka could you paste the url or at least the part here in the issue that causes the problem?
This might be fixed with #15618 in Matomo 4

**Comment by nagulka** [comment] 2020-04-20 05:11
all Cyrillic parts of a URL, they have for example a cyrillic letter "с" or "я" cause the error and ignored from matomo.

The paths for example:
/наследие
/пять

You can see that, if you open the log file with the notepad++ (format UTF8)

**Comment by sgiehl** [comment] 2020-04-20 08:06
Tried tracking an url containing your examples locally and it worked correctly. 
Might be an issue of database collation. Could you check which collation your database and the table `matomo_log_action` has on your install?

**Comment by nagulka** [comment] 2020-04-20 09:02
The collation of the database (MariaDB) is utf8_general_ci, of the table matomo_log_action also utf8_general_ci. The database is auto created while matomo installation.

**Comment by nagulka** [comment] 2020-04-23 13:42
Were you able to reproduce the error?
I think that cannot be due to the collation of the database, because "Action name" is entered in the table "matomo_log_action" without any problems (even if the string contains the cyrillic letters "с" or "я"). But the "Action URL" cause the error as soon as the url contains cyrillic letters "с" or "я". I think the URL was previously converted to the wrong format (bevor the inserting in the database).

I use Matomo 3.13.4
Windows Server 2019
IIS 10
PHP-7.4.4

I am always available for additional information. Thanks.

**Comment by sgiehl** [comment] 2020-04-24 06:54
Actually I was not able to reproduce when I send those chars in the URL. Are you able to find those requests to matomo.php in the access log? Maybe they are already sent malformed

**Comment by mattab** [comment] 2023-12-11 17:40
Thanks for contributing to this issue. As it has been a few months since the last activity and we believe this is likely not an issue anymore, we will now close this. If that's not the case, please do feel free to either reopen this issue or [open a new one](https://developer.matomo.org/guides/core-team-workflow#submitting-a-bug-report). We will gladly take a look again!

Also this might help: https://matomo.org/faq/how-to-update/how-to-convert-the-database-to-utf8mb4-charset/

**Closed by mattab** 2023-12-11 17:40 UTC
Labels: c: i18n
