### ISSUE TITLE
Campaign URL Builder: Campaign ID field is missing in the app

### ISSUE THREAD

**Issue by KarthikRaja1388** [matomo-org/matomo#16233] opened 2020-07-22 04:32 UTC
Campaign ID filed can be found in [https://matomo.org/docs/tracking-campaigns-url-builder/](https://matomo.org/docs/tracking-campaigns-url-builder/) but it is not available when accessing from Matomo and this can be viewed from our [demo](https://demo.matomo.org/index.php?module=CoreHome&action=index&date=today&period=week&idSite=62#?idSite=62&period=week&date=today&segment=&category=Referrers_Referrers&subcategory=Referrers_URLCampaignBuilder) and same can be reproduced in Cloud and On-Premise.

**Comment by sgiehl** [comment] 2020-07-22 07:34
@KarthikRaja1388 That's a duplicate of https://github.com/matomo-org/plugin-MarketingCampaignsReporting/issues/40
And there is already https://github.com/matomo-org/plugin-MarketingCampaignsReporting/pull/41 to fix that

**Comment by tsteur** [comment] 2020-07-22 21:51
@sgiehl I think this issue is purely about the campaign builder? I'll reopen it for now as it's not present there.

**Comment by dankerizer** [comment] 2020-10-26 13:59
@KarthikRaja1388 you can activated plugin "MarketingCampaignsReporting "

CLick on Cog icon
click on “Plugins” in the left menu,

**Closed** 2020-12-13 19:57 UTC
Labels: Enhancement, Help wanted
