### ISSUE TITLE
Suggestion: console for invalidating invalidate-report-data should take segment id as a parameter

### ISSUE THREAD

**Issue by mikkeschiren** [matomo-org/matomo#15734] opened 2020-03-26 09:15 UTC
I think it would help a lot if the console command for invalidating report data would take the segment id, as an option.

So instead of:
`/console core:invalidate-report-data --segment='eventCategory=@StringFoo;visitIp!=127.0.0.1'`

We could have:
`/console core:invalidate-report-data --segment-id=2`

Also makes sense when the core:archive command takes the segment-id as a parameter, a.k.a:
`./console core:archive --force-idsegments=2`

If this is a good idea, I could look into it and do a pull request. For non breaking changes we could keep the segment definition option still.

**Comment by tsteur** [comment] 2020-03-26 19:01
Thanks for creating the issue @mikkeschiren This is a duplicate of https://github.com/matomo-org/matomo/issues/14763 Be great to follow that issue

**Closed by tsteur** 2020-03-26 19:01 UTC
