### ISSUE TITLE
Matomo two unique visitor recorded for a single user for visit and events separately

### ISSUE THREAD

**Issue by prazserendio** [matomo-org/matomo#15631] opened 2020-02-28 05:21 UTC
I am using **Matomo tracking code** and **Tag manager** in a same web page (.html file), I get the visitor log of single user as two unique visitor entries like - page Visit and Events, instead of recording under single unique visitor.

I have up the tags like this :

```
<head>
<tag-manager code>
...........
...........
<tracking -code>
</head>
```

**Screenshot :**
![cDs2S](https://user-images.githubusercontent.com/51264444/75512620-0fdbcf00-5a18-11ea-839e-d3dd95321029.jpg)

Note : I have Updated matomo version - 3.13.3 to latest (Got this issue in old and latest version too)

Have anyone faced this issue?

Thanks in Advance!

**Comment by tsteur** [comment] 2020-02-28 05:43
@prazserendio could you ask this question in our forum please? https://forum.matomo.org/

We're only handling bugs/feature requests here but not implementation help. Sorry about that.

You will want to provide a few more details if possible like if you have embedded the Matomo Tag or a Matomo Variable in your Tag Manager container. If so, you will want to disable the feature "Bundle tracker" in the Matomo Configuration Variable.

![image](https://user-images.githubusercontent.com/273120/75513532-01160c00-5a5a-11ea-81d0-2a8bd73991f9.png)

If you can provide a link to your site that'll be even more helpful so people can debug the issue if needed. 

If it turns out there's a bug we'll happy to reopen this issue. Sorry about closing it for now. Hope you understand.

**Closed by tsteur** 2020-02-28 05:43 UTC

**Comment by prazserendio** [comment] 2020-02-28 06:06
Its a kind of bug only and I have also posted the same in the forum [https://forum.matomo.org/t/matomo-two-unique-visitor-recorded-for-a-single-user-for-visit-and-events-separately/36267](https://forum.matomo.org/t/matomo-two-unique-visitor-recorded-for-a-single-user-for-visit-and-events-separately/36267) 

No hope!

**Comment by tsteur** [comment] 2020-02-28 06:16
@prazserendio I recommend you give more details in the forum otherwise it's not possible to say what the issue could be. It sounds like a misconfiguration but we'd need more details and ideally even a link to a URL to reproduce this issue.

**Comment by prazserendio** [comment] 2020-02-28 06:43
Hello @tsteur,

I have added two pieces of code to my website :
1. Matomo Javascript code
2. Matomo Tag Manager code (1 Variable & 3 Triggers)

Position of the tracking code places on the html file :
```
<head>
<tag-manager code>
...........
...........
<tracking-code>
</head>
```
Usually when a user visits the page their **Visit Actions and Events** should come under a single user like :

![image (2)](https://user-images.githubusercontent.com/51264444/75516583-d5c3fa80-5a22-11ea-9c0b-0533a92e1a1b.png)
But in my case there are two separate unique users entry created for Visit Action and Events respectively for a single user click a page :

![cDs2S](https://user-images.githubusercontent.com/51264444/75516673-01df7b80-5a23-11ea-976e-c54ac45de6a8.jpg)

The problem is Matomo captures the visit actions under a user and events under another user.

**Comment by prazserendio** [comment] 2020-02-28 07:04
> @prazserendio I recommend you give more details in the forum otherwise it's not possible to say what the issue could be. It sounds like a misconfiguration but we'd need more details and ideally even a link to a URL to reproduce this issue.

I have given more information and replied the same in the Matomo forum as well.
