### ISSUE TITLE
Segment pages on tags

### ISSUE THREAD

**Issue by rjxp** [matomo-org/matomo#15594] opened 2020-02-19 16:20 UTC
My question is not primarily a question regarding the Matomo Tag Manager (just because the word Tag occurs here), it concerns the segmentation of pages.

My website has K pages (approx. 300'000). There are L keywords (approx. 30'000). Each page can contain M>0 different tags (about 2-10); each tag is on N>0 pages (a few tags are on many pages, but many tags have only a few pages). Comparable to recipes (pages), which are tagged with ingredients (tags).

  I want to see the hitlist for a specific tag, i.e. the pages with the best accesses for a specific tag. In the example: Which cooking recipes that contain a carrot as an ingredient are most viewed/has the most visitors, the longest time spent, etc.pp.? But also questions like: Is there perhaps a tag with few pages but many accesses?  Or: Is there an ingredient that is used in many recipes, but these recipes have relatively few accesses?

In Matomo I get under BEHAVIOUR/PAGES or BEHAVIOUR/PAGE TITLE a hit list of my pages (the best recipes). I expected to be able to filter this list with segments for a certain tag. I tried with Matomo Events (every tag on a page fires an Matomo Event), with Matomo Customer Variables (all tags concatenated as value in a Matomo Customer Variable) and via Matomo Content Tracking (Matomo Tag Impression/Tag Interaction for each tag on a page).

All my attempts (Events/Custom Variable/Content Tracking) to segment pages to a certain tag, segment sessions and not pages. So in the example: A visitor first looked at a recipe for an apple pie and then a recipe for a carrot pie. If I segment my pages in Matomo to the tag "carrot" (IS="carrot" or CONTAINS="carrot"), I also get the apple pie displayed (where there is no carrot as an ingredient/tag).

The Matomo Tag Manager is a massive beast and at least it doesn't catch my eye how I can measure my M-to-N ratio with it? I can think of Matomo Triggers and Matomo Variables, but how do I get a hit list of my pages for a certain tag at the end? For me it looks like I have to get along with the Matomo Tag Manager at the end with Matomo Events, Matomo Customer Variable or Matomo Content Tracking, too?

Am I doing something totally wrong? Is the request too esoteric? Is it possible to change the segmentation of sessions to pages? Or is it just not possible w/Matomo?

**Comment by Findus23** [comment] 2020-02-19 16:42
I don't know segments that well, but I think your idea goes in a similar direction as https://github.com/matomo-org/matomo/issues/15438 and the linked issues.

**Comment by tsteur** [comment] 2020-02-19 19:03
@rjxp this is indeed a duplicate of https://github.com/matomo-org/matomo/issues/15438 

There are workarounds to get this behaviour see https://github.com/matomo-org/matomo/issues/15130#issuecomment-551252343

**Closed by tsteur** 2020-02-19 19:03 UTC
