### ISSUE TITLE
Add quickselect for today, yesterday (,last week, last month)

### ISSUE THREAD

**Issue by fdellwing** [matomo-org/matomo#13817] opened 2018-12-10 08:42 UTC
It would be nice to have a quickselect for the most common dates in the datepicker on all sites and dashboard.

I propose: today, yesterday, last week, last month

**Comment by tsteur** [comment] 2018-12-10 18:18
@fdellwing this is a duplicate of https://github.com/matomo-org/matomo/issues/13707 and I think there's also another issue.

**Closed by tsteur** 2018-12-10 18:18 UTC
Labels: duplicate
