### ISSUE TITLE
Scheduler GeoIP2AutoUpdate gives warning

### ISSUE THREAD

**Issue by sju10544** [matomo-org/matomo#14258] opened 2019-03-23 20:51 UTC
Hi all,

after having a look at the "piwik-archive.log" because the Maxminddb is not updating successfull I got this:

GeoIP2AutoUpdater: successfully downloaded 'https://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz'
WARNING [2019-03-23 20:15:34] 23435  xxx/htdocs/piwik/plugins/Monolog/Processor/SprintfProcessor.php(24): Warning - vsprintf(): Too few arguments - Matomo 3.9.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already)

The downloaded file is "GeoIP2-City.mmdb.tar.gz" and has only 6KB...
The URL for downloading the file is: https://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz

Any ideas?

**Comment by sgiehl** [comment] 2019-03-24 10:40
> WARNING [2019-03-23 20:15:34] 23435 xxx/htdocs/piwik/plugins/Monolog/Processor/SprintfProcessor.php(24): Warning - vsprintf(): Too few arguments - Matomo 3.9.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already)

Found the reason for this one. Will propose a PR for it.

**Comment by sju10544** [comment] 2019-03-24 13:21
Hmmm... sorry but after manually made the changes in the file and run
./console core:run-scheduled-tasks --force
I got the same error messages and behaviour.

**Comment by mattab** [comment] 2019-06-29 12:37
@sgiehl could you check @sju10544 comment, maybe the issue is not fixed?

**Comment by SystemZ** [comment] 2019-10-05 15:48
This problem is present in `3.12.0-b4`

```
INFO [2019-10-05 15:41:14] 14  ---------------------------
INFO [2019-10-05 15:41:14] 14  SCHEDULED TASKS
INFO [2019-10-05 15:41:14] 14  Starting Scheduled tasks... 
INFO [2019-10-05 15:41:14] 14  Scheduler: executing task Piwik\Plugins\GeoIp2\GeoIP2AutoUpdater.update...
INFO [2019-10-05 15:41:14] 14  GeoIP2AutoUpdater: successfully downloaded 'https://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz'
WARNING [2019-10-05 15:41:14] 14  /var/www/html/piwik/plugins/Monolog/Processor/SprintfProcessor.php(24): Warning - vsprintf(): Too few arguments - Matomo 3.12.0-b4 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already)
INFO [2019-10-05 15:41:14] 14  Scheduler: finished. Time elapsed: 0.088s
INFO [2019-10-05 15:41:14] 14  done
INFO [2019-10-05 15:41:14] 14  ---------------------------
```

**Comment by tsteur** [comment] 2019-10-06 19:00
Cheked the translations and logs that use %s after `successfully downloaded '%s'"` around GeoIP updating but couldn't really find the string. Maybe someone else can have a look too? Guess it could be still from a different task

**Comment by mattab** [comment] 2019-12-24 00:59
we'll probably stop using Maxmind soon, so closing this issue now, see #15308

**Closed by mattab** 2019-12-24 00:59 UTC
Labels: Bug
