### ISSUE TITLE
Another 500 error bug in regards to Live data

### ISSUE THREAD

**Issue by Power2All** [matomo-org/matomo#12033] opened 2017-09-12 08:53 UTC
Found another issue after upgrade, looks like a twig issue.

![image](https://user-images.githubusercontent.com/2010549/30316782-92e8f006-97a8-11e7-8c9b-7fc5ed2e2271.png)

**Comment by sgiehl** [comment] 2017-09-12 09:06
That does not seem to be a twig problem. The visitor data provided for rendering seems to be incorrect. Could you try to open this url and check if the response contains an error:
`method=Live.getLastVisitsDetails&idSite=1&filter_limit=10&format=php&serialize=0&disable_generic_filters=1`  (you may need to adjust the `idSite` param)

**Comment by Power2All** [comment] 2017-09-12 09:29
Bug found.
Seems something changed with the upgrade process, and MySQL is not properly updated:

{result: "error",…}
message
:
"Mysqli prepare error: Unknown column 'log_link_visit_action.idpageview' in 'field list'"
result
:
"error"

**Comment by sgiehl** [comment] 2017-09-12 10:34
Could you please paste the result of this query:
```mysql
SELECT option_value FROM piwik_option WHERE option_name = 'version_log_link_visit_action.idpageview';
```

**Comment by Power2All** [comment] 2017-09-12 11:38
![image](https://user-images.githubusercontent.com/2010549/30323985-a06371ae-97bf-11e7-8743-ddf3f588b366.png)

**Comment by sgiehl** [comment] 2017-09-12 12:49
Could you check if this file exists on your Piwik:
`piwik/plugins/Actions/Columns/IdPageview.php`

**Comment by Power2All** [comment] 2017-09-12 13:21
-rw-r--r-- 1 09-webstats www-data 896 Sep 12 10:17 plugins/Actions/Columns/IdPageview.php

**Comment by sgiehl** [comment] 2017-09-12 18:51
You can run the SQL `DELETE FROM piwik_option WHERE option_name = 'version_log_link_visit_action.idpageview';`
Afterwards Piwik should automatically create the missing coulmn when you open it.

**Comment by tsteur** [comment] 2017-09-12 18:53
@Power2All do you remember from which Piwik version you updated?

**Comment by tsteur** [comment] 2017-09-12 19:06
@sgiehl we are getting similar error on demo.piwik.org on an ecommerce website (Marketplace)


A fatal error occurred

The following error just broke Piwik (v3.1.0-rc1):

Key "icon" for array with keys "type, url, pageTitle, pageIdAction, idpageview, serverTimePretty, timeSpentRef, pageId, contentName, contentPiece, contentTarget, contentInteraction, interactionPosition, timestamp" does not exist.
in
/storage/piwik-demo/www/demo.piwik.org/plugins/Live/templates/getLastVisitsStart.twig line 148

**Comment by sgiehl** [comment] 2017-09-12 19:53
guess that is caused by content actions. Seems I missed to have them correctly handled in real time widget

**Comment by Power2All** [comment] 2017-09-13 10:32
> You can run the SQL DELETE FROM piwik_option WHERE option_name = 'version_log_link_visit_action.idpageview';
Afterwards Piwik should automatically create the missing coulmn when you open it.

When I did this, it came finally with a "update your database" when accessing piwik again.
After the upgrade, it still showed the above red text error, but when it parsed some stuff, it started to work again.
So far now it looks good.

**Comment by sgiehl** [comment] 2017-09-13 15:59
> @Power2All do you remember from which Piwik version you updated?

**Comment by sgiehl** [comment] 2017-09-21 08:27
No. This is unrelated to the last release. Sure, the error now pops up, as the `idpageview` column is now used. But it should have been created in an update before. Not sure why I wasn't.

**Comment by mattab** [comment] 2017-09-21 09:11
Might be duplicate of https://github.com/piwik/piwik/issues/11981 and probably other issues

**Comment by mattab** [comment] 2018-06-26 21:52
this should be fixed, if you still experience this please open a new issue.

**Closed by mattab** 2018-06-26 21:52 UTC
