### ISSUE TITLE
import_logs.py not using STDIN anymore

### ISSUE THREAD

**Issue by jdelker** [matomo-org/matomo#16338] opened 2020-08-23 14:33 UTC
After upgrading to matomo 3.14, I noticed that our Apache-Log processing pipeline in logstash was not working anymore.

In there, logs are piped through STDIN into `import_logs.py` for processing, by invoking it as `import_logs.py ... -`.
After the upgrade the logstash pipeline is collapsing immediately after invokation.

Analysis showed, that STDIN processing is obviously not working anymore:
`import_logs.py ... apache.log` works fine.
`import_logs.py ... - < apache.log` terminates immediately with no lines parsed.

**Comment by tsteur** [comment] 2020-08-23 19:58
Hi @jdelker  I think this is a duplicate of https://github.com/matomo-org/matomo-log-analytics/issues/273 . Let me know if that's not the case and I'll reopen the issue. It was fixed in https://github.com/matomo-org/matomo-log-analytics/pull/275

**Closed by tsteur** 2020-08-23 19:58 UTC

**Comment by jdelker** [comment] 2020-08-23 20:20
Yes, that fixes the issue.
Sorry for the duplicate, but somehow I didn't find the referenced issue beforehand.
