### ISSUE TITLE
Provide statistics on devicePixelRatio (for Retina / high DPI / smartphone displays)

### ISSUE THREAD

**Issue by johsin18** [matomo-org/matomo#12392] opened 2017-12-31 17:24 UTC
In addition to the Screen Resolution statistics, provide statistics on the value of devicePixelRatio, giving an indication of how "sharp" the visitors' displays are. This applies in particular to Retina / high DPI / smartphone displays. Using these stats, one can assess how rewarding it would be to provide high resolution images.

As the value of devicePixelRatio is an arbitrary decimal, maybe use ranges, e.g. 1<x<=1.5, 1.5<x<=2, 2<x<=3, 3<x<=4, , and so on. The current Page zoom also influences the devicePixelRatio, but this means that the user would like to see more or less detail, so it's actually nice to include that.

This improvement was also suggested at the very end of:
https://github.com/piwik/piwik/issues/4663

**Comment by Findus23** [comment] 2017-12-31 17:26
It should be pretty easy to write a plugin which does this report. 
One could simply modify this existing plugin:
https://github.com/sgiehl/piwik-plugin-DeviceFeatureWebGL

**Comment by johsin18** [comment] 2018-01-02 18:01
In contrast to the WebGL plugin, it's not just adding one more entry to an existing report, but rather adding a completely new report.

**Comment by wasinger** [comment] 2018-07-17 12:48
This seems to be a duplicate of #11405.

**Comment by johsin18** [comment] 2018-07-17 13:01
True.  BTW I'm currently implementing a plugin.

**Comment by sgiehl** [comment] 2018-07-17 16:17
I'm closing this in favor of #11405

**Closed by sgiehl** 2018-07-17 16:17 UTC

**Comment by johsin18** [comment] 2018-08-09 11:04
My "Device Pixel Ratio" plugin has hit the marketplace, so this problem is solved.
