### ISSUE TITLE
Update message creates empty space in admin and pushes widgets down

### ISSUE THREAD

**Issue by VincentCouzij** [matomo-org/matomo#14623] opened 2019-07-04 07:37 UTC
Hi,

The update message in the Matomo admin creates a large empty space and pushes all the widgets down. Example: ![https://imgur.com/a/tSfZyyf](https://i.imgur.com/e0rS49q.png)

**Comment by tsteur** [comment] 2019-07-04 11:41
Can't reproduce this here. Maybe doesn't happen with Matomo 3.10 anymore? Are you using any 3rd party plugins (plugins neither from Matomo nor InnoCraft (premium features))?

**Comment by VincentCouzij** [comment] 2019-07-04 11:52
The only plugin we are using is QueuedTracking. I am planning to update our install to 3.10 but I won't be able to check if it is fixed until a new version is released. If I look at the html the secondNavBar is wrapped in `<a rel="noreferrer noopener" href="https://builds.matomo.org/piwik-3.10.0.zip">` 

If I remove the wrapping `rel="noreferrer noopener" href="https://builds.matomo.org/piwik-3.10.0.zip">... </a>` the page displays like normal

**Comment by tsteur** [comment] 2019-07-18 02:50
@mattab you moved this into 3.11. Can you reproduce this? I can't... neither Chrome nor Firefox.

@VincentCouzij which browser is that?

**Comment by VincentCouzij** [comment] 2019-07-18 09:05
That is the newest version of Chrome on macOS 10.14.5 But I get this on every browser I try (Chrome, Safari, Firefox)

**Comment by tsteur** [comment] 2019-07-18 20:38
@VincentCouzij was testing this under latest macOS as well. Can't reproduce unfortunately. If someone else can, that be great to know.

**Comment by mattab** [comment] 2019-08-09 02:20
Thanks for reporting this issue. 
Unfortunately we're unable to reproduce the problem. 
**If anyone is reading this and has seen this behaviour, please leave a comment and a screenshot (and ideally how you managed to reproduce).**
If we don't hear more about this issue, we will close it later. Thanks!

**Comment by peterbo** [comment] 2019-10-24 22:55
Duplicate of https://github.com/matomo-org/matomo/issues/15045, fixed in https://github.com/matomo-org/matomo/issues/15047

**Comment by VincentCouzij** [comment] 2019-11-01 08:12
I will test the 3.12.0 release and will be report my findings when a version after that gets released.

**Comment by sgiehl** [comment] 2019-11-03 15:25
@VincentCouzij I'll close this one, as it should be fixed. Feel free to reopen if not.

**Closed by sgiehl** 2019-11-03 15:25 UTC
Labels: Bug, Waiting for user feedback / Cannot reproduce yet
