### ISSUE TITLE
File integrity check  vendor/davaxi/sparkline

### ISSUE THREAD

**Issue by gatokichi** [matomo-org/matomo#13318] opened 2018-08-20 02:36 UTC
What is the inconsistency displayed every time when checking the system after updating Matomo?
The same files are displayed as inconsistent even though it is being deleted each time.

---
 File integrity check failed and reported some errors. You should fix this issue and then refresh this page until it shows no error.

Files were found in your Matomo but we didn't expect them.
--> Please delete these files to prevent errors. <--

File to delete: vendor/davaxi/sparkline/autoload.php
File to delete: vendor/davaxi/sparkline/src/autoload.php
File to delete: vendor/piwik/device-detector/autoload.php
---

**Comment by mattab** [comment] 2018-09-01 22:44
Thank you for the report and sorry that we missed this during RC cycle. Marking as duplicate of https://github.com/matomo-org/matomo/issues/13364

**Closed by mattab** 2018-09-01 22:44 UTC
Labels: Regression
