### ISSUE TITLE
Segment causes inconsistent average time on page

### ISSUE THREAD

**Issue by anonymous-matomo-user** [matomo-org/matomo#4719] opened 2014-02-19 15:27 UTC
There seems to be an issue, when I create a segment so that only the page-titles of pages that contain a certain string inside the URL (for example pageUrl="_/cms/_" ) are displayed: 
The segment works, but it seems to affect the "avg. time on page" values in a strange way. 
For example: 
A certain Page shows without segment about 22min time on page and with segment it show about 46 seconds (see screenshots). All the other metics seem to be identical, though.

**Comment by mattab** [comment] 2024-01-16 21:42
Thanks for contributing to this issue. As it has been a few months since the last activity and we believe this is likely not an issue anymore, we will now close this. If that's not the case, please do feel free to either reopen this issue or [open a new one](https://developer.matomo.org/guides/core-team-workflow#submitting-a-bug-report). We will gladly take a look again!

**Closed by mattab** 2024-01-16 21:42 UTC
Labels: Bug

**Comment by atom-box** [comment] 2024-05-28 19:40
_There might have been a regression. Average time on page, for a segment, seems broken in Matomo 5. See the user's comment and screenshots here:_

"Why is the "average time on page" different for a Page URL for "All Visits" and for a segment where only the action URL is filtered? Surely that should be the same?"

All Visits:
![image](https://github.com/matomo-org/matomo/assets/22874146/dca20fe3-8034-4a49-b2c2-2f53bfe73653)

Same URL but as a Segment
![image](https://github.com/matomo-org/matomo/assets/22874146/9ad4b47b-3753-4130-86f9-a487e742ec1e)
![image](https://github.com/matomo-org/matomo/assets/22874146/3c8857ec-7021-41cd-82c5-6d7c6c022fe1)

**Comment by atom-box** [comment] 2024-06-05 16:20
I cannot reproduce this issue.

Matomo Cloud seems fine: 

![image](https://github.com/matomo-org/matomo/assets/22874146/5b698c57-532c-4874-bddc-c16135acdf78)

**Comment by PeteTrombone** [comment] 2024-06-06 11:11
We have the problem with the segments.

**Comment by sgiehl** [comment] 2024-06-06 13:02
@PeteTrombone are you already using Matomo 5?

**Comment by PeteTrombone** [comment] 2024-06-07 08:19
@sgiehl yes, 5.0.3

**Comment by sgiehl** [comment] 2024-06-07 08:50
@PeteTrombone Does it happen for all type of segments or only specific segments - like segments on action or visit dimensions only.

**Comment by PeteTrombone** [comment] 2024-06-07 09:32
@sgiehl it is as atom-box described. We only noticed it in segments with the "Action URL".
