### ISSUE TITLE
Allow reenabling cookies

### ISSUE THREAD

**Issue by Findus23** [matomo-org/matomo#13950] opened 2019-01-11 17:04 UTC
Suggested here: https://forum.matomo.org/t/disable-and-enable-cookies/31171

As one can disable cookies it sounds reasonable to provide a way to re-enable cookies (e.g. to disable cookies by default, but allow an opt in)

In theory this should work, but there may be some issues in the details. (e.g. one has to undo the `browserFeatures.cookie = '0';`)
```javascript
this.enableCookies = function () {
    configCookiesDisabled = false;
};
```

**Comment by mattab** [comment] 2020-02-04 04:45
marking as duplicate of https://github.com/matomo-org/matomo/issues/13056

**Closed by mattab** 2020-02-04 04:45 UTC
Labels: Help wanted, c: Privacy
