### ISSUE TITLE
Edge Anaheim is recognized as Chrome

### ISSUE THREAD

**Issue by Studio384** [matomo-org/matomo#14268] opened 2019-03-25 10:33 UTC
The Edge Anaheim browser (the Chromium-based revamp of Edge) is currently being recognized as Chrome instead of Edge. Matomo should be looking for `Edg/` in the UAS.

```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3739.0 Safari/537.36 Edg/75.0.109.0
```

**Comment by Findus23** [comment] 2019-03-25 10:34
See https://github.com/matomo-org/device-detector/pull/5943 for a fix

**Comment by fdellwing** [comment] 2019-03-25 11:01
Did they really cut the `e` from `Edge` to try to fly under the name of Chrome again? -.-

**Comment by nickurt** [comment] 2019-03-25 11:07
Yes, and I think its by design, all the current checks for Edge (Spartan) don't work for the new Edge (Anaheim), fwiw Edge for Android is internally called EdgA and for iOS its EdgiOS ..

**Comment by Findus23** [comment] 2019-05-06 06:44
This has been merged in the meantime

**Closed by Findus23** 2019-05-06 06:44 UTC
