### ISSUE TITLE
Segment filter countries incomplete

### ISSUE THREAD

**Issue by ingoratsdorf** [matomo-org/matomo#15756] opened 2020-03-31 07:34 UTC
Adding a new segment filter, trying to filter for "Country".
When I try to filter for country "New Zealand", there is none. There's also no "New Caledonia" and actually my alphabetically sorted dropdown list ends at "Hungary". What happend with anything after "Hungary"?

![Country Filter List](https://user-images.githubusercontent.com/3344778/77999154-b8ba7880-738e-11ea-8067-5f85859fe5dd.png)
![New Zealand Search](https://user-images.githubusercontent.com/3344778/77999157-b9eba580-738e-11ea-8f51-186ecffa66ed.png)

**Comment by tsteur** [comment] 2020-03-31 07:45
Hi there, this is a duplicate of https://github.com/matomo-org/matomo/issues/15620

**Closed by tsteur** 2020-03-31 07:45 UTC
