### ISSUE TITLE
SQLSTATE[42000]: Syntax error or access violation: 1064

### ISSUE THREAD

**Issue by ybzhaoplus** [matomo-org/matomo#12784] opened 2018-04-29 03:27 UTC
My environment:
php 7.2.5
mysql: 8.0.11
matomo: 3.4.0

Here is the error: after I imported old data to newly installed MySQL 8.0.11

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '. piwik_log_visit' at line 1

**Comment by mj** [comment] 2018-05-02 09:51
This appears to be a duplicate of #12759.

**Comment by chauffer** [comment] 2018-05-02 14:28
Thanks for finding that @mj!

**Comment by Findus23** [comment] 2018-10-25 17:03
Fixed by #12759 and released in 3.5.0

**Closed by Findus23** 2018-10-25 17:03 UTC
