### ISSUE TITLE
HTML email reports: Links to Piwik and Icons not working on HTTPS (IP address used instead of hostname)

### ISSUE THREAD

**Issue by nkuehn** [matomo-org/matomo#5250] opened 2014-05-27 13:30 UTC
Hi, 

the HTML generated by the excellent Piwik email report generator contains References to the Piwik installation (e.g. some Icons and a Link to the Piwik installation). 

On our HTTPS-Only accessible Piwik installation these URLs cannot be resolved because the URLs use the IP address of the Piwik instance instead of a valid hostname and the SSL certificate is only valid for the Hostname. 

Should be resolvable easily because you have to configure the "Trusted Piwik Hostname" anyways in the Settings section (also for security reasons).  I suppose the Path part of the Links is handled somehow (can't test that because my piwik is running in the root folder). 

Keywords: email HTML

**Comment by mattab** [comment] 2015-04-08 07:03
let's investigate this issue as part of the broader set of bugs in #6880  -> our goal will be to make Piwik work perfectly in this special use case which many users have reported issues with.

**Comment by mattab** [comment] 2017-09-14 23:31
Hi @nkuehn - do you still experience this issue in Piwik 3.1.0 ?

**Comment by nkuehn** [comment] 2017-09-19 12:07
Hi @mattab I am working in a different company for a while already and don't have an up to date setup available any more (and have no status and access to the one that we experienced this issue in).  Sorry to say I can't help you out at the moment (don't have the spare private time any more too unfortunately). 

If nobody else has come up with the issue since 2014 I personally would consider it irrelevant no matter if fixed or not. 

But in any case I can recommend to test solely via an SSL-terminating reverse proxy and do not give the test runner direct access to the PHP IP / Host at all.

**Comment by krispii** [comment] 2017-10-02 13:52
@mattab Are you forwarding from NGINX using `localhost:someport`?

I ask because we had this issue when I used `proxy_pass http://localhost:someport` but identifying the virtual host `proxy_pass http://somepiwik.somedomain.tld:someport` fixed the HTML email reports.

**Comment by nkuehn** [comment] 2017-10-02 14:35
@krispii  that could well be the reason but is a weird setup - you "hide" behind a reverse proxy to _not_  make the internal URL / IP / Hostname accessible to the outside - proxying to the public external hostname is not the point of a proxy - you want to decouple internal deployment from external URL.

**Comment by mattab** [comment] 2017-11-19 23:45
This might be a duplicate of https://github.com/piwik/piwik/issues/11545 but need to check. We'll try to fix it soon

**Comment by tsteur** [comment] 2018-09-19 02:36
Maybe this was fixed in https://github.com/matomo-org/matomo/pull/13122 ?

**Comment by mattab** [comment] 2018-10-05 02:51
Please reopen if you still experience the issue with the latest Matomo @nkuehn

**Closed by mattab** 2018-10-05 02:51 UTC
Labels: Bug

**Comment by nkuehn** [comment] 2018-10-05 07:07
+1  - I don't even have a working installation any more so it's fair to assume if nobody else has the issue it does not exist any more.
