### ISSUE TITLE
Track how many visitors use/set "do not track" and "opt out"

### ISSUE THREAD

**Issue by hpvd** [matomo-org/matomo#8200] opened 2015-06-24 10:22 UTC
Would be very helpful for good statistics to have the amount of visitors
- whoes browser send "do not track"
- how many users actively use the "opt out"

**Comment by tsteur** [comment] 2015-06-25 21:53
:+1:

**Comment by gaumondp** [comment] 2015-06-26 12:55
Like the idea too, even if it looks weird to track people saying "DNT" to us...
:)

We have to make sure that this data is always anonymised and add a note about it in #6196  (PRIVACY.md)

**Comment by JohnMaguire** [comment] 2015-12-06 19:22
:+1:

Google tracks users with "Do Not Track" by default, however you can disable it, and you can also track, while disabled, how many visitors had DNT enabled. (see http://www.outfox.com/do-not-track-for-google-analytics/)

From reading the donnottrack.us website, it sounds like Piwik might theoretically be compliant with Do Not Track (even while tracking visitors) so long as it's not tracking cross-domain: http://donottrack.us/cookbook/

I wonder if Do Not Track support should actually be disabled by default in this case?

**Comment by rubo77** [comment] 2018-07-03 09:20
I think this is a very important request:

If you install matamo on your website to get a reasonable statistic about your visitors. It is pure nonsense not to count those users with a "do-not-track" mark.

Instead those users should be counted anonymously without IP and without any information about the user. Just a counter, that there was someone on the page.

**Comment by mattab** [comment] 2019-07-01 09:48
Thanks for the suggestion. Marking as duplicate of https://github.com/matomo-org/matomo/issues/12001

**Closed by mattab** 2019-07-01 09:48 UTC
Labels: Enhancement
