### ISSUE TITLE
weird behavior of pager in 'browsers' list widget

### ISSUE THREAD

**Issue by mpaolo** [matomo-org/matomo#11591] opened 2017-04-05 09:07 UTC
3.0.3 here, just updated. 
On a site the 'browsers' widget counts 6 items, at bottom the pager shows: " 1-6 of 6  Next ›" with 'next' as active link.
Click 'next' yields " ‹ Previous   0-6 of 6  Next › "
Click 'next' again yields " ‹ Previous   -1-6 of 6  Next › "
and so on. i.e. left index limit decreases toward negative, list doesn't change though as the total number of items fits a single page.
Click on 'previous' brings back the initial pager display

**Comment by mpaolo** [comment] 2017-04-05 09:09
I mean, 
- I don't expect prev/next at all if total items fit a page
- I don't expect 'next' to 'page backward' to negative index pages

**Comment by mattab** [comment] 2017-05-08 20:46
Hi @mpaolo 
Unfortunately we can't reproduce this issue. Can you reproduce this on https://demo.piwik.org ?

**Comment by mpaolo** [comment] 2017-05-09 18:22
yep, seems I got the glitch: e.g. for 
virtual-drums.com
2017-05-09
there are 4 browsers as of now. If you select 5,10,... view it's fine, but if you select 'all' you get
 ‹ Previous   0-4 of 4  Next › 
or 'next' only, depends on initial state, then the broken behavior. See also the wrong count when switching view to bro.version from that state

![piwikbrokenbrowidget](https://cloud.githubusercontent.com/assets/15540168/25865985/337d855c-34f5-11e7-9498-55e72e444c18.PNG)

**Comment by mattab** [comment] 2023-12-10 11:48
Thanks for contributing to this issue. As it has been a few months since the last activity and we believe this is likely not an issue anymore, we will now close this. If that's not the case, please do feel free to either reopen this issue or [open a new one](https://developer.matomo.org/guides/core-team-workflow#submitting-a-bug-report). We will gladly take a look again!

**Closed by mattab** 2023-12-10 11:48 UTC
Labels: Bug
