### ISSUE TITLE
Custom plugin directory not working properly on some plugins 

### ISSUE THREAD

**Issue by JugurthaK** [matomo-org/matomo#15340] opened 2020-01-02 09:57 UTC
Hello, 

This issue is related to Issue#14717 ;

When going to premium plugins as ABTesting or SessionRecording on left panel, I've an error referring to a 404 with the following path : `./custom-folder//HeatmapSessionRecording/angularjs`

When we've initialized our custom folder, it was without any "/" at the end, 

Regards,

**Comment by tsteur** [comment] 2020-01-02 19:39
Could you let us know how you configured your Matomo On-Premise re the paths? Be great to know roughly the structure of the Matomo path and the custom plugin path.

Also: Are you using the latest version of Matomo? As we fixed some things there

**Comment by JugurthaK** [comment] 2020-01-03 05:50
Hello

Currently working on 3.13.0 (latest version on Docker Hub); since I'm using the Docker image, my custom path is defined as an envvar. 

The custom directory and the Matomo plugins directory are at the same level, so at the root of Matomo.
Moreover, Funnels is working properly and its on the same folder as AbTesting or HeatMapSession. 

Thank you,

**Comment by tsteur** [comment] 2020-01-03 06:20
It's a bit funny it works with Funnel but not with the other two plugins. I'm using it here with HeatmapSessionRecording and Funnels in a custom plugin dir and it works nicely. 

In case you are familiar with the browser developer tools, in the `console` could you enter `piwik.relativePluginWebDirs` and paste here what the outcome is?

And is `./custom-folder//HeatmapSessionRecording/angularjs` the full resource that is being requested? Is there no JS or HTML file attached in the path? 

I suppose as a result these plugins don't work for you in the Matomo UI?

**Comment by JugurthaK** [comment] 2020-01-03 07:35
> In case you are familiar with the browser developer tools, in the console could you enter piwik.relativePluginWebDirs and paste here what the outcome is?

```JSON
AbTesting: "./additional-plugins/"
ActivityLog: "./additional-plugins/"
Funnels: "./additional-plugins/"
HeatmapSessionRecording: "./additional-plugins/"
LoginSaml: "./additional-plugins/"
QueuedTracking: "./additional-plugins/"
ReferrersManager: "./additional-plugins/"
TasksTimetable: "./additional-plugins/"
UsersFlow: "./additional-plugins/"
```
> And is ./custom-folder//HeatmapSessionRecording/angularjs the full resource that is being requested? Is there no JS or HTML file attached in the path?

There is an HTML file attached,

> I suppose as a result these plugins don't work for you in the Matomo UI?

No they're not unfortunately,

**Comment by tsteur** [comment] 2020-01-06 00:48
So it is trying to load `https://example.com/additional-plugins/AbTesting/angularjs/manage/manage.directive.html`

and `https://example.com/additional-plugins/HeatmapSessionRecording/angularjs/manageSession/manage.directive.html`?

And these return a 404 error. Do you know what the correct URL should be that works? For me everything seems to be working fine so far. Are these plugins basically located in a directory named `additional-plugins` in the Matomo root dir? With other directories like `plugins`, `lang`, `js`, `config` on the same level (which you already mentioned I think but be good to have this double confirmed)?

Because if so, it looks like Matomo generates the correct URL but it might be a webserver issue that these files cannot be found?

**Comment by JugurthaK** [comment] 2020-01-13 07:03
Hello, 

Sorry for the late response (being in apprenticeship isnt easy :( )

> https://example.com/additional-plugins/AbTesting/angularjs/manage/manage.directive.html

In fact, its trying to load https://example.com/additional-plugins*//*AbTesting/angularjs/manage/manage.directive.html

This double slash is f***king up everything. And as I've said, I dont know where it can come from.

**Comment by tsteur** [comment] 2020-01-13 19:17
If the double slash won't solve it, it be great to know what the URL should look like. This way we can better understand what is going wrong.

**Comment by JugurthaK** [comment] 2020-01-22 19:17
Hello guys,

I've checked our nginx config, the .html files are allowed from any source. But I've seen in our logs that sometimes they're requests to the plugins from the classical folder and not the custom one.

I dont think the issue is on your side anymore, if I find how to solve it, I will let you know !

Regards,

**Comment by tsteur** [comment] 2020-01-22 19:21
Awesome, that be really great as it will help when others face this issue. I will close the issue for now but be great if you could still commend about what you find and we can reopen the issue also any time if needed.

**Closed by tsteur** 2020-01-22 19:21 UTC
Labels: Waiting for user feedback / Cannot reproduce yet

**Comment by JugurthaK** [comment] 2020-01-30 15:51
Hello guys,

I'm a man of word, so i've finally found the issue. Our matomo is not in the same container as our nginx, and the nginx container had a additional-plugins folder, but it was empty..

To solve it, I've just binded the volume containing the custom plugins to Matomo and Nginx and its working properly.

Regards,

**Comment by tsteur** [comment] 2020-01-30 18:52
Awesome @JugurthaK Thanks a lot for making the effort to letting us know. Very appreciated 👍
