### ISSUE TITLE
"Page URL not defined" message in Visitor Log

### ISSUE THREAD

**Issue by Amenel** [matomo-org/matomo#11257] opened 2017-01-22 18:50 UTC
I have been seeing some "Page URL not defined" in the Visitor Log in the past few versions of Piwik.

I have not been able to identify the reasons why this happens nor the circumstances in which it happens, all the more since the same page may lead to that message and, at other times, yield a "normal" URL (see the attached image).

![image 140](https://cloud.githubusercontent.com/assets/7868710/22184910/9a61875a-e0db-11e6-8fd4-e7d0131fb423.png)

For all page visits for which the URL appears as not defined, the "Visitors in Real-time" widget will show the URL of the current page URL (e.g. "https://analytics.khalemy.com/index.php?module=CoreHome&action=index&idSite=1&period=range&date=last30#") as the URL of the page that has been visited, which is of course totally wrong.

I don't know whether the page protocol (HTTP vs HTTPS) has something to do with the issue or not.

Maybe that it's a configuration issue on my part, but I'm positive that this issue did not present itself earlier, for instance two or four years ago.

**Comment by collinbarrett** [comment] 2017-01-31 17:53
I'm currently trying to debug this myself, and I ran across [this article](https://ajdg.solutions/2015/04/25/using-piwik-stats-but-getting-page-url-not-defined-all-the-time/). All my sites and my Piwik install are only accessible via https, so I am trying to change from protocol-agnostic urls to specifying https as that author recommend. Will see if that helps...

**Comment by collinbarrett** [comment] 2017-02-01 16:26
Update: changing my javascript and image tracker Piwik urls to "https://" instead of just "//" does not (at least fully) resolve it. I still see many "Page URL not defined"s.

**Comment by mattab** [comment] 2017-02-20 16:58
It's possible to find out the cause, and we would love to know as well / fully understand this issue.

In your visitor log for those "Page URL not defined" look at the date & time of those requests. Then look in your web server access log files for the piwik server. Look for lines containing "piwik.php" and containing the same IP address or visitor id that had this page url not defined. What are those log lines? please post them here. we'll investigate and maybe we can make this better

**Comment by collinbarrett** [comment] 2017-02-21 02:16
I'll try to trace this info down per your instructions. It'll probably take me a few days before I have a chance, though. Thanks!

**Comment by collinbarrett** [comment] 2017-02-24 19:35
As an example, I had one visitor that had 72 actions on my site. Of those, about 64 of them show "Page URL not defined" in the Visitor Log. Here's a snapshot of their first five actions:

![image](https://cloud.githubusercontent.com/assets/6483057/23317542/734ebcf0-fa94-11e6-82e2-afa8d53e436f.png)

 I traced the IP address and the exact time of those first five actions to the following nginx log entries. Note that I renamed "piwik.php" to "s.php" for my public site. Also note that I am using the proxy method to hide the url of my Piwik install which is why (I think) there are two records in the log for each action. The last bytes of the IPs are replaced with "0"s. My auth tokens are replaced with "MYTOKEN". I hope I have anonymized this enough... I recognize that my setup is somewhat complex, so it might not be a good use case for debugging. And the issue I am seeing might be due to my complex setup and not Piwik itself.

`
41.35.000.000 - - - BYPASS [24/Feb/2017:12:59:42 -0600] "GET /s.php?ping=1&idsite=3&rec=1&r=933972&h=20&m=59&s=41&url=https%3A%2F%2Ffilterlists.com%2F&urlref=https%3A%2F%2Ffilterlists.com%2F&_id=85aab28741efc426&_idts=1487952165&_idvc=2&_idn=0&_refts=1487962436&_viewts=1487962436&_ref=https%3A%2F%2Fwww.google.com.eg%2F&send_image=1&pdf=1&qt=0&realp=0&wma=0&dir=0&fla=1&java=0&gears=0&ag=0&cookie=1&res=1440x900&gt_ms=3&pv_id=B0iPen HTTP/1.1" 200 54 "https://filterlists.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36" "41.35.000.000"
2604:a880:0:1010::000:0000 - - - - [24/Feb/2017:12:59:42 -0600] "GET /piwik.php?cip=41.35.000.000&token_auth=MYTOKEN&ping=1&idsite=3&rec=1&r=933972&h=20&m=59&s=41&url=https%3A%2F%2Ffilterlists.com%2F&urlref=https%3A%2F%2Ffilterlists.com%2F&_id=85aab28741efc426&_idts=1487952165&_idvc=2&_idn=0&_refts=1487962436&_viewts=1487962436&_ref=https%3A%2F%2Fwww.google.com.eg%2F&send_image=1&pdf=1&qt=0&realp=0&wma=0&dir=0&fla=1&java=0&gears=0&ag=0&cookie=1&res=1440x900&gt_ms=3&pv_id=B0iPen& HTTP/1.1" 200 86 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36" "2604:a880:0000:1010:0000:0000:0000:0000"
41.35.000.000 - - - BYPASS [24/Feb/2017:12:59:37 -0600] "GET /s.php?ping=1&idsite=3&rec=1&r=106076&h=20&m=59&s=36&url=https%3A%2F%2Ffilterlists.com%2F&urlref=https%3A%2F%2Ffilterlists.com%2F&_id=85aab28741efc426&_idts=1487952165&_idvc=2&_idn=0&_refts=1487962436&_viewts=1487962436&_ref=https%3A%2F%2Fwww.google.com.eg%2F&send_image=1&pdf=1&qt=0&realp=0&wma=0&dir=0&fla=1&java=0&gears=0&ag=0&cookie=1&res=1440x900&gt_ms=3&pv_id=B0iPen HTTP/1.1" 200 54 "https://filterlists.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36" "41.35.000.000"
2604:a880:0:1010::000:0000 - - - - [24/Feb/2017:12:59:37 -0600] "GET /piwik.php?cip=41.35.000.000&token_auth=MYTOKEN&ping=1&idsite=3&rec=1&r=106076&h=20&m=59&s=36&url=https%3A%2F%2Ffilterlists.com%2F&urlref=https%3A%2F%2Ffilterlists.com%2F&_id=85aab28741efc426&_idts=1487952165&_idvc=2&_idn=0&_refts=1487962436&_viewts=1487962436&_ref=https%3A%2F%2Fwww.google.com.eg%2F&send_image=1&pdf=1&qt=0&realp=0&wma=0&dir=0&fla=1&java=0&gears=0&ag=0&cookie=1&res=1440x900&gt_ms=3&pv_id=B0iPen& HTTP/1.1" 200 86 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36" "2604:a880:0000:1010:0000:0000:0000:0000"
41.35.000.000 - - - BYPASS [24/Feb/2017:12:59:28 -0600] "GET /s.php?ping=1&idsite=3&rec=1&r=152003&h=20&m=59&s=27&url=https%3A%2F%2Ffilterlists.com%2F&urlref=https%3A%2F%2Ffilterlists.com%2F&_id=85aab28741efc426&_idts=1487952165&_idvc=2&_idn=0&_refts=1487962436&_viewts=1487962436&_ref=https%3A%2F%2Fwww.google.com.eg%2F&send_image=1&pdf=1&qt=0&realp=0&wma=0&dir=0&fla=1&java=0&gears=0&ag=0&cookie=1&res=1440x900&gt_ms=3&pv_id=B0iPen HTTP/1.1" 200 54 "https://filterlists.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36" "41.35.000.000"
2604:a880:0:1010::000:0000 - - - - [24/Feb/2017:12:59:28 -0600] "GET /piwik.php?cip=41.35.000.000&token_auth=MYTOKEN&ping=1&idsite=3&rec=1&r=152003&h=20&m=59&s=27&url=https%3A%2F%2Ffilterlists.com%2F&urlref=https%3A%2F%2Ffilterlists.com%2F&_id=85aab28741efc426&_idts=1487952165&_idvc=2&_idn=0&_refts=1487962436&_viewts=1487962436&_ref=https%3A%2F%2Fwww.google.com.eg%2F&send_image=1&pdf=1&qt=0&realp=0&wma=0&dir=0&fla=1&java=0&gears=0&ag=0&cookie=1&res=1440x900&gt_ms=3&pv_id=B0iPen& HTTP/1.1" 200 86 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36" "2604:a880:0000:1010:0000:0000:0000:0000"
41.35.000.000 - - - BYPASS [24/Feb/2017:12:59:23 -0600] "GET /s.php?ping=1&idsite=3&rec=1&r=620856&h=20&m=59&s=22&url=https%3A%2F%2Ffilterlists.com%2F&urlref=https%3A%2F%2Ffilterlists.com%2F&_id=85aab28741efc426&_idts=1487952165&_idvc=2&_idn=0&_refts=1487962436&_viewts=1487962436&_ref=https%3A%2F%2Fwww.google.com.eg%2F&send_image=1&pdf=1&qt=0&realp=0&wma=0&dir=0&fla=1&java=0&gears=0&ag=0&cookie=1&res=1440x900&gt_ms=3&pv_id=B0iPen HTTP/1.1" 200 54 "https://filterlists.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36" "41.35.000.000"
2604:a880:0:1010::000:0000 - - - - [24/Feb/2017:12:59:23 -0600] "GET /piwik.php?cip=41.35.000.000&token_auth=MYTOKEN&ping=1&idsite=3&rec=1&r=620856&h=20&m=59&s=22&url=https%3A%2F%2Ffilterlists.com%2F&urlref=https%3A%2F%2Ffilterlists.com%2F&_id=85aab28741efc426&_idts=1487952165&_idvc=2&_idn=0&_refts=1487962436&_viewts=1487962436&_ref=https%3A%2F%2Fwww.google.com.eg%2F&send_image=1&pdf=1&qt=0&realp=0&wma=0&dir=0&fla=1&java=0&gears=0&ag=0&cookie=1&res=1440x900&gt_ms=3&pv_id=B0iPen& HTTP/1.1" 200 86 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36" "2604:a880:0000:1010:0000:0000:0000:0000"
41.35.000.000 - - - BYPASS [24/Feb/2017:12:59:18 -0600] "GET /s.php?ping=1&idsite=3&rec=1&r=989997&h=20&m=59&s=17&url=https%3A%2F%2Ffilterlists.com%2F&urlref=https%3A%2F%2Ffilterlists.com%2F&_id=85aab28741efc426&_idts=1487952165&_idvc=2&_idn=0&_refts=1487962436&_viewts=1487962436&_ref=https%3A%2F%2Fwww.google.com.eg%2F&send_image=1&pdf=1&qt=0&realp=0&wma=0&dir=0&fla=1&java=0&gears=0&ag=0&cookie=1&res=1440x900&gt_ms=3&pv_id=B0iPen HTTP/1.1" 200 54 "https://filterlists.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36" "41.35.000.000"
2604:a880:0:1010::000:0000 - - - - [24/Feb/2017:12:59:18 -0600] "GET /piwik.php?cip=41.35.000.000&token_auth=MYTOKEN&ping=1&idsite=3&rec=1&r=989997&h=20&m=59&s=17&url=https%3A%2F%2Ffilterlists.com%2F&urlref=https%3A%2F%2Ffilterlists.com%2F&_id=85aab28741efc426&_idts=1487952165&_idvc=2&_idn=0&_refts=1487962436&_viewts=1487962436&_ref=https%3A%2F%2Fwww.google.com.eg%2F&send_image=1&pdf=1&qt=0&realp=0&wma=0&dir=0&fla=1&java=0&gears=0&ag=0&cookie=1&res=1440x900&gt_ms=3&pv_id=B0iPen& HTTP/1.1" 200 86 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36" "2604:a880:0000:1010:0000:0000:0000:0000"
`

**Comment by mattab** [comment] 2020-06-12 05:32
Thanks for contributing to this issue. As it has been a few months since the last activity and we believe this is likely not an issue anymore, we will now close this. If that's not the case, please do feel free to either reopen this issue or [open a new one](https://developer.matomo.org/guides/core-team-workflow#submitting-a-bug-report). We will gladly take a look again!

**Closed by mattab** 2020-06-12 05:32 UTC
Labels: Bug, Waiting for user feedback
