### ISSUE TITLE
Row evolution API: no data returned when &label parameter matches a path containing @ character

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#6287] opened 2014-09-24 10:57 UTC
This bug has been reported and kindly reproduced in demo server by @websirnik [on the forums here.](http://forum.piwik.org/read.php?2,119964,page=1#msg-120290)

**Row evolution seems to work eg.**
-  [Row evolution report for Page URL: relayto.dev/@korotaev](http://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=32&period=day&date=yesterday#/module=Actions&action=menuGetPageUrls&idSite=32&period=day&date=yesterday&popover=RowAction$3ARowEvolution$3AActions.getPageUrls$3A0$3A$40$252F$2540korotaev)
- API request is successful and returns data for today: http://demo.piwik.org/index.php?module=API&method=Actions.getPageUrls&format=JSON&idSite=32&period=day&date=2014-08-25,2014-09-23&expanded=1&label=%40%252F%2540korotaev&filter_limit=30

**but there is a bug in data in export when row evolution for a page with a sub-directory**
- Row evolution [works in the UI successfully for Page URL: relayto.dev/@korotaev/xwrQK22t ](http://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=32&period=day&date=yesterday#/module=Actions&action=menuGetPageUrls&idSite=32&period=day&date=yesterday&popover=RowAction$3ARowEvolution$3AActions.getPageUrls$3A0$3A$2540korotaev$20$3E$20$40$252FxwrQK22t)
- When label has a slash to match a sub-page then [API export does not show data](http://demo.piwik.org/index.php?module=API&method=Actions.getPageUrls&format=JSON&idSite=32&period=day&date=2014-08-25,2014-09-23&expanded=1&label=%2540korotaev%20%26gt%3B%20%40%252FxwrQK22t&&filter_limit=30&filter_limit=30)

The goal of this issue is to fix the export links so that clicking on export links work in all cases.

**Comment by tsteur** [comment] 2024-02-20 03:46
Closing it as unable to reproduce it

**Closed by tsteur** 2024-02-20 03:46 UTC
Labels: Bug
