### ISSUE TITLE
After upgrade to 3.2.0 getting "Oops… there was a problem during the request." in almost every widget

### ISSUE THREAD

**Issue by galrotem1993** [matomo-org/matomo#12244] opened 2017-11-01 09:06 UTC
hi,
yesterday i updated my piwik from 2.15 to latest version (3.2.0) and also update from php 5.3.8 to 7.0.3.
MySQL version: 5.6.22
running on windows server 2008, IIS 7.5

after the update nothing is working, i get errors 
"oops... there was a problem during request. Maybe the server had a temporary issue, or maybe you requested a report with too much data. Please try again. if this error occurs repeatedly please contact your piwik administrator for assistance"

similar to https://github.com/piwik/piwik/issues/12051 but with almost all the widgets.

any idea how to fix this?
maybe php/iis configuration?

**Comment by Findus23** [comment] 2017-11-01 09:08
Hi, can you check in your php error log, what error exactly occured.

**Comment by galrotem1993** [comment] 2017-11-01 09:30
PHP Fatal error: Cannot declare class Piwik\Plugins\UserCountry\LocationProvider\DefaultProvider, because the name is already in use in Piwik\Plugins\UserCountry\LocationProvider\Default.php on line 112

and

Error in Piwik (tracker): Error query: SQLSTATE[HY000]: General error 1366 Incorrect string value: '\xD7_\xD7\x97\xD7_...' for column 'name' at row 1 in query Insert Into Piwik_log_action (name, hash, type, url_prefix) Values (?, CRC32(?),?,?) Parameters: array:

**Comment by Findus23** [comment] 2017-11-01 09:41
Hi,
This is a duplicate of #11057

You can check there or here for the solution:

https://forum.piwik.org/t/piwik-3-0-0-core-plugin-usercountry-error/22203
(delete `piwik/plugins/UserCountry/LocationProvider/Default.php`)

**Comment by galrotem1993** [comment] 2017-11-01 09:47
its seems to fix the problem.
also https://github.com/piwik/piwik/issues/10378 disabled opcache and deleted plugins/CoreVisualizations/Visualizations/HtmlTable/PivotBy.php

any idea how to fix 
Error in Piwik (tracker): Error query: SQLSTATE[HY000]: General error 1366 Incorrect string value: '\xD7_\xD7\x97\xD7_...' for column 'name' at row 1 in query Insert Into Piwik_log_action (name, hash, type, url_prefix) Values (?, CRC32(?),?,?) Parameters: array:

**Comment by sgiehl** [comment] 2017-11-01 09:58
@galrotem1993  do you know the original value that should have been saved in this case? Which language is your website in?

**Comment by galrotem1993** [comment] 2017-11-01 10:03
the site is English, the content data is Hebrew.
i don't know if this is new error cause i never check that log, this could be an old issue

**Comment by mattab** [comment] 2019-06-18 05:35
Hi there, to fix the issue can you try upgrade to the latest Matomo version?
https://matomo.org/docs/update/

if you still experience this issue afterwards, please re-open this and post a comment. Thanks!

**Closed by mattab** 2019-06-18 05:35 UTC
Labels: duplicate

**Comment by courtens** [comment] 2019-08-20 18:09
Or on Windows - (set permission to "Everyone" stopped working) I needed to add IUSR for it to work again.
