### ISSUE TITLE
Email Report Y Axis Number Cut Off for large numbers

### ISSUE THREAD

**Issue by ibril15** [matomo-org/matomo#14973] opened 2019-10-08 21:56 UTC
Hi,

In Email Report, the y-axis numbers are getting cut off when there are 7+ digits:

![image](https://user-images.githubusercontent.com/26365407/66436328-c0f3b580-e9f4-11e9-934c-a5d7720d70a0.png)

Is this a bug?  Thanks.

-Igor

**Comment by mattab** [comment] 2020-01-21 04:56
@ibril15 Thanks for the report, yes it is a bug :+1:

**Comment by randy-innocraft** [comment] 2024-07-10 17:11
@ibril15, Thank you for reporting this bug. We have tried reproducing the bug, but it no longer seems to be occurring. We will close this ticket now, but if you find that it is still occurring, please let us know and we will reopen this ticket. Thank you!

**Closed by randy-innocraft** 2024-07-10 17:11 UTC
Labels: Bug, c: Graphs and charts, c: Email Reports
