### ISSUE TITLE
Wrong Permission Error Thrown

### ISSUE THREAD

**Issue by JimmyFivy** [matomo-org/matomo#15679] opened 2020-03-06 09:56 UTC
Matomo throws a error for writing permission of the plugin directory. This showed up when I tried to install a plugin without the permission. I made the modification immediately, and I can now install and activate plugins without any trouble. However, after correctly modified the permission setting, the error message still show up on every pages I open, which is pretty annoying.
Is there a way to ignore the message? or to fix it?
![捕获](https://user-images.githubusercontent.com/25278939/76072927-c53bf300-5fd3-11ea-9c9e-81242297a97c.PNG)

**Comment by pebosi** [comment] 2020-03-06 13:02
Did you modified the owner of the files? Maybe, as the message says, you need to set to 777.

**Comment by JimmyFivy** [comment] 2020-03-06 13:12
Yep, as I can confirm that from the output of the file info.
![捕获](https://user-images.githubusercontent.com/25278939/76086461-13aabb00-5fef-11ea-9223-79f54fe6916a.PNG)
And if I had modified the owner correctly, the user "www" should have all permissions of these files.

**Comment by tsteur** [comment] 2020-03-07 02:48
Thanks for mentioning @JimmyFivy Marking this one as a duplicate of https://github.com/matomo-org/matomo/issues/15575

It may help to log out and log in again as a temporary workaround.

**Closed by tsteur** 2020-03-07 02:48 UTC
