### ISSUE TITLE
Deadlocks during archiving

### ISSUE THREAD

**Issue by jbrule** [matomo-org/matomo#15596] opened 2020-02-19 17:16 UTC
I am seeing a lot of deadlocks when running **core:archive** Pretty much this same exception over and over again.

Matomo version: 3.13.0
MySQL version: 5.5.64-MariaDB
PHP version: 7.2.24

Output Follows
INFO [2020-02-19 16:37:26] 61123  Error: Got invalid response from API request: ?module=API&method=API.get&idSite=2863&period=day&date=last52&format=php&trigger=archivephp. Response was 'a:2:{s:6:"result";s:5:"error";s:7:"message";s:11285:"SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction #0 /apps/apache/www/production/matomo/libs/Zend/Db/Statement.php(300): Zend_Db_Statement_Pdo-&gt;_execute(Array) #1 /apps/apache/www/production/matomo/libs/Zend/Db/Adapter/Abstract.php(479): Zend_Db_Statement-&gt;execute(Array) #2 /apps/apache/www/production/matomo/libs/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query('DELETE FROM `pi...', Array) #3 /apps/apache/www/production/matomo/core/Db/Adapter/Pdo/Mysql.php(309): Zend_Db_Adapter_Pdo_Abstract-&gt;query('DELETE FROM `pi...', Array) #4 /apps/apache/www/production/matomo/core/Db.php(276): Piwik\Db\Adapter\Pdo\Mysql-&gt;query('DELETE FROM `pi...', Array) #5 /apps/apache/www/production/matomo/core/Option.php(235): Piwik\Db::query('DELETE FROM `pi...', Array) #6 /apps/apache/www/production/matomo/core/Option.php(94): Piwik\Option-&gt;deleteNameLike('report_to_inval...', NULL) #7 /apps/apache/www/production/matomo/core/Archive/ArchiveInvalidator.php(145): Piwik\Option::deleteLike('report_to_inval...') #8 /apps/apache/www/production/matomo/core/Archive/ArchiveInvalidator.php(217): Piwik\Archive\ArchiveInvalidator-&gt;forgetRememberedArchivedReportsToInvalidate(2863, Object(Piwik\Date)) #9 /apps/apache/www/production/matomo/core/Archive.php(508): Piwik\Archive\ArchiveInvalidator-&gt;markArchivesAsInvalidated(Array, Array, false) #10 /apps/apache/www/production/matomo/core/Archive.php(641): Piwik\Archive-&gt;invalidatedReportsIfNeeded() #11 /apps/apache/www/production/matomo/core/Archive.php(620): Piwik\Archive-&gt;cacheArchiveIdsAfterLaunching(Array, Array) #12 /apps/apache/www/production/matomo/core/Archive.php(549): Piwik\Archive-&gt;getArchiveIds(Array) #13 /apps/apache/www/production/matomo/core/Archive.php(303): Piwik\Archive-&gt;get(Array, 'numeric') #14 /apps/apache/www/production/matomo/plugins/VisitsSummary/API.php(36): Piwik\Archive-&gt;getDataTableFromNumeric(Array) #15 [internal function]: Piwik\Plugins\VisitsSummary\API-&gt;get('2863', 'day', 'last52', false, Array) #16 /apps/apache/www/production/matomo/core/API/Proxy.php(237): call_user_func_array(Array, Array) #17 /apps/apache/www/production/matomo/core/Context.php(28): Piwik\API\Proxy-&gt;Piwik\API\{closure}() #18 /apps/apache/www/production/matomo/core/API/Proxy.php(328): Piwik\Context::executeWithQueryParameters(Array, Object(Closure)) #19 /apps/apache/www/production/matomo/plugins/API/API.php(435): Piwik\API\Proxy-&gt;call('\\Piwik\\Plugins\\...', 'get', Array) #20 [internal function]: Piwik\Plugins\API\API-&gt;get('2863', 'day', 'last52', false, Array) #21 /apps/apache/www/production/matomo/core/API/Proxy.php(237): call_user_func_array(Array, Array) #22 /apps/apache/www/production/matomo/core/Context.php(28): Piwik\API\Proxy-&gt;Piwik\API\{closure}() #23 /apps/apache/www/production/matomo/core/API/Proxy.php(328): Piwik\Context::executeWithQueryParameters(Array, Object(Closure)) #24 /apps/apache/www/production/matomo/core/API/Request.php(265): Piwik\API\Proxy-&gt;call('\\Piwik\\Plugins\\...', 'get', Array) #25 /apps/apache/www/production/matomo/plugins/API/Controller.php(41): Piwik\API\Request-&gt;process() #26 [internal function]: Piwik\Plugins\API\Controller-&gt;index() #27 /apps/apache/www/production/matomo/core/FrontController.php(589): call_user_func_array(Array, Array) #28 /apps/apache/www/production/matomo/core/FrontController.php(165): Piwik\FrontController-&gt;doDispatch('API', false, Array) #29 /apps/apache/www/production/matomo/core/dispatch.php(34): Piwik\FrontController-&gt;dispatch() #30 /apps/apache/www/production/matomo/index.php(27): require_once('/apps/apache/ww...') #31 /apps/apache/www/production/matomo/core/CliMulti/RequestCommand.php(79): require_once('/apps/apache/ww...') #32 /apps/apache/www/production/matomo/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): Piwik\CliMulti\RequestCommand-&gt;execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #33 /apps/apache/www/production/matomo/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command-&gt;run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #34 /apps/apache/www/production/matomo/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application-&gt;doRunCommand(Object(Piwik\CliMulti\RequestCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #35 [internal function]: Symfony\Component\Console\Application-&gt;doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #36 /apps/apache/www/production/matomo/core/Console.php(103): call_user_func(Array, Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #37 /apps/apache/www/production/matomo/core/Access.php(639): Piwik\Console-&gt;Piwik\{closure}() #38 /apps/apache/www/production/matomo/core/Console.php(104): Piwik\Access::doAsSuperUser(Object(Closure)) #39 /apps/apache/www/production/matomo/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Piwik\Console-&gt;doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #40 /apps/apache/www/production/matomo/console(27): Symfony\Component\Console\Application-&gt;run() #41 {main}, caused by: SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction #0 /apps/apache/www/production/matomo/libs/Zend/Db/Statement/Pdo.php(228): PDOStatement-&gt;ex
INFO [2020-02-19 16:37:26] 61123  Error: Empty or invalid response '' for website id 2863, Time elapsed: 3.736s, skipping
ERROR [2020-02-19 16:37:26] 61123  128 total errors during this script execution, please investigate and try and fix these errors.

 
  [Exception]
  128 total errors during this script execution, please investigate and try and fix these errors.

**Comment by tsteur** [comment] 2020-02-19 20:18
@jbrule this is a duplicate of https://github.com/matomo-org/matomo/issues/15545 

Be good to read the issue and the comments and also especially https://github.com/matomo-org/matomo/issues/15545#issuecomment-586746584 we'd basically need more details about the deadlock

**Closed by tsteur** 2020-02-19 20:18 UTC
Labels: duplicate
