### ISSUE TITLE
new search engine

### ISSUE THREAD

**Issue by broros** [matomo-org/matomo#15332] opened 2019-12-31 09:21 UTC
why don't you implement Elasticsearch instead of mysql?

**Comment by sgiehl** [comment] 2019-12-31 09:24
This is a widely used open source software. The most common setup for webhosters is still PHP / MySQL. Switching the database would make it impossible for a lot users to use it...

**Comment by Findus23** [comment] 2019-12-31 11:24
In addition, I don't think the main focus of Matomo isn't search (and especially full text search) where something like Elasticsearch would bring benefits.

**Comment by tsteur** [comment] 2019-12-31 20:50
marking this as a duplicate of https://github.com/matomo-org/matomo/issues/500 where we discuss alternatives. I doubt ElasticSearch be a real option though since there are faster / better alternatives that are also more SQL compatible

**Closed by tsteur** 2019-12-31 20:50 UTC
