### ISSUE TITLE
Error during Autoupdate to 3.9.0

### ISSUE THREAD

**Issue by kuality** [matomo-org/matomo#14248] opened 2019-03-20 19:03 UTC
When I ran the auto update to 3.9, my browser tried to go to 
https://traffic.umintmed.ca/index.php??module=CoreUpdater&action=oneClickUpdate

Which then gave an error which I stupidly didn't take down. 
I stripped off the URL past index.php and Matomo loaded. Then tried to go back to 
https://traffic.umintmed.ca/index.php??module=CoreUpdater&action=oneClickUpdate 
And now it says "An error occurred" and that Matomo is up to date at version 3.9.0; This also shows up in the PHP log ([20-Mar-2019 18:50:00 UTC] Error in Matomo: Your Matomo version 3.9.0 is up to date.), but the original error doesn't show in that log. 
No error showed in the apache error log for this. 
Apache access log shows 142.xxx.xxx.xxx- - [20/Mar/2019:11:50:01 -0700] "GET /plugins/Morpheus/images/logo.svg HTTP/1.1" 200 2953 "https://traffic.umintmed.ca/index.php?module=CoreUpdater&action=oneClickUpdate" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:65.0) Gecko/20100101 Firefox/65.0"  but not sure if that's even from that access. 

On a somewhat unrelated note... you guys have changed most mentions of "piwik" to "matomo" but the Apache access logs still give me lines like the following for our mediawikis that use matomo via the [Matomo extension v4.0.0](https://www.mediawiki.org/wiki/Extension:Matomo) 
142.xxx.xxx.xxx- - [20/Mar/2019:05:54:18 -0700] "GET //**piwik**.php?action_name=Recent%20changes%20-%20CCMDB%20Wiki&idsite=4&rec=1&r=585411&h=7&m=57&s=53&url=https%3A%2F%2Fccmdb.kuality.ca%2Findex.php%2FSpecial%3ARecentChanges&_id=d3cfc693367ba880&_idts=1551904279&_idvc=9&_idn=0&_refts=0&_viewts=1553086674&send_image=1&pdf=1&qt=0&realp=0&wma=0&dir=0&fla=0&java=0&gears=0&ag=0&cookie=1&res=1366x768&gt_ms=866&pv_id=QnnCqq HTTP/1.1" 200 404 "https://ccmdb.kuality.ca/index.php/Special:RecentChanges" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36"

**Comment by andre5tz** [comment] 2019-03-20 19:25
I got this error:
> 
Matomo encountered an error: Call to undefined method Piwik\Plugin\Manager::getPluginDirectory() (which lead to: Circular dependency detected while trying to resolve entry 'Piwik\Twig')

**Comment by kuality** [comment] 2019-03-20 19:28
Yes, that sounds about right, I do remember the method and the piwik and the circular part. Glad you paid more attention than I did, andre5tz.

**Comment by Findus23** [comment] 2019-03-20 19:31
Hi, this sounds like https://github.com/matomo-org/matomo/issues/14227 which has already been fixed and is included in 3.9.1 which will be released soon.
(Duplicate of #14227)

**Closed** 2019-03-20 19:31 UTC
Labels: duplicate
