### ISSUE TITLE
Unique Visitors missing in Referrer breakdowns when using period other than daily

### ISSUE THREAD

**Issue by caistleitner** [matomo-org/matomo#11179] opened 2017-01-11 11:37 UTC
In Referrers breakdowns, Unique Visitors column is not available for anything but "daily" periods.

We're on Piwik 2.17.1, and we have enabled UV processing for all periods following Faq#113 by using

```
[General]
enable_processing_unique_visitors_day = 1
enable_processing_unique_visitors_week = 1
enable_processing_unique_visitors_month = 1
enable_processing_unique_visitors_year = 1
enable_processing_unique_visitors_range = 1
```
We re-generated archived reports, but on the tables on the "Referrers"/"All Referrers" page, the "Unique Visitors" column is only shown for daily periods.

What we're seeing can also be seen on demo.piwiki.org:

When navigating to (period parameter is "daily"):

http://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=3&period=day&date=yesterday#?idSite=3&period=day&date=yesterday&category=Referrers_Referrers&subcategory=Referrers_WidgetGetAll

The third column in both the "Referrer Types" and "Referrers" tables is "Unique Visitors". So the numbers we're looking for are available for daily periods.

But when changing the period to weekly, the "Unique Visitors" column disappears. E.g.:

http://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=3&period=day&date=yesterday#?idSite=3&period=week&date=2017-01-09&category=Referrers_Referrers&subcategory=Referrers_WidgetGetAll

On that page, the "Referrer Types" and "Referrers" tables are missing the "Unique Visitors" column.

Is there a way to get the "Unique Visitors" column also for other-than-daily periods per referrer?

[Forum discussion](https://forum.piwik.org/t/unique-visitors-missing-in-referrer-breakdowns-when-using-period-other-than-daily/22558) suggested to file this issue here at github.

**Comment by mattab** [comment] 2017-01-22 00:00
Hi @caistleitner 
Thanks for the report. Could you please try this small patch here: https://github.com/piwik/piwik/pull/11240/files

and report if the issue is fully fixed for you?

**Comment by somechris** [comment] 2017-01-22 11:35
Unfortunately, the patch does not address the issue.

The patch is for the Evolution graph in the “Referrers”/“Overview” page.
And the patch only adds the possibility to select "Unique Visitors" and "Users" for "Metrics to plot" in the Evolution graph for periods other than daily. But when selecting for example “Unique Visitors” (for periods other than daily) the plotted graph is a flat line at zero.
(The selected web page has >0 UVs and I had regenerated reports of course)

So the patch adds non-working selection possibilities.
And the patch is for a different page (The patch is for "Referrers"/"Overview", but the issue calls for "Referrers"/"All Referrers").

**Comment by caistleitner** [comment] 2017-01-22 11:36
Unfortunately, the patch does not address the issue.

The patch is for the Evolution graph in the “Referrers”/“Overview” page.
And the patch only adds the possibility to select "Unique Visitors" and "Users" for "Metrics to plot" in the Evolution graph for periods other than daily. But when selecting for example “Unique Visitors” (for periods other than daily) the plotted graph is a flat line at zero.
(The selected web page has >0 UVs and I had regenerated reports of course)

So the patch adds non-working selection possibilities.
And the patch is for a different page (The patch is for "Referrers"/"Overview", but the issue calls for "Referrers"/"All Referrers").

**Comment by halfnibble** [comment] 2017-01-22 22:43
I am having a related issue. I'm on 3.0.1. I modified my config to enable unique_visitors processing for all report types. And I even applied the fix suggested by @mattab.

I am trying to get unique visitors by year using `'VisitsSummary.get'`.

The funny thing is, it returns `nb_uniq_visitors` for 2016 and 2017, but sets 2014 and 2015 to `0`. 

However, if I go with a *monthly* report, I can see `nb_uniq_visitors` for both 2014 and 2015.  So something very strange is going on.

**Comment by caistleitner** [comment] 2017-01-23 13:50
@halfnibble: It seems your problem is different from the one describen in this issue, as you are using the `VisitsSummary.get` API. However, as the API exposes numbers for 2017 and 2016, but not older years, deleting old reports (if you've still got the raw input data for them!) and have them regenerated in the next request may do the trick. This approach is mentioned in code comments, but is missing from [Faq#113](http://piwik.org/faq/how-to/faq_113/). See issue #11265.

**Comment by mattab** [comment] 2017-02-18 11:40
@halfnibble You need to force PIwik to invalidate your old data, I think. Please try this: https://piwik.org/faq/how-to/faq_155/

**Comment by mattab** [comment] 2023-12-10 11:56
Thanks for contributing to this issue. As it has been a few months since the last activity and we believe this is likely not an issue anymore, we will now close this. If that's not the case, please do feel free to either reopen this issue or [open a new one](https://developer.matomo.org/guides/core-team-workflow#submitting-a-bug-report). We will gladly take a look again!

**Closed by mattab** 2023-12-10 11:56 UTC
Labels: Bug
