### ISSUE TITLE
Dashboard percentage incorrect on massive increase

### ISSUE THREAD

**Issue by holtwick** [matomo-org/matomo#16067] opened 2020-06-15 08:58 UTC
My website increased traffic from about 100 visits to a few thousands. The percentage dropped down to a low number (3%) where instead it should show be above 1000%. Interestingly when sorting by evolution the order is correct, therefore I guess it is probably a display issue.

![CleanShot 2020-06-15 at 10 53 10@2x](https://user-images.githubusercontent.com/49557/84638102-d2cc1780-aef6-11ea-8385-f1cf72a8112d.png)

<img width="761" alt="CleanShot 2020-06-15 at 10 58 50@2x" src="https://user-images.githubusercontent.com/49557/84638412-3eae8000-aef7-11ea-8b9f-868dd8d1f92d.png">

**Comment by sgiehl** [comment] 2020-06-15 10:15
@holtwick Thanks for creating this issue. I've just tried to reproduce that locally by generating some local test data. Seems that happens as soon as the percentage exceeds 1000. We need to investigate that further.

**Comment by sgiehl** [comment] 2020-07-23 09:42
The problem seems to be, that numbers are all returned formatted and in JavaScript they are tried to parse to Integer, which has incorrect results for a string like `1,235.2%`.  The tooltip for the totals also show an incorrect percentage. In addition parsing numbers in languages that don't use a normal dash as indicator for negativ numbers might result in a complete fail...

**Comment by bx80** [comment] 2021-11-15 20:50
This issue has been fixed in #18099

**Closed by bx80** 2021-11-15 20:50 UTC
Labels: Bug
