### ISSUE TITLE
GeoIP2 plugin issue in Matomo

### ISSUE THREAD

**Issue by revathi-muthana123** [matomo-org/matomo#16444] opened 2020-09-16 10:28 UTC
Hello, 
We have Matomo 3.12.0 setup on my environment. We are using GeoIP2 (php) plugin for the location tracking from visitors. but we have an issue here, some of the users are browsing from their websites & monitoring analytics. But it is showing default location as “united States” instead of original locations. I read some of the official documents like after 1.9 or later versions it is using GeoIP2 for tracking locations instead of languages. So we tried to download latest version of this plugin from Maxmind website “https://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz” in the same way which we have done earlier.
Finally we found that & signed up for the account & provided license details as well. But it’s not installing properly. It’s throwing some error like " Error: Matomo tried checking the location of a known IP address (194.57.91.215), but your server returned ‘L’Ecouvotte, BFC, FR’. If this provider were configured correctly, it would return ‘Besançon, BFC, FR’.".
Please help me on this. How we can install, what are the steps we need to follow.

![image](https://user-images.githubusercontent.com/39338792/93325726-5ddde600-f835-11ea-9cb3-21f138b6d5fe.png)

Thanks & Best Regards
Revathi

**Comment by Findus23** [comment] 2020-09-16 10:36
For reference: https://forum.matomo.org/t/geoip2-plugin-issue-in-matomo/38523

**Comment by Findus23** [comment] 2020-09-16 10:40
Can you try updating to Matomo 3.13.1?
3.12.0 was released before Maxmind changed their free database and therefore probably can't properly support the new files.

**Comment by sgiehl** [comment] 2020-09-16 10:44
Updating Matomo to 3.14 should actually solve that issue. The detected
location seems to have changed in a newer release of the geoip2 database.
We have already changed that check when integrating support for db-ip.
If updating is not possible in your case you may need to adjust the code
manually...

**Comment by revathi-muthana123** [comment] 2020-09-16 10:53
> Can you try updating to Matomo 3.13.1 or later?
> 3.12.0 was released before Maxmind changed their free database and therefore probably can't properly support the new files.

Yes, we will update when it is only the solution. Thanks for the suggestion.

**Comment by revathi-muthana123** [comment] 2020-09-16 11:00
> Updating Matomo to 3.14 should actually solve that issue. The detected location seems to have changed in a newer release of the geoip2 database. We have already changed that check when integrating support for db-ip. If updating is not possible in your case you may need to adjust the code manually...

Thanks for the answer, Will take time to update. Meanwhile if we need to change the code manually, can you suggest the process where & what we need to change ?

**Comment by revathi-muthana123** [comment] 2020-09-16 12:50
Hello, There is one more issue, we are not sure exactly relates to Matomo or GeoIP plugin. For example in my team 2 colleges are there but working from different locations, i am from India & he is from Poland. He is in another network & i am from different.
When he is trying to get that location from "https://www.maxmind.com/en/locate-my-ip-address" website, it's not tracking any ip address but when i tried from India it is working fine & displaying locations also as i am sharing the screenshots.

![india](https://user-images.githubusercontent.com/39338792/93339455-3c86f500-f849-11ea-9279-cbc59d19c1b4.png)
![Poland](https://user-images.githubusercontent.com/39338792/93339474-41e43f80-f849-11ea-85f5-5c3ca6b8592b.png)

Please help us to find the cause for this.

**Comment by tsteur** [comment] 2020-09-16 21:11
@revathi-muthana123 I suggest you get in touch directly with MaxMind regarding your last two comments. Maybe they can help you. It's possible their database simply doesn't have the data for that IP.

I'll close the issue for now as I understand the issue is fixed in a newer version. Let us know if updating didn't help @revathi-muthana123  and we'll be happy to reopen.

Thanks

**Closed by tsteur** 2020-09-16 21:11 UTC

**Comment by revathi-muthana123** [comment] 2020-11-05 06:11
Hello,
We have upgraded to latest version of Matomo 3.14.1. But still default location is pointing to "United States (North America)" only. It's not indicating to original location. Can you please help on this.
![image](https://user-images.githubusercontent.com/39338792/98204324-d589e080-1f5b-11eb-91fa-f62176bd01ea.png)

**Comment by tsteur** [comment] 2020-11-05 18:37
@revathi-muthana123  have you configured a geo IP provider see https://matomo.org/docs/geo-locate/

**Comment by revathi-muthana123** [comment] 2020-11-06 06:25
Hello @tsteur Yes, we configured in the same way & we tried different methods as well but still it's not resolving that issue. It is pointing to the same "united states" location. We suspect that it is a bug in Matomo. We tried Geolite2 City & Country Databases as well. Is there anything else to be configured, why because ISP Provider & Org Provider both are showing unknown. Can you help on this, as it is blocking us.
![image](https://user-images.githubusercontent.com/39338792/98333544-0256fa00-2027-11eb-8ba6-941c4d29ae01.png)

**Comment by tsteur** [comment] 2020-11-08 20:26
@revathi-muthana123 if it's blocking you, you might want to consider looking into our support subscriptions https://matomo.org/support-plans/ since in these cases where things aren't quite obvious what is happening we can't always do too much. 

Depending what GeoDB you use, I recommend you enter your IP address into their online tool to see if it detects the location correctly. Eg you can visit https://db-ip.com/ or https://www.maxmind.com/en/geoip-demo

If you have Matomo set up behind a proxy or similar, and it's not receiving the correct IP address, you might want to look into https://matomo.org/faq/how-to-install/faq_98/
