### ISSUE TITLE
Manage Plugins -> Activate any plug-in makes tab in Chrome hang

### ISSUE THREAD

**Issue by bluikko** [matomo-org/matomo#11191] opened 2017-01-14 13:48 UTC
After updating Piwik to 3.0.0. Go to Manage Plugins, and "Activate" any plug-in makes Chrome tab hang/freeze. After clicking "Activate", Chrome loads for a while and after page loading complete, the tab hangs. Cannot scroll, if switching to another tab & back, the tab is empty. Basically can only reload the tab and it works again (shows the Manage Plugins page).

Numerous problems in Piwik update to 3.0.0, this happened immediately after update (including after manually deleting some files that were "leftovers" from some old version and caused piles of errors). It still happens after a clean re-installation of Piwik.

**Comment by mattab** [comment] 2017-02-18 09:28
Hi @bluikko 
Thanks for the report. So far we cannot reproduce. Do you find any error in your web server error log file?

**Comment by bluikko** [comment] 2017-02-18 11:53
No errors. Seemed to be one of the multiple problems with this update, and completely client-side. Clearing browser cache fixed the issue.

**Comment by mattab** [comment] 2017-02-20 17:01
Would you please send us temporary, super user access to your Piwik? please let us know at matt@piwik org or via http://piwik.org/contact/

**Comment by mattab** [comment] 2020-06-12 05:32
Thanks for contributing to this issue. As it has been a few months since the last activity and we believe this is likely not an issue anymore, we will now close this. If that's not the case, please do feel free to either reopen this issue or [open a new one](https://developer.matomo.org/guides/core-team-workflow#submitting-a-bug-report). We will gladly take a look again!

**Closed by mattab** 2020-06-12 05:32 UTC
Labels: Waiting for user feedback
