### ISSUE TITLE
Add new Edge (Chromium) user agent

### ISSUE THREAD

**Issue by Aarklendoia** [matomo-org/matomo#14327] opened 2019-04-09 08:25 UTC
The new Edge based on Chromium is available for Edge Insiders.

The user agent is :
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.48 Safari/537.36 Edg/74.1.96.24`

Could you add it?

**Comment by fdellwing** [comment] 2019-04-09 09:03
Duplicate of #14268

**Comment by sgiehl** [comment] 2019-04-09 09:20
should already be detected with latest master

**Closed by sgiehl** 2019-04-09 09:20 UTC

**Comment by Aarklendoia** [comment] 2019-04-09 09:23
I use version 3.9.1 and it displays Chrome 74.0 (and not Edge 74.1).

**Comment by sgiehl** [comment] 2019-04-09 09:25
It was not included in latest release. But should be in the next one.

**Comment by Aarklendoia** [comment] 2019-04-09 09:26
Ok, thanks.
