### ISSUE TITLE
./console core:update always executes dry-run 

### ISSUE THREAD

**Issue by weberhofer** [matomo-org/matomo#12909] opened 2018-05-14 09:41 UTC
Updating from 3.4 to 3.5 always executes the dry-run mode ans doesn't actually update the databases. Up to 3.4 the updates worked perfectly.

**Comment by tsteur** [comment] 2019-10-30 01:18
Can you try setting the option ` --yes`? Otherwise what is the output at the end of the command?

**Comment by stefan-niedermann** [comment] 2019-10-30 07:07
I fixed it myself in the meantime by executing the dry-run sql query directly.

**Comment by tsteur** [comment] 2019-10-30 19:46
Thanks for letting us know. I'll close this issue for now as we can't reproduce it. If anyone experiences this issue please comment and we'll try to get more details such as https://github.com/matomo-org/matomo/issues/12909#issuecomment-547697647

**Closed by tsteur** 2019-10-30 19:46 UTC

**Comment by SubJunk** [comment] 2020-12-05 08:29
Appending `--yes` fixed it for me

**Comment by bbodenmiller** [comment] 2021-01-09 09:18
I'm also always getting dry runs without running `--dry-run`. Is it possible `multi_server_environment = 1` is the cause of this?

I'm also not being prompted in the UI to do database upgrade when I should be.

**Comment by bbodenmiller** [comment] 2021-01-09 09:25
Actually looks like dry run is the default: https://github.com/matomo-org/matomo/blob/0d979018ce23e8e0187dd435cc8de99fcf3c3585/CHANGELOG.md#breaking-changes-18
