### ISSUE TITLE
pivacy settings per website

### ISSUE THREAD

**Issue by hpvd** [matomo-org/matomo#11009] opened 2016-12-14 15:54 UTC
When using piwik as multisite tracking tool, privacy settings (like ip anonymization, delete reports, respectation of do not track) should be possible per website not per complete piwik installation.

Reason:
there may be different requirements for each website:
- testing or live
- different kinds of business
- different kinds of user-groups
- active in different countries 
-...

**Comment by tsteur** [comment] 2016-12-14 18:41
Definitely, I'm missing this feature as well. Be good to have 👍

**Comment by es86de** [comment] 2017-03-14 18:01
I miss that feature too.

**Comment by tsteur** [comment] 2020-09-03 21:12
closing this issue as a duplicate of https://github.com/matomo-org/matomo/issues/11009

**Closed by tsteur** 2020-09-03 21:12 UTC
Labels: Enhancement, c: Privacy
