### ISSUE TITLE
Content Interaction not counted

### ISSUE THREAD

**Issue by xf039** [matomo-org/matomo#15306] opened 2019-12-22 18:03 UTC
Matomo version: 3.13.0
MySQL version: 5.5.64-MariaDB
PHP version: 7.2.25

Content interactions are not tracked and appear as out-click in the visitor log. Content impressions are counted.

Integration
```html
<a href="https://example.com" target="_blank" data-track-content data-content-name="Group" data-content-piece="Name"><img src="https://example.com/image.png" /></a>
````

**Comment by tsteur** [comment] 2019-12-22 18:24
Any chance you can send us a link to our website where we can reproduce this? Could also do by email: hello at matomo.org

In case you know: Is there maybe some click event listener  on the link or image that would prevent our click listener to work?

**Comment by xf039** [comment] 2019-12-22 19:00
@tsteur Thanks for the quick follow up and I appreciate your time looking into this issue. 

I have emailed the link to the email address you provided, there should be no click listeners attached to the image

**Comment by tsteur** [comment] 2019-12-22 19:33
Thanks. I just had a look and tested it on one of banners and it worked actually nicely for me. You might see my actions in the visits log. Which browser are you using? Is all the other tracking working?  Do you maybe have an ad blocker or something similar enabled?

**Comment by xf039** [comment] 2019-12-22 20:03
@tsteur Thanks for checking it out! 

Below the screenshot from the visit log of your visit, the content impressions are registered but the banner interactions are only registered as out-clicks and not as content interactions. ![image](https://user-images.githubusercontent.com/8216035/71326649-ef663480-24fd-11ea-94bf-c07e2606be17.png)

The same problem occurs with all other visitors, the interaction rate stays at 0 over the complete month, all other tracking is working fine.

**Comment by xf039** [comment] 2019-12-22 20:12
@tsteur Thanks for checking it out!  

Below the screenshot from the visit log the content impressions are registered but the banner interactions are only registered as out-clicks and not as content interactions. ![image](https://user-images.githubusercontent.com/8216035/71326649-ef663480-24fd-11ea-94bf-c07e2606be17.png)

The same problem occurs with all other visitors, the interaction rate stays at 0 over the complete month, all other tracking is working fine. Maybe there is something wrong with the way I implemented the content tracking tag?

**Comment by tsteur** [comment] 2019-12-22 21:14
I see. It seems outlinks are not supported yet but only internal links. I'm marking this issue as a duplicate of https://github.com/matomo-org/matomo/issues/12880  and https://github.com/matomo-org/matomo/issues/12227 . As mentioned in #12227 it looks like we will be fixing this as part of Matomo 4 in https://github.com/matomo-org/matomo/issues/6265 . We started work on Matomo 4 already.

**Closed by tsteur** 2019-12-22 21:14 UTC
