### ISSUE TITLE
row evolution exporty fails if you try to export data from second page

### ISSUE THREAD

**Issue by RMastop** [matomo-org/matomo#4473] opened 2014-01-03 12:00 UTC
When one tries to export data from line higher than or equal to 25 in a row evolution, you get no data.
Exporting from a row evolution from line 1 to 24 works well.

The URL behind the export option contains query parameter: "&filter_limit=#INT#" where #INT# is 24.
I've seen cases where #INT# is 100.

I'm using version Piwik 2.0.2.

**Comment by urmet0** [comment] 2017-06-27 11:48
Do you have any news on this?

I have trouble with the same thing. Reading this bug i have seen, that i also have a duplicate filter_limit parameter. Once with false and once with 10.
When i remove the parameter with 10, the export returns a correct csv.
Otherwise it returns only "Date".

It seems that there is only a problem for the period year, but it works with month.
And it works with different URLs (period year) and there are 2 filter_limit parameters too.

I could "reproduce" this behaviour on demo site using the following URL. But i saw, that the label in the URL is not valid. However...the result is the same. :)
http://demo.piwik.org/index.php?module=API&method=Actions.getPageUrls&format=CSV&idSite=3&period=year&date=2013-01-01,2017-12-31&label=&date=2013-01-01%2C2017-12-31&filter_limit=false&format_metrics=1&expanded=1&translateColumnNames=1&language=de&label=virtual-%E2%80%8Bdrums.%E2%80%8Bcom/%E2%80%8Bphotos.%E2%80%8Bphp/%E2%80%8Bvirtual-%E2%80%8Bdrums-%E2%80%8Blaval-%E2%80%8Bvirtual-%E2%80%8B002/&token_auth=anonymous&filter_limit=5


I use Piwik 2.14.1

**Comment by mattab** [comment] 2017-07-10 21:41
> I use Piwik 2.14.1

Please upgrade to Piwik 3 and let us know if you still experience this issue?

**Comment by urmet0** [comment] 2017-07-18 11:22
Hm, but i tried to reproduce it on your demo site and it worked. Not good enough?
Is there any bugfix for this, that it is worth to upgrade to the actual version?

I have this problem in production environment (could not reproduce it in development) and there are people working there. The upgrade includes UI changes, so it is not the best option for me.

**Comment by mattab** [comment] 2017-07-24 05:07
Yes, this bug was fixed

**Comment by urmet0** [comment] 2018-01-03 14:44
My problem seems to be fixed after upgrading to Piwik 3.2.0.
Now the report is completely shown.

Thank you.

**Comment by sgiehl** [comment] 2019-01-05 22:46
This one might be fixed meanwhile with the next export overlay

**Comment by tsteur** [comment] 2024-02-20 03:28
Closing this as it seems fixed, if it still happens please comment or create a new issue

**Closed by tsteur** 2024-02-20 03:28 UTC
Labels: Bug
