### ISSUE TITLE
Email reports sent via the cron core:archive task do not contain reports that depend on idsite

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#12560] opened 2018-02-15 02:31 UTC
This is when executed on the cli. The problem is, there is no `$_GET[idSite]` set which means no `Reports.addReports` event listener can find reports as they use `getRequestVar('idSite')` to find eg all custom dimensions. This means it is not possible for plugins to add any reports depending on the idSite while rendering scheduled reports.

Easiest solution / work around would be probably to temporarily set an idsite while generating a report, and the ReportsCache would need to be based on idSite.

To test use eg `./console scheduled-tasks:run --force`

**Comment by mattab** [comment] 2018-03-13 00:03
We also have a similar issue, which should be addressed ideally here too:

We get the error: `ERROR [2018-03-12 21:09:50] Got invalid response from API request: ?module=API&method=API.get&idSite=2&period=day&date=last52&format=php&trigger=archivephp. Response was 'a:2:{s:6:"result";s:5:"error";s:7:"message";s:81:"Segment 'dimension7' is not a supported segment. - caused by plugin CustomReports";}'`, 
but we found that idSite=2 is a Roll-Up site, and the roll-up does not have custom reports.
But the website idSite=1  has the dimension7 existing.

-> Therefore the issue is that the roll-up idSite=2 sub-triggers the archiving of idsite=1, but does not load the right dimensions. We should address this specifically with a work-around as the other issue with email reports.

**Comment by mattab** [comment] 2018-03-13 00:04
Edit: Marking as `Major` because we are otherwise getting email reports with the error each day, and the roll-up data is not processed correctly.

**Closed** 2018-03-20 10:20 UTC
Labels: Bug, Major
