### ISSUE TITLE
how en encrypt url params of matomo.php from inside matomo.js

### ISSUE THREAD

**Issue by dave-dm** [matomo-org/matomo#16334] opened 2020-08-21 09:44 UTC
My goal is to encrypt the url params then send the matomo.php request to a proxy, which will decrypt the params and then send to the real matomo.php. The reason for this is I am already proxying matomo.php and matomo.js with different file names and from the same domain but ublock stills blocks it. I'm thinking it identifies the url params?

Inside matomo.js https://raw.githubusercontent.com/matomo-org/matomo/master/js/piwik.js where should I be encrypting the request? I see 2 request types, XMLRequest and sendBacon, which one should I use? Is there a central place where I can encrypt the request query string?

**Comment by tsteur** [comment] 2020-08-23 20:03
Thanks for creating this issue @dave-dm . I'll close this issue as a duplicate of https://github.com/matomo-org/matomo/issues/7364 and https://github.com/matomo-org/matomo/issues/14207

**Closed by tsteur** 2020-08-23 20:03 UTC
