### ISSUE TITLE
Visitor Totals for a Segment Not Summed Correctly with a Date Range of a Month

### ISSUE THREAD

**Issue by garrick-abine** [matomo-org/matomo#16545] opened 2020-10-07 12:35 UTC
Hello,

We seem to be having an issue similar to #16320 where aggregated totals for a segment don't calculate correctly.  Our install is on-premise running 3.14.1.  We have a segment where all visits for the channel for the month (Sep 2020) totaled 1,336 visits. This is the the same total regardless of the period selected (month or date range).  However, selecting the following date ranges for the same segment yields visitor totals of:

Date Range | Visitor Totals
------------|--------------
1 Sep - 30 Sep | 1,336
1 Sep - 26 Sep | 4,467
1 Sep - 27 Sep | 711
8 Sep - 30 Sep | 4,005

We tried invalidating the reports for the segments (for the month of Sep) and re-running the archive progress to recreate them.   However, the error with the totals remains.  This issue does not appear for the previous month (Aug 2020).  Is there something else that we can investigate or do to correct this?  Thanks!

**Comment by tsteur** [comment] 2020-10-07 20:08
Thanks for creating the issue @garrick-abine I've followed up in https://github.com/matomo-org/matomo/issues/16320#issuecomment-705165706 and will close the issue as it looks like a duplicate of that issue and it be great to have all the information in one issue. I hope you don't mind :)

**Closed by tsteur** 2020-10-07 20:08 UTC
