### ISSUE TITLE
Transition plugin can't handle named characters in URL

### ISSUE THREAD

**Issue by minos314** [matomo-org/matomo#10733] opened 2016-10-13 08:21 UTC
I've recognized the transition module can't handle URLs containing named characters.

For example, when I navigte to Actions > Pages, try to open the transitions on a URL like `/testweb/page.php?param1=a&regparam=b` i get following error: 

> There's no data for /testweb/page.php?param1=a®param=b

My guess is the `&reg` param gets interpreted as a naming character, resulting in ®. Therefore the transition module can't find any data. 
The other row actions, like visitor log or row evolution are working on the same URLs.

Reproduced with multiple browsers (chrome, ie, ff)
Piwik 2.16.2
PHP 5.4.16

**Comment by sgiehl** [comment] 2017-09-10 17:30
I'm not able to reproduce that with Piwik 3.1.0. Tracked a url with those params locally and the transitions report for this urls works just fine.
@minos314  please reopen if you can reproduce that with latest Piwik version.

**Comment by minos314** [comment] 2018-05-02 08:43
I can still reproduce the issue in matomo 3.3.0.
Follow these steps:
1. fresh matomo 3.3.0 install
2. create logfile with following sinlge line as content
`test.com 127.0.0.1 - frank [10/Oct/2000:13:55:36 -0700] "GET /web/somepage.html?cmd=view&regseq_typ=1 HTTP/1.0" 200 7453`
3. import log file with import_logs.py
4. navigte to Actions > Pages, try to open the transitions on that URL

**Comment by minos314** [comment] 2018-06-05 13:46
@sgiehl Please reopen issue.

**Comment by sgiehl** [comment] 2020-04-28 09:40
should be fixed with #15221 in Matomo 4

**Closed by sgiehl** 2020-04-28 09:40 UTC
Labels: Bug
