### ISSUE TITLE
Product Revenues sorting not working

### ISSUE THREAD

**Issue by movak** [matomo-org/matomo#8556] opened 2015-08-12 11:05 UTC
On the „Product SKU“ and „Product Category“ table the sorting of the „Product Revenue“ column does not work. Neither the ascending nor the descending sorting.

**Comment by mattab** [comment] 2015-08-14 15:10
Thanks @movak for the report, we'll investigate this

**Comment by tsteur** [comment] 2015-08-18 07:50
I tried to reproduce with latest Piwik version and seems to work for me. Which Piwik version are you using? Can you maybe post a screenshot?

![revenue](https://cloud.githubusercontent.com/assets/273120/9324876/72aa34bc-458e-11e5-8716-68e3f16a053e.png)

**Comment by movak** [comment] 2015-08-18 09:05
Yep, here's my screenshot:

![piwik bug](https://cloud.githubusercontent.com/assets/13764143/9326287/f70880ec-4598-11e5-9e65-21e23bbc3136.png)

**Comment by tsteur** [comment] 2015-08-18 09:07
What's your Piwik version?

**Comment by tsteur** [comment] 2015-08-18 09:10
Just switched to EUR and works for me as well (just in case sort was applied after formatting the metric), I see there are comma values, maybe the problem is related to locale. Will try

**Comment by tsteur** [comment] 2015-08-18 09:15
Still cannot reproduce it :( Maybe let us know a bit more about your environment, eg Piwik version and PHP version. Does it work for other columns?

**Comment by movak** [comment] 2015-08-18 09:25
Ops sry I forgot: 

Piwik 2.14.3
PHP 5.4.41-0+deb7u1

The sorting of this column doesn't work in the SKU and Product Category reports. All other columns seem to work fine.

**Comment by tsteur** [comment] 2015-08-18 10:06
Can maybe someone else try to reproduce on another instance?

**Comment by movak** [comment] 2015-08-18 14:27
I played a little bit with the date ranges and noticed something interesting: The sorting does not work only if data before the 7.8. are included. Now unfortunately I don't know if there are any problems between the 3th to the 5th as the item prices were all 0. But if I choose only the 6th, when items started to have prices > 0 it doesn't work. So I assume it has something to do with the items that were tracked on the sixth... I can also give you Piwik access for this test site if that helps.

**Comment by RaphaelBergmann** [comment] 2020-09-15 13:47
I know this is an old issue, but we just started tracking with Matomo last week, and for most days we have the same problem - the sorting by product revenue instead sorts by visitor number. It get's worse when we select any segment, then it even won't work for the "good" days... Currency is EUR.
Matomo-Version: 3.14.1
MySQL-Version: 10.1.45-MariaDB-0+deb9u1
PHP-Version: 7.4.10
![image](https://user-images.githubusercontent.com/2065979/93218385-733a0e00-f76a-11ea-864b-4d24fbe1aa9f.png)

**Comment by sgiehl** [comment] 2024-01-23 08:49
closing in favor of #21829

**Closed by sgiehl** 2024-01-23 08:49 UTC
