### ISSUE TITLE
The target link can always not be redirect successfuly using content-tracking

### ISSUE THREAD

**Issue by SophiaJOYME** [matomo-org/matomo#7782] opened 2015-04-28 03:45 UTC
Since I use piwik cotent-tracking, the href=/anylink will be replaced with a link to piwik.php of Piwik installation which will in turn redirect the user to the actual target to actually track the interaction. Actually, we cannot open the target link now, the redirection costs lot of time, and the link cannot be opend mostly. Any solution for that? Thanks!

**Comment by SophiaJOYME** [comment] 2015-04-28 03:53
If every tracked link would be redirected, how can we visit our website quickly?
http://developer.piwik.org/guides/content-tracking

**Comment by hazrina** [comment] 2015-04-28 06:56
test1

**Comment by SophiaJOYME** [comment] 2015-04-28 07:18
http://hhwqh.joyme.com/96703.shtml, the tracking now be added all second level pages first navigation except index page.

**Comment by SophiaJOYME** [comment] 2015-04-28 07:18
http://hhwqh.joyme.com/96703.shtml, the tracking now be added all second level pages first navigation except index page.

**Comment by SophiaJOYME** [comment] 2015-04-28 07:38
upload image failed :-(

**Comment by SophiaJOYME** [comment] 2015-04-28 10:01
![nav](https://cloud.githubusercontent.com/assets/12146838/7366910/1fc64e42-edce-11e4-9c29-6f424b1f15a3.JPG)

**Comment by mattab** [comment] 2015-07-14 17:16
Hi @tsteur do you know if it is possible to disable the piwik.php redirection, or would it be a feature request to be able to do Content Tracking without the `piwik.php` redirect? Couldn't find the info in http://developer.piwik.org/guides/content-tracking in a quick glance

**Comment by tsteur** [comment] 2015-07-14 17:44
It's not possible to do it. I'd prefer to completely remove `piwik.php` redirect unless we also that setting (that needs to be implemented) for outlinks. As we track context menu clicks and middle clicks etc as "clicked" we could do same here for content interactions and remove piwik.php redirect

**Comment by mattab** [comment] 2015-07-15 04:38
>  I'd prefer to completely remove `piwik.php` redirect 

I also like the idea of removing the `piwik.php` redirect completely, and use the same technique as for download/outlink tracking which is to send http request + wait 500ms (configurable) before redirecting to actual target. How much effort would it be do you think?

**Comment by tsteur** [comment] 2015-07-15 08:54
I don't remember the code too much but it shouldn't be too much work as everything is already there re Outlinks/Downloads. There's also to do: Adjusting tests, removing redirect feature in `piwik.php`, a lot of testing. Maybe 3-7 hours?

**Comment by mattab** [comment] 2019-02-24 20:34
Closing as duplicate of https://github.com/matomo-org/matomo/issues/12227 where we will remove the piwik.php redirect feature on content tracking (and use send beacon instead).

**Closed by mattab** 2019-02-24 20:34 UTC
Labels: Task
