### ISSUE TITLE
Allow more characters for referrer name (currently limited to 70)

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#9340] opened 2015-12-06 21:12 UTC
I just noticed the referrer name is truncated to 70 characters. For example the referrer name contains the domain of the referrer. With new feature to make Piwik as well handle paths it now also stored the path, not only the domain see https://github.com/piwik/piwik/pull/9320 . Eg `test.subdomain.apache.piwik.org/mysubsite/product1` (that's 51 characters). 70 characters are still quite a lot but it might be too short in some cases. Maybe we could increase it to 100 characters or so?

BTW: The referrer name might also contain a campaign name or the name of a search engine.

Adding to 3.0 milestone as it would require a schema change if we decide to increase it.

**Comment by sgiehl** [comment] 2019-12-09 12:54
duplicate of #13582

**Closed by sgiehl** 2019-12-09 12:54 UTC
Labels: Enhancement, duplicate
