### ISSUE TITLE
Support Emojis on Matomo Page Titles

### ISSUE THREAD

**Issue by scysys** [matomo-org/matomo#15547] opened 2020-02-10 17:38 UTC
Emojis in Page Titles are shown as � in Matomo.

**Example Page Title**
<img width="229" alt="Bildschirmfoto 2020-02-10 um 18 33 11" src="https://user-images.githubusercontent.com/1695531/74174203-d3485f00-4c33-11ea-9891-e4faca71e830.png">

**Ends up in**
![Bildschirmfoto 2020-02-10 um 18 35 02](https://user-images.githubusercontent.com/1695531/74174405-2fab7e80-4c34-11ea-9429-6f5ec789c3e6.png)

Maybe an good improvement for V4 ;)

**Comment by Findus23** [comment] 2020-02-10 17:43
Hi,

I think this is the same as https://github.com/matomo-org/matomo/issues/8790 which is already planned for Matomo 4 for years but as this requires a major database change (https://github.com/matomo-org/matomo/issues/9785) it can't be done before.

**Comment by sgiehl** [comment] 2020-02-10 18:19
Correct. It's planned for Matomo 4 and actually a duplicate of #8790

**Closed by sgiehl** 2020-02-10 18:19 UTC
